# Generated by Django 3.2.8 on 2022-09-07 01:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketdata', '0010_delete_virtualcut'),
        ('account', '0044_draftcashflow_action'),
        ('currency', '0002_auto_20220702_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxSpotMargin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('maintenance_rate', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('nfa_rate', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.broker')),
                ('data_cut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketdata.datacut')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.fxpair')),
            ],
            options={
                'verbose_name_plural': 'fxspotmargins',
                'unique_together': {('pair', 'data_cut', 'broker')},
            },
        ),
    ]
