# Generated by Django 3.2.8 on 2022-09-07 01:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_draftcashflow_action'),
        ('margin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarginDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('margin_requirement', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('excess_liquidity', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
            options={
                'unique_together': {('company', 'date')},
            },
        ),
    ]
