# Generated by Django 3.2.8 on 2022-10-13 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('margin', '0002_margindetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fxspotmargin',
            options={'verbose_name_plural': 'FX Spot margins'},
        ),
    ]
