# Generated by Django 3.2.8 on 2022-10-31 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0017_alter_ibkraccountsummary_account_type'),
        ('margin', '0004_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='funding_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ibkr.fundingrequest'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=11),
        ),
    ]
