# Generated by Django 4.2.3 on 2024-01-04 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_auto_20240105_0032'),
        ('margin', '0006_dailymargindetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='broker_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.brokeraccount'),
        ),
        migrations.AlterField(
            model_name='fxspotmargin',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.broker'),
        ),
    ]
