from main.apps.core.tasks.clean_a_table_in_database import clean_a_table_in_database
from main.apps.core.tasks.eod import eod_master_workflow, process_covariance_estimator_batch, process_all_covariance_estimator_batches
from main.apps.core.tasks.simple_activity_report_for_a_model import simple_activity_report_for_a_model
