# Generated by Django 3.2.8 on 2022-05-29 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20220526_0206'),
        ('currency', '0001_initial'),
        ('hedge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyMargin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.broker')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency')),
            ],
            options={
                'unique_together': {('broker', 'currency')},
            },
        ),
    ]
