# Generated by Django 3.2.8 on 2022-06-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0002_currencymargin'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounthedgerequest',
            name='commission',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='accounthedgerequest',
            name='commission_cntr',
            field=models.FloatField(null=True),
        ),
    ]
