# Generated by Django 3.2.8 on 2022-06-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0002_currencymargin'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencymargin',
            name='tier_from',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currencymargin',
            name='tier_to',
            field=models.FloatField(null=True),
        ),
    ]
