# Generated by Django 3.2.8 on 2022-06-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0004_benchmarkrate_interestrate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currencymargin',
            unique_together=set(),
        ),
    ]
