# Generated by Django 3.2.8 on 2022-06-11 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0003_auto_20220610_0154'),
        ('hedge', '0005_alter_currencymargin_unique_together'),
    ]

    operations = [
    ]
