# Generated by Django 3.2.8 on 2022-07-02 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20220702_1908'),
        ('hedge', '0006_merge_20220611_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounthedgerequest',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currency.fxpair'),
        ),
    ]
