# Generated by Django 3.2.8 on 2022-07-12 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0007_alter_accounthedgerequest_pair'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interestrate',
            old_name='rate_paid',
            new_name='rate',
        ),
        migrations.AddField(
            model_name='currencymargin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currencymargin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='currencymargin',
            name='tier_from',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currencymargin',
            name='tier_to',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interestrate',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='interestrate',
            name='tier_from',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
