# Generated by Django 3.2.8 on 2022-07-23 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0008_auto_20220712_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='fxspotmargin',
            name='maintenance_rate',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='fxspotmargin',
            name='nfa_rate',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
