# Generated by Django 3.2.8 on 2022-08-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0009_auto_20220723_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencymargin',
            name='tier_from',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interestrate',
            name='tier_from',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
