# Generated by Django 3.2.8 on 2022-09-07 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0010_auto_20220803_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FxSpotMargin',
        ),
    ]
