# Generated by Django 3.2.8 on 2022-10-01 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_alter_brokeraccount_company'),
        ('hedge', '0012_companyfxposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfxposition',
            name='broker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fxbroker', to='account.brokeraccount'),
        ),
    ]
