# Generated by Django 3.2.8 on 2022-10-03 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_alter_brokeraccount_company'),
        ('hedge', '0013_alter_companyfxposition_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='omsorderrequest',
            name='broker_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.brokeraccount'),
            preserve_default=False,
        ),
    ]
