# Generated by Django 3.2.8 on 2022-10-07 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_alter_brokeraccount_company'),
        ('currency', '0002_auto_20220702_1908'),
        ('hedge', '0014_omsorderrequest_broker_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyfxposition',
            old_name='broker',
            new_name='broker_account',
        ),
        migrations.AlterUniqueTogether(
            name='companyfxposition',
            unique_together={('record_time', 'company', 'positions_type', 'broker_account', 'fxpair')},
        ),
    ]
