# Generated by Django 3.2.8 on 2022-10-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0016_auto_20221008_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyhedgeaction',
            name='virtual_data_cut',
        ),
        migrations.AlterField(
            model_name='fxposition',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
