# Generated by Django 3.2.8 on 2022-10-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0017_auto_20221009_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencymargin',
            name='spread',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interestrate',
            name='spread',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
