# Generated by Django 3.2.8 on 2022-10-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0018_auto_20221013_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencymargin',
            name='spread',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interestrate',
            name='spread',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
