# Generated by Django 3.2.8 on 2022-10-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0019_auto_20221013_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencymargin',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
