# Generated by Django 3.2.8 on 2022-10-29 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_auto_20221019_2204'),
        ('hedge', '0020_currencymargin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxposition',
            name='company_hedge_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hedge.companyhedgeaction'),
        ),
        migrations.CreateModel(
            name='CompanyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
        migrations.AddField(
            model_name='fxposition',
            name='company_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hedge.companyevent'),
        ),
    ]
