# Generated by Django 3.2.8 on 2022-10-30 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0021_auto_20221029_1459'),
        ('hedge', '0021_delete_fxrolloverrate'),
    ]

    operations = [
    ]
