# Generated by Django 3.2.8 on 2022-11-10 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20220702_1908'),
        ('account', '0057_merge_0056_alter_broker_name_0056_auto_20221109_0153'),
        ('hedge', '0023_auto_20221030_1623'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyfxposition',
            unique_together={('snapshot_event', 'company', 'broker_account', 'fxpair')},
        ),
    ]
