# Generated by Django 3.2.8 on 2022-11-10 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0057_merge_0056_alter_broker_name_0056_auto_20221109_0153'),
        ('currency', '0002_auto_20220702_1908'),
        ('hedge', '0024_alter_companyfxposition_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyfxposition',
            unique_together={('record_time', 'company', 'broker_account', 'fxpair'), ('snapshot_event', 'company', 'broker_account', 'fxpair')},
        ),
    ]
