# Generated by Django 3.2.8 on 2022-12-12 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0025_alter_companyfxposition_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyfxposition',
            options={'verbose_name_plural': 'Company FX Positions'},
        ),
    ]
