# Generated by Django 3.2.8 on 2022-12-18 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20220702_1908'),
        ('account', '0069_user_phone_otp_code'),
        ('hedge', '0026_alter_companyfxposition_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDesiredPositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('fxpair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.fxpair')),
                ('snapshot_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hedge.companyevent')),
            ],
            options={
                'verbose_name_plural': 'Account Desired Positions',
                'unique_together': {('snapshot_event', 'account', 'fxpair')},
            },
        ),
    ]
