# Generated by Django 3.2.8 on 2022-12-20 02:09

from django.db import migrations

from main.apps.hedge.models import HedgeSettings


def fix_incorrect_hedge_settings_naming_convention(apps, schema_editor):
    settings = HedgeSettings.objects.all()
    for setting in settings:
        if "vol_target_reduction" in setting.custom:
            vol_target_reduction = setting.custom['vol_target_reduction']
            setting.custom = {
                "VolTargetReduction": vol_target_reduction
            }
            setting.save()


class Migration(migrations.Migration):
    dependencies = [
        ('hedge', '0028_auto_20221220_0308'),
    ]

    operations = [
        migrations.RunPython(fix_incorrect_hedge_settings_naming_convention)
    ]
