# Generated by Django 3.2.8 on 2023-01-02 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0029_fix_incorrect_hedge_settings_naming_convention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxposition',
            name='company_hedge_action',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hedge.companyhedgeaction'),
        ),
    ]
