# Generated by Django 3.2.8 on 2023-01-22 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0070_company_onboarded'),
        ('currency', '0002_auto_20220702_1908'),
        ('hedge', '0030_alter_fxposition_company_hedge_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxposition',
            name='company_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hedge.companyevent'),
        ),
        migrations.AlterUniqueTogether(
            name='fxposition',
            unique_together={('company_event', 'account', 'fxpair')},
        ),
        migrations.RemoveField(
            model_name='fxposition',
            name='company_hedge_action',
        ),
    ]
