# Generated by Django 3.2.8 on 2023-01-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0031_auto_20230122_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='omsorderrequest',
            old_name='pnl_account_currency',
            new_name='cntr_commission',
        ),
        migrations.RenameField(
            model_name='omsorderrequest',
            old_name='pnl_quote_currency',
            new_name='commission',
        ),
        migrations.AddField(
            model_name='omsorderrequest',
            name='expected_cost',
            field=models.FloatField(null=True),
        ),
    ]
