# Generated by Django 3.2.8 on 2023-01-29 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0070_company_onboarded'),
        ('currency', '0002_auto_20220702_1908'),
        ('hedge', '0032_auto_20230123_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfxposition',
            name='snapshot_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hedge.companyevent'),
        ),
        migrations.AlterUniqueTogether(
            name='companyfxposition',
            unique_together={('snapshot_event', 'company', 'broker_account', 'fxpair')},
        ),
        migrations.RemoveField(
            model_name='companyfxposition',
            name='record_time',
        ),
    ]
