# Generated by Django 3.2.8 on 2023-02-13 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0071_alter_cashflow_status'),
        ('currency', '0002_auto_20220702_1908'),
        ('hedge', '0033_auto_20230129_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCashHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('broker_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fxbroker_account_cch', to='account.brokeraccount')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_currency_cch', to='currency.currency')),
                ('snapshot_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hedge.companyevent')),
            ],
            options={
                'verbose_name_plural': 'Company FX Positions',
                'unique_together': {('snapshot_event', 'broker_account', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='CompanyAccruedCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('broker_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fxbroker_account_cac', to='account.brokeraccount')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_currency_cac', to='currency.currency')),
                ('snapshot_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hedge.companyevent')),
            ],
            options={
                'verbose_name_plural': 'Company FX Positions',
                'unique_together': {('snapshot_event', 'broker_account', 'currency')},
            },
        ),
    ]
