# Generated by Django 3.2.8 on 2023-02-19 20:29

from django.db import migrations, models
import django.db.models.deletion

import hdlib
from hdlib.Instrument.FxForward import FxForwardInstrument


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20220702_1908'),
        ('account', '0071_alter_cashflow_status'),
        ('hedge', '0034_companyaccruedcash_companycashholding'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxForwardPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('delivery_time', models.DateTimeField()),
                ('enter_time', models.DateTimeField()),
                ('forward_price', models.FloatField()),
                ('unwind_price', models.FloatField(default=None, null=True)),
                ('unwind_time', models.DateTimeField(default=None, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwardfxaccount', to='account.account')),
                ('fxpair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwardfxpair', to='currency.fxpair')),
            ],
            options={
                'verbose_name_plural': 'fxforwardpositions',
                'unique_together': {('account', 'fxpair', 'amount', 'delivery_time', 'enter_time')},
            },
            bases=(models.Model, hdlib.Instrument.FxForward.FxForwardInstrument),
        ),
    ]
