# Generated by Django 3.2.8 on 2023-02-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0034_companyaccruedcash_companycashholding'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdesiredpositions',
            name='pre_liquidity_amount',
            field=models.FloatField(null=True),
        ),
    ]
