# Generated by Django 3.2.8 on 2023-03-13 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_auto_20230228_0256'),
        ('hedge', '0036_demoorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidityPoolRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_exposure', models.FloatField(default=0.0)),
                ('pool_useage', models.FloatField(default=0.0)),
                ('is_live', models.BooleanField()),
                ('company_hedge_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hedge.companyhedgeaction')),
                ('fxpair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fxpair_lp_record', to='currency.fxpair')),
            ],
        ),
    ]
