# Generated by Django 3.2.8 on 2023-03-23 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0035_fxforwardposition'),
        ('hedge', '0037_liquiditypoolrecord'),
    ]

    operations = [
    ]
