# Generated by Django 3.2.8 on 2023-06-25 16:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_auto_20230323_0038'),
        ('account', '0076_alter_cashflow_status'),
        ('hedge', '0038_merge_0035_fxforwardposition_0037_liquiditypoolrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='fxforwardposition',
            name='cashflow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fxforwardposition',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fxforwardposition',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='fxforwardposition',
            name='unwind_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fxforwardposition',
            name='unwind_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='fxforwardposition',
            unique_together={('cashflow', 'fxpair', 'amount', 'delivery_time', 'enter_time')},
        ),
        migrations.CreateModel(
            name='DraftFxForwardPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('draft', 'DRAFT'), ('pending_activation', 'PENDING ACTIVATION'), ('active', 'ACTIVE')], default='pending_activation', max_length=24)),
                ('risk_reduction', models.FloatField()),
                ('delivery_time', models.DateTimeField()),
                ('cashflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.cashflow')),
                ('draft_cashflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.draftcashflow')),
                ('fxpair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.fxpair')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='fxforwardposition',
            name='account',
        ),
    ]
