# Generated by Django 3.2.8 on 2023-06-28 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0077_company_rep'),
        ('hedge', '0039_auto_20230625_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxforwardposition',
            name='cashflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.cashflow'),
        ),
    ]
