# Generated by Django 3.2.8 on 2023-07-27 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0077_company_rep'),
        ('hedge', '0041_draftfxforwardposition_beneficiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxforwardposition',
            name='cashflow',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.cashflow'),
        ),
    ]
