# Generated by Django 3.2.8 on 2023-08-05 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0042_alter_fxforwardposition_cashflow'),
        ('hedge', '0043_remove_draftfxforwardposition_fxpair'),
    ]

    operations = [
    ]
