# Generated by Django 4.2.3 on 2023-10-01 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0009_merge_20230907_1337"),
        ("account", "0079_account_strategy_parachutecashflow_parachutedata"),
        ("hedge", "0046_remove_draftfxforwardposition_delivery_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fxforwardposition",
            name="account",
            # We actually want this to be non-nullable, but we can't do that until we've migrated all the data.
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.account",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fxforwardposition",
            name="cashflow",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.cashflow",
            ),
        ),
        migrations.CreateModel(
            name="ParachuteRecordFxPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_exposure", models.FloatField(default=0.0)),
                ("unhedged_exposure", models.FloatField(default=0.0)),
                (
                    "company_hedge_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hedge.companyhedgeaction",
                    ),
                ),
                (
                    "fxpair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fxpair_parachute_record",
                        to="currency.fxpair",
                    ),
                ),
                (
                    "parachute_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.account",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "parachute_record_fxpairs",
                "unique_together": {
                    ("parachute_account", "company_hedge_action", "fxpair")
                },
            },
        ),
        migrations.CreateModel(
            name="ParachuteRecordAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bucket", models.IntegerField()),
                ("limit_value", models.FloatField(default=0.0)),
                ("p_limit", models.FloatField(default=0.0)),
                ("cashflows_npv", models.FloatField(default=0.0)),
                ("forwards_pnl", models.FloatField(default=0.0)),
                ("ann_volatility", models.FloatField(default=None, null=True)),
                ("volatility", models.FloatField(default=None, null=True)),
                ("p_no_breach", models.FloatField(default=0.0, null=True)),
                ("time_horizon", models.IntegerField(default=0)),
                ("fraction_to_hedge", models.FloatField(default=0.0)),
                ("sum_abs_remaining", models.FloatField(default=-1.0)),
                (
                    "company_hedge_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hedge.companyhedgeaction",
                    ),
                ),
                (
                    "parachute_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.account",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "parachute_record_accounts",
                "unique_together": {
                    ("parachute_account", "company_hedge_action", "bucket")
                },
            },
        ),
    ]
