# Generated by Django 4.2.3 on 2023-10-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0047_draftfxforwardposition_settlement_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftfxforwardposition',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='draftfxforwardposition',
            name='settlement_account',
        ),
        migrations.AddField(
            model_name='draftfxforwardposition',
            name='cash_settle_account',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='draftfxforwardposition',
            name='destination_account',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='draftfxforwardposition',
            name='funding_account',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='draftfxforwardposition',
            name='is_cash_settle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='draftfxforwardposition',
            name='origin_account',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
