# Generated by Django 4.2.3 on 2023-10-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0048_remove_draftfxforwardposition_beneficiary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftfxforwardposition',
            name='purpose_of_payment',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
