# Generated by Django 4.2.3 on 2023-10-12 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0080_merge_20231009_2008'),
        ('hedge', '0050_draftfxforwardposition_destination_account_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draftfxforwardposition',
            options={'verbose_name_plural': 'Draft FX Forward Positions'},
        ),
        migrations.AlterModelOptions(
            name='fxforwardposition',
            options={'verbose_name_plural': 'FX Forward Positions'},
        ),
        migrations.AlterField(
            model_name='draftfxforwardposition',
            name='cash_settle_account',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='draftfxforwardposition',
            name='cashflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.cashflow'),
        ),
        migrations.AlterField(
            model_name='draftfxforwardposition',
            name='destination_account',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='draftfxforwardposition',
            name='destination_account_type',
            field=models.CharField(blank=True, choices=[('W', 'Wire'), ('E', 'iACH'), ('C', 'FXBalance')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='draftfxforwardposition',
            name='draft_cashflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.draftcashflow'),
        ),
        migrations.AlterField(
            model_name='draftfxforwardposition',
            name='estimated_fx_forward_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='draftfxforwardposition',
            name='funding_account',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='draftfxforwardposition',
            name='origin_account',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='draftfxforwardposition',
            name='purpose_of_payment',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
