# Generated by Django 4.2.3 on 2023-12-08 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0047_fxforwardposition_account_and_more'),
        ('hedge', '0051_alter_draftfxforwardposition_options_and_more'),
    ]

    operations = [
    ]
