# Generated by Django 4.2.3 on 2023-12-18 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0087_alter_cashflow_created_alter_draftcashflow_created'),
        ('hedge', '0051_alter_draftfxforwardposition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftfxforwardposition',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.installmentcashflow'),
        ),
    ]
