# Generated by Django 4.2.3 on 2024-01-04 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
        ('hedge', '0052_draftfxforwardposition_installment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmarkrate',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.broker'),
        ),
        migrations.AlterField(
            model_name='companyaccruedcash',
            name='broker_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fxbroker_account_cac', to='broker.brokeraccount'),
        ),
        migrations.AlterField(
            model_name='companycashholding',
            name='broker_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fxbroker_account_cch', to='broker.brokeraccount'),
        ),
        migrations.AlterField(
            model_name='companyfxposition',
            name='broker_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fxbroker_account', to='broker.brokeraccount'),
        ),
        migrations.AlterField(
            model_name='currencymargin',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.broker'),
        ),
        migrations.AlterField(
            model_name='fxspotcommission',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.broker'),
        ),
        migrations.AlterField(
            model_name='fxspotspread',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.broker'),
        ),
        migrations.AlterField(
            model_name='interestrate',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.broker'),
        ),
        migrations.AlterField(
            model_name='omsorderrequest',
            name='broker_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.brokeraccount'),
        ),
    ]
