# Generated by Django 4.2.7 on 2024-01-17 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0088_auto_20240109_1842'),
        ('hedge', '0053_alter_draftfxforwardposition_draft_cashflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftfxforwardposition',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
    ]
