# Generated by Django 4.2.7 on 2024-01-17 06:16

from django.db import migrations, models
import django.db.models.deletion

def populate_company_for_draft_forward(apps, schema_editor):
    DraftFxForwardPosition = apps.get_model("hedge", 'DraftFxForwardPosition')
    for draft in DraftFxForwardPosition.objects.all():
        if draft.cashflow is not None:
            draft.company = draft.cashflow.account.company
        if draft.draft_cashflow is not None:
            draft.company = draft.draft_cashflow.company
        if draft.installment is not None:
            draft.company = draft.installment.company
        draft.save()
        if draft.company is None:
            draft.delete()
class Migration(migrations.Migration):

    dependencies = [
        ('account', '0088_auto_20240109_1842'),
        ('hedge', '0054_draftfxforwardposition_company'),
    ]

    operations = [
        migrations.RunPython(populate_company_for_draft_forward),
        migrations.AlterField(
            model_name='draftfxforwardposition',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
    ]
