# Generated by Django 4.2.3 on 2023-12-13 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hedge", "0054_auto_20231212_0130"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ParachuteRecordFxPair",
        ),
    ]
