# Generated by Django 4.2.3 on 2024-01-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedge", "0055_delete_parachuterecordfxpair"),
    ]

    operations = [
        migrations.AddField(
            model_name="parachuterecordaccount",
            name="realized_pnl",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="parachuterecordaccount",
            name="unrealized_pnl",
            field=models.FloatField(default=0.0),
        ),
    ]
