# Generated by Django 4.2.10 on 2024-03-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0055_alter_draftfxforwardposition_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='fxforwardposition',
            name='cntr_amount',
            field=models.FloatField(null=True),
        ),
    ]
