# Generated by Django 4.2.3 on 2024-01-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0053_alter_benchmarkrate_broker_and_more'),
        ('hedge', '0055_alter_draftfxforwardposition_company'),
    ]

    operations = [
    ]
