# Generated by Django 4.2.3 on 2024-01-06 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0091_alter_account_strategy"),
        ("currency", "0018_alter_currency_options_alter_fxpair_options"),
        ("hedge", "0056_parachuterecordaccount_realized_pnl_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParachuteSpotPositions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bucket", models.IntegerField()),
                ("amount", models.FloatField(default=0.0)),
                ("total_price", models.FloatField(default=0.0)),
                (
                    "company_hedge_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hedge.companyhedgeaction",
                    ),
                ),
                (
                    "fxpair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="currency.fxpair",
                    ),
                ),
                (
                    "parachute_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.account",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "parachute_record_accounts",
                "unique_together": {
                    ("parachute_account", "company_hedge_action", "bucket")
                },
            },
        ),
    ]
