# Generated by Django 4.2.3 on 2024-01-06 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0091_alter_account_strategy"),
        ("currency", "0018_alter_currency_options_alter_fxpair_options"),
        ("hedge", "0057_parachutespotpositions"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="parachutespotpositions",
            unique_together={
                ("parachute_account", "company_hedge_action", "fxpair", "bucket")
            },
        ),
    ]
