# Generated by Django 4.2.3 on 2024-01-08 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0052_draftfxforwardposition_installment'),
        ('hedge', '0058_alter_parachutespotpositions_unique_together'),
    ]

    operations = [
    ]
