# Generated by Django 4.2.3 on 2024-01-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedge", "0059_merge_20240108_2301"),
    ]

    operations = [
        migrations.AddField(
            model_name="fxforwardposition",
            name="initial_spot_price",
            field=models.FloatField(null=True),
        ),
    ]
