# Generated by Django 4.2.7 on 2024-01-18 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0055_alter_draftfxforwardposition_company'),
        ('hedge', '0060_fxforwardposition_initial_spot_price'),
    ]

    operations = [
    ]
