# Generated by Django 4.2.7 on 2024-01-18 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0053_alter_benchmarkrate_broker_and_more'),
        ('hedge', '0061_merge_20240118_0247'),
    ]

    operations = [
    ]
