# Generated by Django 4.2.3 on 2024-01-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedge", "0064_alter_parachuterecordaccount_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fxforwardposition",
            name="initial_pangea_forward_price",
            field=models.FloatField(default=None, null=True),
        ),
    ]
