# Generated by Django 4.2.7 on 2024-02-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedge", "0066_parachuterecordaccount_adjusted_limit_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parachuterecordaccount",
            name="account_pnl",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="parachuterecordaccount",
            name="bucket_npv",
            field=models.FloatField(default=0.0),
        ),
    ]
