# Generated by Django 4.2.7 on 2024-02-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedge", "0067_parachuterecordaccount_account_pnl_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parachuterecordaccount",
            name="client_implied_cash_pnl",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="parachuterecordaccount",
            name="forward_client_cash_one_day_pnl",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="parachuterecordaccount",
            name="implied_minimum_client_cash",
            field=models.FloatField(default=0.0),
        ),
    ]
