# Generated by Django 4.2.10 on 2024-03-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0056_fxforwardposition_cntr_amount'),
        ('hedge', '0068_parachuterecordaccount_client_implied_cash_pnl_and_more'),
    ]

    operations = [
    ]
