-- -- Reset marketdata --
DELETE FROM marketdata_cmasset;
ALTER SEQUENCE marketdata_cmasset_id_seq RESTART WITH 1;
DELETE FROM marketdata_cminstrument;
ALTER SEQUENCE marketdata_cminstrument_id_seq RESTART WITH 1;
DELETE FROM marketdata_cminstrumentdata;
ALTER SEQUENCE marketdata_cminstrumentdata_id_seq RESTART WITH 1;
DELETE FROM marketdata_cmspot;
ALTER SEQUENCE marketdata_cmspot_id_seq RESTART WITH 1;
DELETE FROM marketdata_eq;
ALTER SEQUENCE marketdata_eq_id_seq RESTART WITH 1;
DELETE FROM marketdata_eqasset;
ALTER SEQUENCE marketdata_eqasset_id_seq RESTART WITH 1;
DELETE FROM marketdata_fxestimator;
ALTER SEQUENCE marketdata_fxestimator_id_seq RESTART WITH 1;
DELETE FROM marketdata_fxforward;
ALTER SEQUENCE marketdata_fxforward_id_seq RESTART WITH 1;
DELETE FROM marketdata_fxmarketconvention;
ALTER SEQUENCE marketdata_fxmarketconvention_id_seq RESTART WITH 1;
DELETE FROM marketdata_fxspot;
ALTER SEQUENCE marketdata_fxspot_id_seq RESTART WITH 1;
DELETE FROM marketdata_fxspotbenchmark;
ALTER SEQUENCE marketdata_fxspotbenchmark_id_seq RESTART WITH 1;
DELETE FROM marketdata_fxspotcovariance;
ALTER SEQUENCE marketdata_fxspotcovariance_id_seq RESTART WITH 1;
DELETE FROM marketdata_fxspoteod;
ALTER SEQUENCE marketdata_fxspoteod_id_seq RESTART WITH 1;
DELETE FROM marketdata_fxspotintra;
ALTER SEQUENCE marketdata_fxspotintra_id_seq RESTART WITH 1;
DELETE FROM marketdata_fxspotrange;
ALTER SEQUENCE marketdata_fxspotrange_id_seq RESTART WITH 1;
DELETE FROM marketdata_fxspotrangeeod;
ALTER SEQUENCE marketdata_fxspotrangeeod_id_seq RESTART WITH 1;
DELETE FROM marketdata_fxspotrangeintra;
ALTER SEQUENCE marketdata_fxspotrangeintra_id_seq RESTART WITH 1;
DELETE FROM marketdata_fxspotvol;
ALTER SEQUENCE marketdata_fxspotvol_id_seq RESTART WITH 1;
DELETE FROM marketdata_govbond;
ALTER SEQUENCE marketdata_govbond_id_seq RESTART WITH 1;
DELETE FROM marketdata_iborrate;
ALTER SEQUENCE marketdata_iborrate_id_seq RESTART WITH 1;
DELETE FROM marketdata_irdiscount;
ALTER SEQUENCE marketdata_irdiscount_id_seq RESTART WITH 1;
DELETE FROM marketdata_oisrate;
ALTER SEQUENCE marketdata_oisrate_id_seq RESTART WITH 1;
DELETE FROM marketdata_option;
ALTER SEQUENCE marketdata_option_id_seq RESTART WITH 1;
DELETE FROM marketdata_optionstrategy;
ALTER SEQUENCE marketdata_optionstrategy_id_seq RESTART WITH 1;
DELETE FROM marketdata_virtualcut;
ALTER SEQUENCE marketdata_virtualcut_id_seq RESTART WITH 1;
DELETE FROM marketdata_datacut;
ALTER SEQUENCE marketdata_datacut_id_seq RESTART WITH 1;
update dataprovider_file set status = 1;
