# Generated by Django 3.2.8 on 2022-05-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='account_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
