# Generated by Django 3.2.8 on 2022-05-09 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_company_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='account_id',
            new_name='ibkr_account_id',
        ),
    ]
