# Generated by Django 3.2.8 on 2022-06-13 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_brokeraccount_account_type'),
        ('account', '0008_auto_20220607_0553'),
    ]

    operations = [
    ]
