# Generated by Django 3.2.8 on 2022-06-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_cashflow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Draft'), (2, 'Active'), (3, 'Pending Deactivation')], default=1),
        ),
    ]
