# Generated by Django 3.2.8 on 2022-06-22 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_merge_20220614_1719'),
        ('account', '0012_recurringcashflow_description'),
    ]

    operations = [
    ]
