# Generated by Django 3.2.8 on 2022-06-22 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_cashflow_status'),
        ('account', '0013_merge_20220622_0236'),
    ]

    operations = [
    ]
