# Generated by Django 3.2.8 on 2022-06-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_merge_20220622_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='status',
            field=models.IntegerField(choices=[(0, 'INACTIVE'), (1, 'DRAFT'), (2, 'PENDING ACTIVATION'), (3, 'ACTIVE'), (4, 'PENDING_DEACTIVATION')], default=1),
        ),
    ]
