# Generated by Django 3.2.8 on 2022-06-23 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_cashflow_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflow',
            name='is_visible',
        ),
    ]
