# Generated by Django 3.2.8 on 2022-06-25 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_remove_cashflow_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='installment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.installmentcashflow'),
        ),
        migrations.AlterUniqueTogether(
            name='installmentcashflow',
            unique_together={('account', 'installment_name')},
        ),
        migrations.RemoveField(
            model_name='installmentcashflow',
            name='cashflow',
        ),
    ]
