# Generated by Django 3.2.8 on 2022-06-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_remove_cashflow_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='status',
            field=models.CharField(choices=[('inactive', 'INACTIVE'), ('draft', 'DRAFT'), ('pending_activation', 'PENDING ACTIVATION'), ('active', 'ACTIVE'), ('pending_deactivation', 'PENDING_DEACTIVATION')], default='draft', max_length=24),
        ),
    ]
