# Generated by Django 3.2.8 on 2022-06-26 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_cashflow_status'),
        ('account', '0020_auto_20220625_1405'),
    ]

    operations = [
    ]
