# Generated by Django 3.2.8 on 2022-07-02 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20220702_1908'),
        ('account', '0021_merge_20220627_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcurrency',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accurr_currency', to='currency.currency'),
        ),
        migrations.AlterField(
            model_name='brokeraccount',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.broker'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency', to='currency.currency'),
        ),
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comp_currency', to='currency.currency'),
        )
    ]
