# Generated by Django 3.2.8 on 2022-06-30 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_merge_20220626_2335'),
        ('account', '0021_merge_20220627_1143'),
    ]

    operations = [
    ]
