# Generated by Django 3.2.8 on 2022-07-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_merge_20220627_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflow',
            name='original',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='parent',
        ),
        migrations.AddField(
            model_name='cashflow',
            name='calendar_type',
            field=models.IntegerField(choices=[(1, 'Null Calendar'), (2, 'Western Calendar')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='periodicity',
            field=models.TextField(null=True),
        ),
    ]
