# Generated by Django 3.2.8 on 2022-07-03 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20220703_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='calendar_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Null Calendar'), (2, 'Western Calendar')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.installmentcashflow'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='periodicity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
