# Generated by Django 3.2.8 on 2022-07-04 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20220702_1908'),
        ('account', '0025_delete_recurringcashflow'),
    ]

    operations = [
    ]
