# Generated by Django 3.2.8 on 2022-07-04 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_merge_20220704_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflow',
            old_name='calendar_type',
            new_name='calendar',
        ),
    ]
