# Generated by Django 3.2.8 on 2022-07-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_rename_calendar_type_cashflow_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='calendar',
            field=models.CharField(blank=True, choices=[('inactive', 'INACTIVE'), ('NULL_CALENDAR', 'NULL_CALENDAR'), ('WESTERN_CALENDAR', 'WESTERN_CALENDAR')], default='NULL_CALENDAR', max_length=64, null=True),
        ),
    ]
