# Generated by Django 3.2.8 on 2022-07-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_alter_cashflow_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='roll_convention',
            field=models.CharField(blank=True, choices=[('UNADJUSTED', 'Unadjusted'), ('FOLLOWING', 'Following'), ('MODIFIED_FOLLOWING', 'Modified Following'), ('HALF_MONTH_MODIFIED_FOLLOWING', 'Half Month Modified Following'), ('PRECEDING', 'Preceding'), ('MODIFIED_PRECEDING', 'Modified Preceding'), ('NEAREST', 'Nearest')], default='UNADJUSTED', max_length=64, null=True),
        ),
    ]
