# Generated by Django 3.2.8 on 2022-07-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_auto_20220709_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='calendar',
            field=models.CharField(blank=True, choices=[('NULL_CALENDAR', 'NULL_CALENDAR'), ('WESTERN_CALENDAR', 'WESTERN_CALENDAR')], default='NULL_CALENDAR', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='draftcashflow',
            name='calendar',
            field=models.CharField(blank=True, choices=[('NULL_CALENDAR', 'NULL_CALENDAR'), ('WESTERN_CALENDAR', 'WESTERN_CALENDAR')], default='NULL_CALENDAR', max_length=64, null=True),
        ),
    ]
