# Generated by Django 3.2.8 on 2022-07-17 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_auto_20220715_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentcashflow',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='installmentcashflow',
            unique_together={('company', 'installment_name')},
        ),
        migrations.RemoveField(
            model_name='installmentcashflow',
            name='account',
        ),
    ]
