# Generated by Django 3.2.8 on 2022-07-17 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_auto_20220717_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftcashflow',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.installmentcashflow'),
        ),
    ]
