# Generated by Django 3.2.8 on 2022-07-19 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_merge_20220630_1410'),
        ('account', '0033_draftcashflow_installment'),
    ]

    operations = [
    ]
