# Generated by Django 3.2.8 on 2022-07-29 04:18

from django.db import migrations, models
import phonenumber_field.modelfields
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_auto_20220729_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='UTC'),
        ),
    ]
