# Generated by Django 3.2.8 on 2022-07-29 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_auto_20220729_0418'),
        ('account', '0036_auto_20220729_0701'),
    ]

    operations = [
    ]
