# Generated by Django 3.2.8 on 2022-08-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_alter_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_setup_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
