# Generated by Django 3.2.8 on 2022-08-06 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_user_stripe_setup_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftcashflow',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='account.account'),
        ),
    ]
