# Generated by Django 3.2.8 on 2022-08-09 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_companycontactorder'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='installmentcashflow',
            unique_together=set(),
        ),
    ]
