# Generated by Django 3.2.8 on 2022-09-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0044_draftcashflow_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_setup_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
