# Generated by Django 3.2.8 on 2022-09-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_company_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='hs_company_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hs_contact_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
