# Generated by Django 3.2.8 on 2022-09-18 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokeraccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_accounts', to='account.company'),
        ),
    ]
