# Generated by Django 3.2.8 on 2022-10-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_alter_brokeraccount_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='draftcashflow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
