# Generated by Django 3.2.8 on 2022-10-31 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_auto_20221019_2204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deposit',
        ),
    ]
