# Generated by Django 3.2.8 on 2022-11-05 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_delete_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftcashflow',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='account.account'),
        ),
    ]
