# Generated by Django 3.2.8 on 2022-11-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0055_alter_draftcashflow_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
