# Generated by Django 3.2.8 on 2022-11-10 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0056_alter_broker_name'),
        ('account', '0056_auto_20221109_0153'),
    ]

    operations = [
    ]
