# Generated by Django 3.2.8 on 2022-11-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0057_merge_0056_alter_broker_name_0056_auto_20221109_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
