# Generated by Django 3.2.8 on 2022-11-14 01:34

from django.db import migrations
import uuid


def remove_temp_accounts(apps, schema_editor):
    Account = apps.get_model('account', 'Account')
    for account in Account.objects.all():
        try:
            _ = uuid.UUID(account.name)
            account.delete()
        except ValueError:
            pass


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0059_delete_accountcurrency'),
    ]

    operations = [
        migrations.RunPython(remove_temp_accounts)
    ]
