# Generated by Django 3.2.8 on 2022-11-14 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0060_companyjoinrequest'),
        ('account', '0060_remove_temp_accounts'),
    ]

    operations = [
    ]
