# Generated by Django 3.2.8 on 2022-11-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0061_merge_20221114_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyjoinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=60),
        ),
    ]
