# Generated by Django 3.2.8 on 2022-12-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0068_switch_low_high'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
