# Generated by Django 3.2.8 on 2023-01-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0069_user_phone_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
