# Generated by Django 3.2.8 on 2023-03-16 23:31

from django.db import migrations, models

from main.apps.broker.models import BrokerAccountCapability


def seed_broker_account_capabilities(apps, schema_editor):
    model = apps.get_model('account', 'BrokerAccountCapability')
    trade = model(type=BrokerAccountCapability.Types.TRADE)
    fund = model(type=BrokerAccountCapability.Types.FUND)
    trade.save()
    fund.save()

class Migration(migrations.Migration):

    dependencies = [
        ('account', '0072_alter_cashflow_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerAccountCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('trade', 'Trade'), ('fund', 'Fund')], max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Broker Account Capabilities',
            },
        ),
        migrations.AddField(
            model_name='brokeraccount',
            name='capabilities',
            field=models.ManyToManyField(to='account.BrokerAccountCapability'),
        ),
        migrations.RunPython(seed_broker_account_capabilities)
    ]
