# Generated by Django 3.2.8 on 2023-04-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0075_alter_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='status',
            field=models.CharField(choices=[('inactive', 'INACTIVE'), ('pending_approval', 'PENDING APPROVAL'), ('pending_activation', 'PENDING ACTIVATION'), ('active', 'ACTIVE'), ('pending_deactivation', 'PENDING DEACTIVATION'), ('pending_margin', 'PENDING MARGIN'), ('pending_payment', 'PENDING PAYMENT'), ('payment_fail', 'PAYMENT FAIL')], default='pending_activation', max_length=24),
        ),
    ]
