# Generated by Django 3.2.8 on 2023-06-23 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0076_alter_cashflow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='rep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
