# Generated by Django 4.2.4 on 2023-08-26 15:01


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_auto_20230808_2148'),
        ('account', '0077_company_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_currency', to='currency.currency'),
        ),
        migrations.AlterField(
            model_name='draftcashflow',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_currency', to='currency.currency'),
        ),
    ]
