# Generated by Django 4.2.3 on 2023-10-01 18:04

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0009_merge_20230907_1337"),
        ("account", "0078_alter_cashflow_currency_alter_draftcashflow_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="strategy",
            field=models.IntegerField(
                choices=[(0, "Spot Hedging"), (1, "Parachute")], default=0
            ),
        ),
        migrations.CreateModel(
            name="ParachuteCashFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("pay_date", models.DateTimeField()),
                ("amount", models.FloatField()),
                ("generation_time", models.DateTimeField()),
                ("deactivation_date", models.DateTimeField(default=None, null=True)),
                (
                    "deactivated_by_rolloff",
                    models.BooleanField(default=None, null=True),
                ),
                ("initial_npv", models.FloatField(null=True)),
                ("initial_spot", models.FloatField()),
                ("final_npv", models.FloatField(default=None, null=True)),
                ("final_spot", models.FloatField(default=None, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.account",
                    ),
                ),
                (
                    "cashflow_generator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="account.cashflow",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_currency",
                        to="currency.currency",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ParachuteData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lower_limit", models.FloatField()),
                ("lower_p", models.FloatField(default=0.95)),
                ("upper_p", models.FloatField(default=0.99)),
                ("hedged_fraction", models.FloatField(default=0.0)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.account",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "parachute_data",
                "unique_together": {("account",)},
            },
        ),
    ]
