# Generated by Django 4.2.3 on 2023-10-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0078_alter_cashflow_currency_alter_draftcashflow_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='estimated_aum',
            field=models.CharField(choices=[('aum_under_10k', '$1,000 - 9,999'), ('aum_10k_to_100k', '$10,000 - 99,999'), ('aum_100k_to_1m', '$100,000 - 999,999'), ('aum_above_1m', '$1,000,000+')], max_length=50, null=True),
        ),
    ]
