# Generated by Django 4.2.3 on 2023-10-09 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0079_company_estimated_aum'),
        ('account', '0079_create_frontend_auto_login'),
    ]

    operations = [
    ]
