# Generated by Django 4.2.3 on 2023-10-13 01:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0080_merge_20231009_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='service_interested_in',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('fx_hedging', 'FX Hedging'), ('wallet', 'Wallet'), ('payment', 'Payment & Transfer')], max_length=25, null=True),
        ),
    ]
