# Generated by Django 4.2.3 on 2023-11-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0082_cashflownote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='estimated_aum',
            field=models.CharField(choices=[('0_10m', '0-$10,000,000'), ('10m_25m', '$10,000,000 - $25,000,000'), ('25m_50m', '$25,000,000 - $50,000,000'), ('50m+', '$50,000,000+')], max_length=50, null=True),
        ),
    ]
