# Generated by Django 4.2.3 on 2023-12-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0084_alter_cashflow_created_alter_company_estimated_aum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='draftcashflow',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
    ]
