# Generated by Django 4.2.3 on 2023-12-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0079_account_strategy_parachutecashflow_parachutedata'),
        ('account', '0085_alter_cashflow_created_alter_draftcashflow_created'),
    ]

    operations = [
    ]
