# Generated by Django 4.2.3 on 2023-12-15 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0085_alter_cashflow_created_alter_draftcashflow_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 2, 34, 34, 689069, tzinfo=datetime.timezone.utc), verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='draftcashflow',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 2, 34, 34, 689069, tzinfo=datetime.timezone.utc), verbose_name='created'),
        ),
    ]
