# Generated by Django 4.2.3 on 2023-12-25 05:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0086_alter_cashflow_created_alter_draftcashflow_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='estimated_aum',
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='draftcashflow',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
    ]
