# Generated by Django 4.2.3 on 2023-12-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0086_merge_20231208_1517"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashflow",
            name="last_generated_point",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
