# Generated by Django 4.2.3 on 2023-12-15 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0086_alter_cashflow_created_alter_draftcashflow_created'),
        ('account', '0087_cashflow_last_generated_point'),
    ]

    operations = [
    ]
