# Generated by Django 4.2.3 on 2023-12-09 14:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0087_alter_cashflow_created_alter_draftcashflow_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='execution_method',
            field=models.CharField(choices=[('asynchronous', 'Asynchronous'), ('synchronous', 'Synchronous')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='service_interested_in',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('fx_hedging', 'FX Hedging'), ('wallet', 'Wallet'), ('payment', 'Payment & Transfer')], max_length=25, null=True),
        ),
    ]
