# Generated by Django 4.2.3 on 2024-01-09 18:42

from django.db import migrations

def create_system_group(app, schema_editor):
    Group = app.get_model('auth', 'Group')
    group = Group(name="system_internal")
    group.save()
class Migration(migrations.Migration):

    dependencies = [
        ('account', '0087_alter_cashflow_created_alter_draftcashflow_created'),
    ]

    operations = [
        migrations.RunPython(create_system_group)
    ]
