# Generated by Django 4.2.7 on 2024-01-22 15:54

from django.db import migrations


def update_forward_account_settings(apps, schema_editor):
    Account = apps.get_model("account", "Account")
    for account in Account.objects.filter(name__icontains="Custom-"):
        if hasattr(account,'hedge_settings'):
            account.hedge_settings.method = 'NO_HEDGE'
            account.hedge_settings.save()


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0088_auto_20240109_1842'),
    ]

    operations = [
        migrations.RunPython(update_forward_account_settings)
    ]
