# Generated by Django 4.2.10 on 2024-03-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0089_auto_20240122_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='booked_base_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='booked_cntr_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='booked_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='indicative_base_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='indicative_cntr_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='indicative_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='show_pnl_graph',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='draftcashflow',
            name='booked_base_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftcashflow',
            name='booked_cntr_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftcashflow',
            name='booked_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftcashflow',
            name='indicative_base_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftcashflow',
            name='indicative_cntr_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftcashflow',
            name='indicative_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
