# Generated by Django 4.2.3 on 2023-12-20 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0087_alter_cashflow_created_alter_draftcashflow_created'),
        ('account', '0089_parachutedata_lock_lower_limit_and_more'),
    ]

    operations = [
    ]
