# Generated by Django 4.2.7 on 2024-02-07 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0087_remove_company_estimated_aum_alter_cashflow_created_and_more'),
        ('account', '0089_auto_20240122_1554'),
    ]

    operations = [
    ]
