# Generated by Django 4.2.3 on 2023-12-27 06:12

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0089_broker_broker_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='supported_instruments',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('forward', 'Forward'), ('future', 'Future'), ('option', 'Option'), ('spot', 'Spot')], help_text='Supported instruments', max_length=26, null=True),
        ),
        migrations.CreateModel(
            name='BrokerSupportedSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.broker')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currency.fxpair')),
            ],
            options={
                'abstract': False,
                'unique_together': {('broker', 'pair')},
            },
        ),
        migrations.CreateModel(
            name='BrokerSupportedForward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.broker')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currency.fxpair')),
            ],
            options={
                'abstract': False,
                'unique_together': {('broker', 'pair')},
            },
        ),
    ]
