# Generated by Django 4.2.3 on 2024-01-04 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_auto_20240105_0032'),
        ('account', '0090_broker_supported_instruments_brokersupportedspot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokeraccount',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='brokeraccount',
            name='capabilities',
        ),
        migrations.RemoveField(
            model_name='brokeraccount',
            name='company',
        ),
        migrations.AlterUniqueTogether(
            name='brokersupportedforward',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='brokersupportedforward',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='brokersupportedforward',
            name='pair',
        ),
        migrations.AlterUniqueTogether(
            name='brokersupportedspot',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='brokersupportedspot',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='brokersupportedspot',
            name='pair',
        ),
    ]
