# Generated by Django 4.2.3 on 2024-01-11 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0091_alter_account_strategy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parachutedata",
            name="hedged_fraction",
        ),
    ]
