# Generated by Django 4.2.3 on 2024-01-04 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('margin', '0007_alter_deposit_broker_account_and_more'),
        ('hedge', '0053_alter_benchmarkrate_broker_and_more'),
        ('dataprovider', '0020_alter_dataprovider_broker'),
        ('account', '0091_remove_brokeraccount_broker_and_more'),
        ('ibkr', '0032_alter_fundingrequest_broker_account_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Broker',
        ),
        migrations.DeleteModel(
            name='BrokerAccount',
        ),
        migrations.DeleteModel(
            name='BrokerAccountCapability',
        ),
        migrations.DeleteModel(
            name='BrokerSupportedForward',
        ),
        migrations.DeleteModel(
            name='BrokerSupportedSpot',
        ),
    ]
