# Generated by Django 4.2.3 on 2024-01-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0088_auto_20240109_1842'),
        ('account', '0092_delete_broker_delete_brokeraccount_and_more'),
    ]

    operations = [
    ]
