# Generated by Django 4.2.3 on 2024-01-28 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0093_merge_20240112_1755"),
    ]

    operations = [
        migrations.CreateModel(
            name="HardLimitsAccountData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lower_limit_fraction", models.FloatField()),
                ("upper_limit_fraction", models.FloatField(null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.account",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "hard_limits_data",
                "unique_together": {("account",)},
            },
        ),
    ]
