# Generated by Django 4.2.7 on 2024-01-18 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0092_delete_broker_delete_brokeraccount_and_more'),
        ('account', '0093_merge_20240112_1755'),
    ]

    operations = [
    ]
