# Generated by Django 4.2.3 on 2024-01-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0089_auto_20240122_1554'),
        ('account', '0093_merge_20240124_0024'),
    ]

    operations = [
    ]
