# Generated by Django 4.2.7 on 2024-01-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0089_auto_20240122_1554'),
        ('account', '0094_merge_20240118_2011'),
    ]

    operations = [
    ]
