# Generated by Django 4.2.7 on 2024-01-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0094_merge_20240125_0330'),
        ('account', '0095_merge_20240124_1443'),
    ]

    operations = [
    ]
