# Generated by Django 4.2.3 on 2024-01-30 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0094_hardlimitsaccountdata"),
        ("account", "0096_merge_20240124_1910"),
    ]

    operations = []
