# Generated by Django 4.2.7 on 2024-02-19 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0098_singlecashflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlecashflow',
            name='company',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.PROTECT, related_name='cashflows', to='account.company'),
            preserve_default=False,
        ),
    ]
