# Generated by Django 4.2.7 on 2024-02-22 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0090_merge_20240207_2055'),
        ('account', '0098_parachutedata_floating_pnl_fraction'),
    ]

    operations = [
    ]
