# Generated by Django 4.2.7 on 2024-02-19 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0100_hedgingstrategy_autopilothedgingstrategy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hedgingstrategy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_strategies', to='account.company'),
        ),
    ]
