# Generated by Django 4.2.7 on 2024-02-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0101_alter_hedgingstrategy_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hedgingstrategy',
            name='company',
        ),
        migrations.RemoveField(
            model_name='hedgingstrategy',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='parachutehedgingstrategy',
            name='hedgingstrategy_ptr',
        ),
        migrations.RemoveField(
            model_name='singlecashflow',
            name='company',
        ),
        migrations.RemoveField(
            model_name='singlecashflow',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='singlecashflow',
            name='hedge_strategy',
        ),
        migrations.RemoveField(
            model_name='zerogravity',
            name='hedgingstrategy_ptr',
        ),
        migrations.DeleteModel(
            name='AutopilotHedgingStrategy',
        ),
        migrations.DeleteModel(
            name='HedgingStrategy',
        ),
        migrations.DeleteModel(
            name='ParachuteHedgingStrategy',
        ),
        migrations.DeleteModel(
            name='SingleCashFlow',
        ),
        migrations.DeleteModel(
            name='ZeroGravity',
        ),
    ]
