# Generated by Django 4.2.10 on 2024-02-24 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0099_merge_20240222_1920'),
        ('account', '0102_remove_hedgingstrategy_company_and_more'),
    ]

    operations = [
    ]
