# Generated by Django 4.2.10 on 2024-03-06 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0103_merge_20240224_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutopilotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_limit', models.FloatField(blank=True)),
                ('lower_limit', models.FloatField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
            options={
                'verbose_name': 'Autopilot Data',
                'unique_together': {('account',)},
            },
        ),
    ]
