# Generated by Django 4.2.10 on 2024-03-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0090_cashflow_booked_base_amount_and_more'),
        ('account', '0105_autopilotdata'),
    ]

    operations = [
    ]
