# Generated by Django 4.2.10 on 2024-03-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0106_merge_20240308_1439"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="estimated_aum",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0_10m", "0-$10,000,000"),
                    ("10m_100m", "$10,000,000 - $100,000,000"),
                    ("100m_1b", "$100,000,000 - $1000,000,000"),
                    ("1b+", "$1000,000,000+"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
