# Generated by Django 4.2.10 on 2024-03-19 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0107_alter_company_estimated_aum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopilotdata',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autopilot_data', to='account.account'),
        ),
        migrations.AlterField(
            model_name='parachutedata',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parachute_data', to='account.account'),
        ),
    ]
