# Generated by Django 4.2.10 on 2024-03-19 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0108_alter_autopilotdata_account_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='autopilotdata',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='parachutedata',
            unique_together=set(),
        ),
    ]
