# Generated by Django 4.2.10 on 2024-03-19 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0109_alter_autopilotdata_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopilotdata',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autopilot_data', to='account.account'),
        ),
        migrations.AlterField(
            model_name='parachutedata',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parachute_data', to='account.account'),
        ),
    ]
