# Generated by Django 4.2.11 on 2024-05-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0111_company_recipients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accounts',
        ),
    ]
