# Generated by Django 4.2.15 on 2024-09-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0113_company_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='postal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
