# Generated by Django 4.2.15 on 2024-10-14 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0030_country'),
        ('account', '0115_beneficiary_payment_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comp_currency', to='currency.currency', verbose_name='Reporting Currency'),
        ),
        migrations.AlterField(
            model_name='company',
            name='onboarded',
            field=models.BooleanField(default=False, verbose_name='Client Services Agreement Signed'),
        ),
    ]
