# Generated by Django 4.2.15 on 2024-10-24 16:41

from django.db import migrations
from django.apps.registry import Apps
from main.apps.account.models import User


GROUPS = [
    User.UserGroups.ACCOUNT_OWNER_GROUP,
    User.UserGroups.ADMIN_GROUP,
    User.UserGroups.MANAGER_GROUP
]

def add_additional_groups(apps:Apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for group in GROUPS:
        group, created = Group.objects.get_or_create(name=group.value)


def remove_additional_groups(apps:Apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=[group.value for group in GROUPS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0116_alter_company_currency_alter_company_onboarded'),
    ]

    operations = [
        migrations.RunPython(add_additional_groups, remove_additional_groups)
    ]
