#!/bin/bash

set -o errexit
set -o nounset



until timeout 10 celery -A main.celery inspect ping; do
    >&2 echo "Celery workers not available"
done

echo 'Starting flower'


exec celery \
    -A main.celery \
    -b "${CELERY_BROKER_URL}" \
    flower \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
