# Generated by Django 3.2.8 on 2022-06-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacut',
            name='cut_type',
            field=models.IntegerField(choices=[(1, 'Eod'), (2, 'Intra'), (3, 'Benchmark')]),
        ),
    ]
