# Generated by Django 3.2.8 on 2022-06-27 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
        ('marketdata', '0002_alter_datacut_cut_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('trading_date', models.DateField()),
                ('data_cut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketdata.datacut')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.fxpair')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
