# Generated by Django 3.2.8 on 2022-06-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0003_tradingcalendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingcalendar',
            name='trading_date',
        ),
        migrations.AddField(
            model_name='tradingcalendar',
            name='end_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tradingcalendar',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradingcalendar',
            name='start_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
