# Generated by Django 3.2.8 on 2022-07-20 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0004_auto_20220629_2330'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fxspoteod',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='fxspoteod',
            name='data_cut',
        ),
        migrations.RemoveField(
            model_name='fxspoteod',
            name='pair',
        ),
        migrations.AlterUniqueTogether(
            name='fxspotintra',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='fxspotintra',
            name='data_cut',
        ),
        migrations.RemoveField(
            model_name='fxspotintra',
            name='pair',
        ),
        migrations.AlterUniqueTogether(
            name='fxspotrangeeod',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='fxspotrangeeod',
            name='data_cut',
        ),
        migrations.RemoveField(
            model_name='fxspotrangeeod',
            name='pair',
        ),
        migrations.AlterUniqueTogether(
            name='fxspotrangeintra',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='fxspotrangeintra',
            name='data_cut',
        ),
        migrations.RemoveField(
            model_name='fxspotrangeintra',
            name='pair',
        ),
        migrations.DeleteModel(
            name='FxSpotBenchmark',
        ),
        migrations.DeleteModel(
            name='FxSpotEod',
        ),
        migrations.DeleteModel(
            name='FxSpotIntra',
        ),
        migrations.DeleteModel(
            name='FxSpotRangeEod',
        ),
        migrations.DeleteModel(
            name='FxSpotRangeIntra',
        ),
    ]
