# Generated by Django 3.2.8 on 2022-08-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0006_fxspotintra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FxSpotIntra',
        ),
    ]
