# Generated by Django 3.2.8 on 2022-08-11 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20220702_1908'),
        ('marketdata', '0007_delete_fxspotintra'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxSpotIntra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('rate', models.FloatField(null=True)),
                ('rate_bid', models.FloatField(null=True)),
                ('rate_ask', models.FloatField(null=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.fxpair')),
            ],
            options={
                'unique_together': {('date', 'pair')},
            },
        ),
    ]
