# Generated by Django 3.2.8 on 2022-08-14 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0008_fxspotintra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradingcalendar',
            old_name='end_datetime',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='tradingcalendar',
            old_name='start_datetime',
            new_name='start_date',
        ),
    ]
