# Generated by Django 3.2.8 on 2022-08-20 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0009_auto_20220814_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VirtualCut',
        ),
    ]
