# Generated by Django 3.2.8 on 2022-11-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0010_delete_virtualcut'),
    ]

    operations = [
        migrations.AddField(
            model_name='fxmarketconvention',
            name='is_supported',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
