# Generated by Django 3.2.8 on 2023-05-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0011_fxmarketconvention_is_supported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxestimator',
            name='type',
            field=models.IntegerField(choices=[(1, 'Ewma'), (2, 'Gas'), (3, 'Ml')], default=1),
        ),
    ]
