# Generated by Django 3.2.8 on 2023-05-17 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0012_alter_fxestimator_type'),
        ('marketdata', '0012_corpayfxforward'),
    ]

    operations = [
    ]
