# Generated by Django 3.2.8 on 2023-05-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0013_merge_20230517_2213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CorpayFxForward',
        ),
    ]
