# Generated by Django 3.2.8 on 2023-05-21 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_auto_20230323_0038'),
        ('account', '0076_alter_cashflow_status'),
        ('marketdata', '0014_delete_corpayfxforward'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpayFxForward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('tenor', models.CharField(max_length=4)),
                ('rate', models.FloatField(null=True)),
                ('rate_bid', models.FloatField(null=True)),
                ('rate_ask', models.FloatField(null=True)),
                ('fwd_points', models.FloatField(null=True)),
                ('fwd_points_bid', models.FloatField(null=True)),
                ('fwd_points_ask', models.FloatField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('data_cut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketdata.datacut')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.fxpair')),
            ],
            options={
                'abstract': False,
                'unique_together': {('data_cut', 'pair', 'tenor')},
            },
        ),
    ]
