# Generated by Django 3.2.8 on 2023-06-23 00:33

from django.db import migrations


def add_pairs_to_fx_market_convention(apps, schema_editor):
    FxMarketConvention = apps.get_model('marketdata', "FxMarketConvention")
    FxPair = apps.get_model('currency', 'FxPair')
    Currency = apps.get_model('currency', 'Currency')
    ib_supported_pairs = ['AUDUSD', 'BGNUSD', 'EURUSD', 'GBPUSD', 'KRWUSD', 'NZDUSD', 'RONUSD', 'SARUSD',
                          'USDAED', 'USDBGN', 'USDCAD', 'USDCHF', 'USDCNH', 'USDCZK', 'USDDKK', 'USDHKD',
                          'USDHUF', 'USDILD', 'USDJPY', 'USDKRW', 'USDMXN', 'USDNOK', 'USDPLN', 'USDRON',
                          'USDRUB', 'USDSAR', 'USDSEK', 'USDSGD', 'USDTRY', 'USDZAR']

    for pair in ib_supported_pairs:
        base_currency, quote_currency = pair[:3], pair[3:]
        base_currency_model = Currency.objects.filter(mnemonic=base_currency).first()
        if base_currency_model is None:
            continue
        quote_currency_model = Currency.objects.filter(mnemonic=quote_currency).first()
        if quote_currency_model is None:
            continue
        pair_model = FxPair.objects.filter(base_currency=base_currency_model,
                                           quote_currency=quote_currency_model).first()
        if pair_model is None:
            continue
        if FxMarketConvention.objects.filter(pair=pair_model).count() > 0:
            continue
        fx_market_convention = FxMarketConvention(
            pair=pair_model,
            min_lot_size=1000,
            is_supported=True
        )
        fx_market_convention.save()


class Migration(migrations.Migration):
    dependencies = [
        ('marketdata', '0015_corpayfxforward'),
    ]

    operations = [
        migrations.RunPython(add_pairs_to_fx_market_convention)
    ]
