# Generated by Django 4.2 on 2023-08-29 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_auto_20230808_2148'),
        ('account', '0078_alter_cashflow_currency_alter_draftcashflow_currency'),
        ('marketdata', '0018_corpayfxforward_tenor_days'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='corpayfxforward',
            unique_together={('data_cut', 'pair', 'tenor', 'company')},
        ),
    ]
