# Generated by Django 4.2.3 on 2023-10-07 14:52

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0019_alter_corpayfxforward_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('rate_index', models.FloatField(null=True)),
                ('rate_bid_index', models.FloatField(null=True)),
                ('rate_ask_index', models.FloatField(null=True)),
                ('data_cut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketdata.datacut')),
                ('index_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketdata.indexasset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
