# Generated by Django 4.2 on 2023-09-18 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0009_merge_20230907_1337'),
        ('marketdata', '0019_alter_corpayfxforward_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxSpotIntraIBKR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('rate', models.FloatField(null=True)),
                ('rate_bid', models.FloatField(null=True)),
                ('rate_ask', models.FloatField(null=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.fxpair')),
            ],
            options={
                'unique_together': {('date', 'pair')},
            },
        ),
    ]
