# Generated by Django 4.2 on 2023-09-17 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0027_rename_conid_futurecontract_con_id_and_more'),
        ('marketdata', '0019_alter_corpayfxforward_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureTradingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('data_cut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketdata.datacut')),
                ('future_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibkr.futurecontract')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FutureLiquidHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('data_cut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketdata.datacut')),
                ('future_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibkr.futurecontract')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
