# Generated by Django 4.2.3 on 2023-10-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0020_futuretradinghours_futureliquidhours'),
        ('marketdata', '0020_fxspotintraibkr'),
    ]

    operations = [
    ]
