# Generated by Django 4.2.3 on 2023-10-07 14:52

from django.db import migrations

def add_dxy_to_index_asset(apps, schema_editor):
    IndexAsset = apps.get_model('marketdata', "IndexAsset")
    dxy = IndexAsset(
        name = "US Dollar Index",
        symbol = "DXY"
    )
    dxy.save()

def remove_dxy_from_index_asset(apps, schema_editor):
    IndexAsset = apps.get_model('marketdata', "IndexAsset")
    IndexAsset.objects.filter(symbol="DXY").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0020_indexasset_index'),
    ]

    operations = [
        migrations.RunPython(add_dxy_to_index_asset, remove_dxy_from_index_asset)
    ]
