# Generated by Django 4.2.3 on 2023-11-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0021_auto_20231007_2152'),
        ('marketdata', '0021_merge_20231004_1039'),
    ]

    operations = [
    ]
