# Generated by Django 4.2.3 on 2023-10-27 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0010_auto_20230925_0809'),
        ('account', '0081_company_service_interested_in'),
        ('marketdata', '0021_merge_20231004_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpayFxSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('rate', models.FloatField(null=True)),
                ('rate_bid', models.FloatField(null=True)),
                ('rate_ask', models.FloatField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('data_cut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketdata.datacut')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.fxpair')),
            ],
            options={
                'unique_together': {('date', 'pair', 'company')},
            },
        ),
    ]
