# Generated by Django 4.2.3 on 2023-11-07 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0022_merge_20231101_1703'),
        ('marketdata', '0023_corpayfxspot'),
    ]

    operations = [
    ]
