# Generated by Django 4.2.3 on 2024-01-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0018_alter_currency_options_alter_fxpair_options'),
        ('marketdata', '0025_alter_corpayfxforward_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='corpayfxforward',
            unique_together={('date', 'data_cut', 'pair', 'tenor')},
        ),
        migrations.AlterUniqueTogether(
            name='corpayfxspot',
            unique_together={('date', 'data_cut', 'pair')},
        ),
    ]
