# Generated by Django 4.2.7 on 2024-01-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0026_alter_corpayfxforward_unique_together_and_more'),
        ('marketdata', '0026_auto_20231216_1655'),
    ]

    operations = [
    ]
