# Generated by Django 4.2.7 on 2024-01-25 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0027_merge_20240124_1910'),
        ('marketdata', '0027_merge_20240125_1642'),
    ]

    operations = [
    ]
