# Generated by Django 4.2.10 on 2024-03-07 14:06

from django.db import migrations, models
import django.db.models.deletion
import main.apps.oems.models.extensions


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0028_merge_20240125_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingHolidaysCodeFincal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('holiday', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TradingHolidaysInfoFincal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('center', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('info_type', models.CharField(blank=True, choices=[('bank', 'Bank'), ('se_trading', 'SE Trading'), ('se_settlement', 'SE Settlement'), ('futures_trading', 'Futures Trading'), ('other', 'Other')], max_length=50, null=True)),
                ('iso_country', models.CharField(blank=True, max_length=5, null=True)),
                ('define_1', models.TextField(blank=True, null=True)),
                ('define_2', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradingCalendarFincal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('cen_code', models.CharField(max_length=5)),
                ('market', models.CharField(max_length=255)),
                ('irregular', models.CharField(blank=True, choices=[('H', 'Holiday'), ('Y', 'Non Standard Hours'), ('N', 'Normal'), ('W', 'Weekend')], max_length=255, null=True)),
                ('irreg_sess', models.CharField(blank=True, choices=[('C', 'Closed'), ('O', 'Open'), ('T', 'Trading'), ('N', 'Normal')], max_length=255, null=True)),
                ('new_hours', models.CharField(blank=True, choices=[('Y', 'Non Standard Hours'), ('N', 'Normal')], max_length=255, null=True)),
                ('functions', models.CharField(blank=True, max_length=255, null=True)),
                ('activity', models.CharField(blank=True, max_length=255, null=True)),
                ('local_open', main.apps.oems.models.extensions.DateTimeWithoutTZField(blank=True, null=True)),
                ('local_close', main.apps.oems.models.extensions.DateTimeWithoutTZField(blank=True, null=True)),
                ('first_open', models.IntegerField(blank=True, null=True)),
                ('last_open', models.IntegerField(blank=True, null=True)),
                ('first_close', models.IntegerField(blank=True, null=True)),
                ('last_close', models.IntegerField(blank=True, null=True)),
                ('nyus_open', main.apps.oems.models.extensions.DateTimeWithoutTZField(blank=True, null=True)),
                ('nyus_close', main.apps.oems.models.extensions.DateTimeWithoutTZField(blank=True, null=True)),
                ('gmtt_open', models.DateTimeField(blank=True, null=True)),
                ('gmtt_close', models.DateTimeField(blank=True, null=True)),
                ('gmtoff_op', models.CharField(blank=True, null=True)),
                ('fmtoff_cl', models.CharField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['cen_code'], name='marketdata__cen_cod_5365fc_idx'), models.Index(fields=['gmtt_open'], name='marketdata__gmtt_op_42f98a_idx'), models.Index(fields=['gmtt_close'], name='marketdata__gmtt_cl_087ce2_idx')],
            },
        ),
        migrations.CreateModel(
            name='TradingHolidaysFincal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketdata.tradingholidaysinfofincal')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketdata.tradingholidayscodefincal')),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'code'], name='marketdata__date_623650_idx')],
                'unique_together': {('date', 'code')},
            },
        ),
    ]
