# Generated by Django 4.2.10 on 2024-03-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0029_tradingholidayscodefincal_tradingholidaysinfofincal_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tradingholidaysfincal',
            new_name='marketdata__date_f8e15e_idx',
            old_name='marketdata__date_623650_idx',
        ),
        migrations.AlterField(
            model_name='tradingholidaysfincal',
            name='code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='tradingholidaysfincal',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
