# Generated by Django 4.2.11 on 2024-05-02 00:10

from django.db import migrations, models
import main.apps.oems.backend.utils


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0030_rename_marketdata__date_623650_idx_marketdata__date_f8e15e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('instrument_type', models.CharField(blank=True, choices=[('forward', 'Forward'), ('future', 'Future'), ('base_future', 'BaseFuture'), ('continuous_future', 'ContinuousFuture'), ('cash_equity', 'CashEquity'), ('option', 'Option'), ('spot', 'Spot'), ('window_forward', 'Window Forward'), ('ndf', 'Ndf'), ('swap', 'Swap'), ('nds', 'Nds'), ('rtp', 'Realtime Payment'), ('continuous_spot', 'Continuous Spot')], help_text='instrument type', null=True)),
                ('tradable_instrument', models.BooleanField(default=False)),
                ('reference', models.JSONField(blank=True, encoder=main.apps.oems.backend.utils.DateTimeEncoder, null=True)),
                ('symbology', models.JSONField(blank=True, encoder=main.apps.oems.backend.utils.DateTimeEncoder, null=True)),
            ],
        ),
    ]
