# Generated by Django 4.2.11 on 2024-05-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0033_init_secmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='multi_leg',
            field=models.BooleanField(default=False),
        ),
    ]
