# Generated by Django 4.2.11 on 2024-05-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketdata", "0036_alter_instrument_instrument_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="fxforward",
            name="delivery_days",
            field=models.IntegerField(
                help_text="Day count from spot to delivery date for an option based on tenor.",
                null=True,
                verbose_name="Delivery Days",
            ),
        ),
        migrations.AddField(
            model_name="fxforward",
            name="expiry_days",
            field=models.IntegerField(
                help_text="Day count from valuation to expiry date for an option based on tenor.",
                null=True,
                verbose_name="Expiry Days",
            ),
        ),
        migrations.AddField(
            model_name="fxforward",
            name="interest_days",
            field=models.IntegerField(
                help_text="Day count for a forward from spot to delivery based on tenor.",
                null=True,
                verbose_name="Interest Days",
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="delivery_days",
            field=models.IntegerField(
                help_text="Day count from spot to delivery date for an option based on tenor.",
                null=True,
                verbose_name="Delivery Days",
            ),
        ),
        migrations.AddField(
            model_name="optionstrategy",
            name="delivery_days",
            field=models.IntegerField(
                help_text="Day count from spot to delivery date for an option based on tenor.",
                null=True,
                verbose_name="Delivery Days",
            ),
        ),
        migrations.AddField(
            model_name="optionstrategy",
            name="expiry_days",
            field=models.IntegerField(
                help_text="Day count from valuation to expiry date for an option based on tenor.",
                null=True,
                verbose_name="Expiry Days",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="expiry_days",
            field=models.IntegerField(
                help_text="Day count from valuation to expiry date for an option based on tenor.",
                verbose_name="Expiry Days",
            ),
        ),
    ]
