# Generated by Django 4.2.11 on 2024-05-22 13:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0025_auto_20240514"),
        ("marketdata", "0038_fxoptionstrategy_fxoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="fxoptionstrategy",
            name="acquired_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="fxoptionstrategy",
            name="pair",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="currency.fxpair",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fxoptionstrategy",
            name="storage_type",
            field=models.CharField(
                choices=[
                    ("local_storage", "Local Storage"),
                    ("sftp", "SFTP"),
                    ("gcs", "Google Cloud Storage"),
                ],
                default=1,
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
