# Generated by Django 4.2.11 on 2024-05-28 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0038_init_usd_instrument'),
        ('marketdata', '0039_fxoptionstrategy_acquired_date_fxoptionstrategy_pair_and_more'),
    ]

    operations = [
    ]
