# Generated by Django 4.2.15 on 2024-08-28 18:53

from django.db import migrations

def update_sec_master(app, schema_editor):
    Instrument = app.get_model('marketdata', 'Instrument')
    for instrument in Instrument.objects.iterator():
        if '-BROKEN' in instrument.name:
            instrument.name = instrument.name.replace('BROKEN','FWD')
            instrument.save()


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0045_auto_20240828_0854'),
    ]

    operations = [
        migrations.RunPython(update_sec_master)
    ]
