# Generated by Django 4.2.10 on 2024-03-21 06:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_webhook_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhook',
            name='uuid',
        ),
        migrations.AddField(
            model_name='webhook',
            name='webhook_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
