# Generated by Django 4.2.10 on 2024-03-22 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0110_alter_autopilotdata_account_and_more'),
        ('webhook', '0004_remove_webhook_uuid_webhook_webhook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='The name of the event.', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(help_text='The unique type of the event.', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='events',
            field=models.ManyToManyField(help_text='The events associated with this group.', to='webhook.event'),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='name',
            field=models.CharField(help_text='The name of the event group.', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='slug',
            field=models.SlugField(help_text='The slug for the event group.'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='company',
            field=models.ForeignKey(help_text='The company associated with the webhook.', on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='created_by',
            field=models.ForeignKey(help_text='The user who created the webhook.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='events',
            field=models.ManyToManyField(help_text='The events associated with this webhook.', to='webhook.event'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='groups',
            field=models.ManyToManyField(help_text='The event groups associated with this webhook.', to='webhook.eventgroup'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='url',
            field=models.URLField(help_text='The URL where the webhook will send events.'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='webhook_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier for the webhook.', unique=True),
        ),
    ]
