# Generated by Django 4.2.10 on 2024-03-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('webhook', '0005_alter_event_name_alter_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='signing_secret',
            field=models.CharField(default='CT5tRoGu00sritIMVCgXgkWEzxzPbJyrLe9Jg_xbSw4',
                                   help_text='The signing secret for the webhook.', max_length=255),
        )
    ]
