# Generated by Django 4.2.10 on 2024-03-27 16:50

from django.db import migrations
from django.utils.text import slugify


def populate_slug_for_event_group(apps, schema_editor):
    EventGroup = apps.get_model("webhook", "EventGroup")
    for group in EventGroup.objects.all():
        group.slug = slugify(group.name)
        group.save()


class Migration(migrations.Migration):
    dependencies = [
        ('webhook', '0006_webhook_signing_secret'),
    ]

    operations = [
        migrations.RunPython(populate_slug_for_event_group)
    ]
