# Generated by Django 4.2.10 on 2024-03-27 16:52

from django.db import migrations, models
import main.apps.webhook.models.webhook


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0007_auto_20240327_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='signing_secret',
            field=models.CharField(default=main.apps.webhook.models.webhook.generate_signing_secret, help_text='The signing secret for the webhook.', max_length=255),
        ),
    ]
