# Generated by Django 4.2.11 on 2024-04-24 03:57

from django.db import migrations, IntegrityError

def create_webhook_events(apps, schema_editor):
    Event = apps.get_model('webhook', 'Event')
    webhook_events = [
        {'name': 'Beneficiary Created', 'type': 'beneficiary.created'},
        {'name': 'Beneficiary Updated', 'type': 'beneficiary.updated'},
        {'name': 'Beneficiary Deleted', 'type': 'beneficiary.canceled'},
    ]
    for event in webhook_events:
        try:
            Event.objects.create(**event)
        except IntegrityError:
            continue

def create_webhook_event_groups(apps, schema_editor):
    EventGroup = apps.get_model('webhook', 'EventGroup')
    Event = apps.get_model('webhook', 'Event')
    groups = [
        {
            'name': 'Beneficiary',
            'slug': 'beneficiary',
            'events': [
                Event.objects.get(type='beneficiary.created'),
                Event.objects.get(type='beneficiary.updated'),
                Event.objects.get(type='beneficiary.canceled'),
            ]
        }
    ]
    for group in groups:
        group_obj = EventGroup.objects.create(name=group['name'], slug=group['slug'])
        all_group = EventGroup.objects.get(name='All')
        for event in group['events']:
            all_group.events.add(event)
            group_obj.events.add(event)

class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0008_alter_webhook_signing_secret'),
    ]

    operations = [
        migrations.RunPython(create_webhook_events),
        migrations.RunPython(create_webhook_event_groups),
    ]
