# Generated by Django 4.2.15 on 2024-10-11 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('webhook', '0009_auto_20240424_0357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authtoken.tokenproxy',),
        ),
    ]
