# Generated by Django 3.2.8 on 2022-06-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprovider', '0002_alter_source_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file_format',
            field=models.CharField(choices=[('csv', 'csv'), ('xml', 'xml'), ('fixml', 'fixml'), ('api', 'api'), ('html', 'html')], default='csv', max_length=10),
        ),
    ]
