# Generated by Django 3.2.8 on 2022-06-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprovider', '0004_dataprovider_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
