# Generated by Django 3.2.8 on 2022-06-08 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_brokeraccount_account_type'),
        ('dataprovider', '0005_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprovider',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.broker'),
        ),
    ]
