# Generated by Django 3.2.8 on 2022-06-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprovider', '0006_alter_dataprovider_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='data_cut_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Eod'), (2, 'Intra'), (3, 'Benchmark')], default=1),
        ),
    ]
