# Generated by Django 3.2.8 on 2023-06-19 20:46

from django.db import migrations


def remove_datacut_eod_with_hour_0(apps, schema_editor):
    DataCut = apps.get_model('marketdata', 'DataCut')
    datacut_qs = DataCut.objects.filter(
        cut_type=1,
        cut_time__hour=0
    )
    datacut_qs.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('dataprovider', '0010_auto_20230519_0621'),
    ]

    operations = [
        migrations.RunPython(remove_datacut_eod_with_hour_0)
    ]
