# Generated by Django 3.2.8 on 2023-08-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprovider', '0012_auto_20230724_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='data_type',
            field=models.CharField(choices=[('local_storage', 'Local Storage'), ('sftp', 'SFTP'), ('rest', 'REST API'), ('gcp', 'Google Cloud'), ('ibkr_tws', 'IBKR TWS'), ('ibkr_web', 'IBKR Web'), ('corpay_csv', 'Corpay CSV')], default='local_storage', max_length=255),
        ),
    ]
