# Generated by Django 3.2.8 on 2023-08-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprovider', '0012_auto_20230724_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprovider',
            name='provider_handler',
            field=models.CharField(choices=[('reuters', 'Reuters'), ('ice', 'ICE'), ('corpay', 'CorPay'), ('ibkr', 'IBKR'), ('ndl', 'Nasdaq Data Link'), ('country', 'Country ISO Codes'), ('spi', 'Social Progress Index')], default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='file_format',
            field=models.CharField(choices=[('csv', 'csv'), ('xml', 'xml'), ('fixml', 'fixml'), ('json', 'json'), ('api', 'api'), ('html', 'html'), ('txt', 'txt'), ('xlsx', 'xlsx')], default='csv', max_length=10),
        ),
    ]
