# Generated by Django 4.2.3 on 2023-09-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataprovider', '0013_alter_provider_handler'),
        ('dataprovider', '0015_alter_source_data_type'),
    ]

    operations = [
    ]
