# Generated by Django 4.2.3 on 2023-10-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprovider', '0016_merge_20230907_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file_format',
            field=models.CharField(choices=[('csv', 'csv'), ('xml', 'xml'), ('fixml', 'fixml'), ('json', 'json'), ('api', 'api'), ('html', 'html'), ('txt', 'txt'), ('xlsx', 'xlsx'), ('model', 'model')], default='csv', max_length=10),
        ),
        migrations.AlterField(
            model_name='source',
            name='data_type',
            field=models.CharField(choices=[('local_storage', 'Local Storage'), ('sftp', 'SFTP'), ('rest', 'REST API'), ('gcp', 'Google Cloud'), ('ibkr_tws', 'IBKR TWS'), ('ibkr_web', 'IBKR Web'), ('corpay', 'CorPay API'), ('model', 'Model')], default='local_storage', max_length=255),
        ),
    ]
