# Generated by Django 4.2.3 on 2024-01-02 13:58

import collections
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprovider', '0017_alter_profile_file_format_alter_source_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='options',
            field=models.JSONField(default=collections.defaultdict, help_text='Profiles options'),
        ),
    ]
