# Generated by Django 4.2.3 on 2024-01-02 13:59

import collections
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprovider', '0018_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='options',
            field=models.JSONField(default=collections.defaultdict, help_text='Profile options'),
        ),
    ]
