# Generated by Django 4.2.3 on 2024-01-04 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_auto_20240105_0032'),
        ('dataprovider', '0019_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprovider',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='broker.broker'),
        ),
    ]
