# Generated by Django 4.2.7 on 2024-01-16 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataprovider', '0019_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileParallelOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('manual', 'Manual'), ('dynamic', 'Dynamic')], default='manual')),
                ('provider', models.CharField(blank=True, choices=[('fxpair', 'FX Pair'), ('company', 'Company')], default=None, null=True)),
                ('instrument', models.CharField(choices=[('spot', 'Spot'), ('forward', 'Forward')])),
                ('ids', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprovider.profile')),
            ],
        ),
    ]