# Generated by Django 4.2.7 on 2024-01-17 00:00

import collections
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataprovider', '0020_profileparalleloption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='options',
            field=models.JSONField(blank=True, default=collections.defaultdict, help_text='Profile options', null=True),
        ),
        migrations.AlterField(
            model_name='profileparalleloption',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dataprovider.profile'),
        ),
    ]
