# Generated by Django 4.2.7 on 2024-01-18 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataprovider', '0020_alter_dataprovider_broker'),
        ('dataprovider', '0021_alter_profile_options_and_more'),
    ]

    operations = [
    ]
