# Generated by Django 4.2.3 on 2024-01-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataprovider', '0020_alter_dataprovider_broker'),
        ('dataprovider', '0021_alter_profile_options_and_more'),
    ]

    operations = [
    ]
