# Generated by Django 4.2.7 on 2024-01-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataprovider', '0022_alter_profileparalleloption_instrument'),
        ('dataprovider', '0023_merge_20240124_1910'),
    ]

    operations = [
    ]
