# Generated by Django 4.2.7 on 2024-02-21 15:31

from django.db import migrations


def add_currencies(apps, schema_editor):
    Currency = apps.get_model('currency', 'Currency')
    obj, created = Currency.objects.get_or_create(
        mnemonic='SAF',
        name='Saudi riyal',
        category='other',
        symbol_location='prefix',
    )


def add_fx_pair(apps, schema_editor):
    Currency = apps.get_model('currency', 'Currency')
    FxPair = apps.get_model('currency', 'FxPair')

    usd = Currency.objects.get(mnemonic='USD')
    saf = Currency.objects.get(mnemonic='SAF')

    obj, created = FxPair.objects.get_or_create(
        base_currency=usd,
        quote_currency=saf
    )
    obj, created = FxPair.objects.get_or_create(
        base_currency=saf,
        quote_currency=usd
    )


class Migration(migrations.Migration):
    dependencies = [
        ("dataprovider", "0024_merge_20240126_1428"),
    ]

    operations = [

        migrations.RunPython(add_currencies, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(add_fx_pair, reverse_code=migrations.RunPython.noop),
    ]
