# Generated by Django 4.2.10 on 2024-03-06 04:00
import datetime

from django.db import migrations


def update_cut_type(apps, schema_editor):
    DataCut = apps.get_model('marketdata', 'DataCut')

    time_22 = datetime.time(22, 0, 0, 0)
    time_16 = datetime.time(16, 0, 0, 0)

    # Update for cut_time 22:00 to EOD
    DataCut.objects.exclude(cut_type=1).filter(cut_time__time=time_22).update(cut_type=1)
    # Update for cut_time 16:00 to BENCHMARK
    DataCut.objects.exclude(cut_type=3).filter(cut_time__time=time_16).update(cut_type=3)


class Migration(migrations.Migration):
    dependencies = [
        ("dataprovider", "0026_added_eursaf_to_fxpair"),
    ]

    operations = [
        migrations.RunPython(update_cut_type),
    ]
