# Generated by Django 4.2.10 on 2024-03-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprovider', '0027_auto_20240306_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprovider',
            name='provider_handler',
            field=models.CharField(choices=[('reuters', 'Reuters'), ('ice', 'ICE'), ('corpay', 'CorPay'), ('ibkr', 'IBKR'), ('ndl', 'Nasdaq Data Link'), ('country', 'Country ISO Codes'), ('spi', 'Social Progress Index'), ('fin_cal', 'Fin Cal')], default=None, max_length=255),
        ),
    ]
