# Generated by Django 4.2.10 on 2024-03-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataprovider', '0029_auto_20240320_1545'),
        ('dataprovider', '0029_fix_fxspotintra_date'),
    ]

    operations = [
    ]
