# Generated by Django 4.2.10 on 2024-03-26 05:12

from datetime import datetime

from django.db import migrations


def update_cut_type_to_eod(apps, schema_editor):
    DataCut = apps.get_model('marketdata', 'DataCut')
    cut_times = [
        "2024-03-11 21:00:00.000000 +00:00",
        "2024-03-18 21:00:00.000000 +00:00",
        "2024-03-08 20:00:00.000000 +00:00"
    ]
    for cut_time_str in cut_times:
        cut_time = datetime.strptime(cut_time_str, "%Y-%m-%d %H:%M:%S.%f %z")
        DataCut.objects.filter(cut_time=cut_time).update(cut_type=1)


class Migration(migrations.Migration):
    dependencies = [
        ("dataprovider", "0030_merge_20240325_1607"),
    ]

    operations = [
        migrations.RunPython(update_cut_type_to_eod),
    ]
