# Generated by Django 4.2.11 on 2024-04-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprovider', '0031_fix_wrong_cut_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='extract_for_profile_ids',
            field=models.CharField(help_text='Profile ids related to the downloaded archived file', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='file_format',
            field=models.CharField(choices=[('csv', 'csv'), ('xml', 'xml'), ('fixml', 'fixml'), ('json', 'json'), ('api', 'api'), ('html', 'html'), ('txt', 'txt'), ('xlsx', 'xlsx'), ('model', 'model'), ('zip', 'zip'), ('tar.gz', 'tar.gz')], default='csv', max_length=10),
        ),
    ]
