# Generated by Django 4.2.11 on 2024-05-09 14:55

from django.db import migrations
from django.apps.registry import Apps
from main.apps.dataprovider.models import Source as Src


def modify_ibkr_tws_profiles(apps:Apps, reverse:bool = False):
    Source = apps.get_model('dataprovider', 'Source')
    Profile = apps.get_model('dataprovider', 'Profile')

    try:
        ibkr_tws_profiles = Profile.objects.filter(source__data_type=Src.DataType.IBKR_TWS.value)
        for ibkr_tws_profile in ibkr_tws_profiles:
            ibkr_tws_profile.enabled = reverse
            ibkr_tws_profile.save()
    except Exception:
        pass

def disable_ibkr_tws_profiles(apps:Apps, schema_editor):
    modify_ibkr_tws_profiles(apps=apps)

def enable_ibkr_tws_profiles(apps:Apps, schema_editor):
    modify_ibkr_tws_profiles(apps=apps, reverse=True)


class Migration(migrations.Migration):

    dependencies = [
        ('dataprovider', '0033_add_and_modify_fincal_importer'),
    ]

    operations = [
        migrations.RunPython(disable_ibkr_tws_profiles, enable_ibkr_tws_profiles)
    ]
