# Generated by Django 4.2.11 on 2024-05-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataprovider", "0035_add_backfill_marketdata_periodic_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="extract_for_profile_ids",
            field=models.CharField(
                blank=True,
                help_text="Profile ids related to the downloaded archived file",
                null=True,
            ),
        ),
    ]
