# Generated by Django 4.2.11 on 2024-06-06 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dataprovider", "0037_collectorconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("writer", models.CharField(blank=True, max_length=1024, null=True)),
                ("publisher", models.CharField(blank=True, max_length=1024, null=True)),
                ("cache", models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.RemoveField(model_name="collectorconfig", name="write_to_bq",),
        migrations.AddField(
            model_name="collectorconfig",
            name="storage_config",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dataprovider.storageconfig",
            ),
            preserve_default=False,
        ),
    ]
