# Generated by Django 4.2.11 on 2024-06-25 13:49

import logging

from django.db import migrations


def update_file_status(apps, schema_editor):
    Profile = apps.get_model('dataprovider', 'Profile')
    File = apps.get_model('dataprovider', 'File')
    logger = logging.getLogger(__name__)

    # Lists of sources and profile names to loop through
    sources_names = ["ICE SFTP", "ICE GCP"]
    profile_names = ["ICE Option New", "ICE Option Strategy New"]

    # Loop through each source and profile name
    for source_name in sources_names:
        for profile_name in profile_names:
            try:
                profile = Profile.objects.get(name=profile_name, source__name=source_name)
                files = profile.file_set.all()

                for file_instance in files:
                    file_instance.status = 1
                    file_instance.save()
            except Profile.DoesNotExist:
                logger.info(f"No profile found for {profile_name} with source {source_name}")
            except Exception as e:
                logger.info(f"An error occurred: {e}")


def delete_fxoption_instances(apps, schema_editor):
    FxOption = apps.get_model('marketdata', 'FxOption')
    FxOptionStrategy = apps.get_model('marketdata', 'FxOptionStrategy')
    logger = logging.getLogger(__name__)

    # Delete all instances of FxOption
    try:
        FxOption.objects.all().delete()
        logger.info("All FxOption instances have been deleted.")
    except Exception as e:
        logger.error(f"An error occurred while deleting FxOption instances: {e}")

    # Delete all instances of FxOptionStrategy
    try:
        FxOptionStrategy.objects.all().delete()
        logger.info("All FxOptionStrategy instances have been deleted.")
    except Exception as e:
        logger.error(f"An error occurred while deleting FxOptionStrategy instances: {e}")


class Migration(migrations.Migration):
    dependencies = [
        ("dataprovider", "0042_populate_storage_and_collector_config"),
    ]

    operations = [
        migrations.RunPython(update_file_status),
        migrations.RunPython(delete_fxoption_instances),

    ]
