# Generated by Django 3.2.8 on 2022-05-06 00:47

from django.db import migrations, models
import django.db.models.deletion
import hdlib.Core.Currency


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, null=True)),
                ('mnemonic', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('unit', models.FloatField(blank=True, null=True)),
                ('numeric_code', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'currencies',
            },
            bases=(models.Model, hdlib.Core.Currency.Currency),
        ),
        migrations.CreateModel(
            name='FxPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_currency', to='currency.currency')),
                ('quote_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_currency', to='currency.currency')),
            ],
            options={
                'verbose_name_plural': 'FX Pairs',
                'unique_together': {('base_currency', 'quote_currency')},
            },
        ),
    ]
