# Generated by Django 3.2.8 on 2022-07-02 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxpair',
            name='base_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_currency', to='currency.currency'),
        ),
        migrations.AlterField(
            model_name='fxpair',
            name='quote_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_currency', to='currency.currency'),
        ),
    ]
