# Generated by Django 3.2.8 on 2022-11-09 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20220702_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='image_banner',
            field=models.ImageField(blank=True, null=True, upload_to='currency/banner/'),
        ),
        migrations.AddField(
            model_name='currency',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='currency/thumbnail/'),
        ),
        migrations.CreateModel(
            name='StabilityIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('category', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='currency.currency')),
            ],
            options={
                'verbose_name_plural': 'stability indexes',
            },
        ),
    ]
