# Generated by Django 3.2.8 on 2023-02-28 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_auto_20221109_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stabilityindex',
            name='category',
        ),
        migrations.AddField(
            model_name='stabilityindex',
            name='parent_index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.stabilityindex'),
        ),
    ]
