# Generated by Django 3.2.8 on 2023-03-20 21:49

from django.db import migrations

from main.apps.currency.scripts.create_currencies import create_fx_pairs


def add_fxpairs(apps, schema_editor):
    """
    Adds a set of Fx pairs, and currencies to support them, to the DB.

    See https://docs.djangoproject.com/en/4.1/ref/migration-operations/ for information on RunPython.
    """
    fxpairs = ["AUDUSD", "EURUSD", "USDCAD", "USDMXN", "USDCNY", "USDCNH", "USDHKD", "USDJPY", "GBPUSD", "USDKRW",
               "USDSGD", "USDILS", "USDBRL", "USDBRR", "USDTHB", "USDTHO", "USDIDR", "USDIDF", "USDINR", "USDINF",
               "USDCHF", "USDCZK", "USDDKK", "USDNOK", "USDHUF", "USDPLN", "USDSEK", "USDZAR", "USDKES", "USDKEF",
               "USDPHP", "USDPHF", "USDTWD", "USDTWF", "NZDUSD", "USDTRF", "USDTRY", "USDSAR", "USDMYR", "USDMYF",
               "USDAED", "USDAEF", "USDKRF"]
    create_fx_pairs(fxpairs=fxpairs)


class Migration(migrations.Migration):
    dependencies = [
        ('currency', '0004_auto_20230228_0256'),
        ('marketdata', '0011_fxmarketconvention_is_supported')
    ]

    operations = [
        migrations.RunPython(add_fxpairs)
    ]
