# Generated by Django 3.2.8 on 2023-03-23 00:38

from django.db import migrations

from main.apps.currency.scripts.create_currencies import create_fx_pairs


def add_fxpairs(apps, schema_editor):
    """
    Adds a set of Fx pairs, and currencies to support them, to the DB.

    See https://docs.djangoproject.com/en/4.1/ref/migration-operations/ for information on RunPython.
    """
    fxpairs = ["AUDUSD", "EURUSD", "USDCAD", "USDMXN", "USDCNY", "USDCNH", "USDHKD", "USDJPY", "GBPUSD", "USDKRW",
               "USDSGD", "USDILS", "USDBRL", "USDBRR", "USDTHB", "USDTHO", "USDIDR", "USDIDF", "USDINR", "USDINF",
               "USDCHF", "USDCZK", "USDDKK", "USDNOK", "USDHUF", "USDPLN", "USDSEK", "USDZAR", "USDKES", "USDKEF",
               "USDPHP", "USDPHF", "USDTWD", "USDTWF", "NZDUSD", "USDTRF", "USDTRY", "USDSAR", "USDMYR", "USDMYF",
               "USDAED", "USDAEF", "USDKRF"]
    create_fx_pairs(fxpairs=fxpairs, add_reverse_pairs=True)


# This migration fixes the fact that in the last migration, we only added the forwards pairs, and we need to add the
# reverse pairs. I.e., for every X/Y we added, we also need Y/X. I've change the create_fx_pairs script so it can
# add the reverse pair too.
class Migration(migrations.Migration):
    dependencies = [
        ('currency', '0005_auto_20230320_2149'),
    ]

    operations = [
        migrations.RunPython(add_fxpairs)
    ]
