# Generated by Django 3.2.8 on 2023-08-08 21:48

from django.db import migrations
from main.apps.currency.scripts.create_currencies import create_currency


def create_currencies(apps, schema_editor):
    currencies = [
        ('VND', 'Vietnamese Dong', '₫'),
        ('GHS', 'Ghanaian Cedi', 'GH₵'),
        ('BGN', 'Bulgarian Lev', 'лв'),
        ('BHD', 'Bahraini Dinar', '.د.ب'),
        ('BWP', 'Botswana Pula', 'P'),
        ('JOD', 'Jordanian Dinar', 'د.ا'),
        ('KWD', 'Kuwaiti Dinar', 'د.ك'),
        ('LSL', 'Basotho Loti (Lesotho)', 'L'),
        ('OMR', 'Omani Rial', 'ر.ع.'),
        ('QAR', 'Qatari Riyal', 'ر.ق'),
        ('RON', 'Romanian Leu', 'lei'),
        ('TND', 'New Taiwan Dollar', 'NT$'),
        ('UGX', 'Ugandan Shilling', 'USh'),
        ('CLP', 'Chilean Peso', '$'),
        ('COP', 'Colombian Peso', '$'),
        ('MAD', 'Moroccan Dirham', 'د.م.'),
        ('ZMW', 'Zambian Kwacha', 'ZK'),
    ]
    for currency in currencies:
        create_currency(mnemonic=currency[0], name=currency[1], symbol=currency[2])


class Migration(migrations.Migration):
    dependencies = [
        ('currency', '0006_auto_20230323_0038'),
        ('corpay', '0016_currencydefinition'),
    ]

    operations = [
        migrations.RunPython(create_currencies)
    ]
