# Generated by Django 3.2.8 on 2023-05-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_auto_20230323_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='numeric_code',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
