# Generated by Django 3.2.8 on 2023-08-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_alter_currency_numeric_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stabilityindex',
            name='average_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stabilityindex',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
