# Generated by Django 4.2.3 on 2023-09-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_auto_20230808_2148'),
        ('currency', '0008_add_fields_to_stabilityindex'),
    ]

    operations = [
    ]
