# Generated by Django 4.2.3 on 2023-10-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0010_auto_20230925_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='category',
            field=models.TextField(choices=[('p10', 'P10'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
