# Generated by Django 4.2.3 on 2023-10-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0011_currency_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='category',
            field=models.TextField(choices=[('p10', 'P10'), ('other', 'Other'), ('all', 'All')], max_length=10, null=True),
        ),
    ]
