# Generated by Django 4.2.3 on 2023-11-06 22:29

from django.db import migrations

from main.apps.currency.models.currency import Currency

def set_currency_category(apps, schema_editor):
    p10 = ['CAD', 'CNH', 'CNY', 'EUR', 'GBP', 'INR', 'JPY', 'KRW',
           'MXN', 'TWD', 'USD', 'VND']

    CurrencyModel = apps.get_model('currency', 'Currency')
    for currency in CurrencyModel.objects.all():
        if currency.mnemonic in p10:
            currency.category = Currency.CurrencyCategory.P10
        else:
            currency.category = Currency.CurrencyCategory.OTHER

        currency.save()

class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0012_alter_currency_category'),
    ]

    operations = [
        migrations.RunPython(set_currency_category)
    ]
