# Generated by Django 4.2.3 on 2023-12-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0013_auto_20231106_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='symbol_location',
            field=models.CharField(default='prefix', max_length=6),
        ),
    ]
