# Generated by Django 4.2.3 on 2023-12-05 20:00

from django.db import migrations


def update_currencies(app, schema_editor):
    currencies_data = {
        "KES": {
            "name": "Kenyan Shilling",
            "symbol": "=",
            "mnemonic": "KES",
            "numeric_code": 404,
            "symbol_location": "suffix"
        },
        "MYR": {
            "name": "Malaysian Ringgit",
            "symbol": "RM",
            "mnemonic": "MYR",
            "numeric_code": 458
        },
        "PHP": {
            "name": "Philippine Peso",
            "symbol": "₱",
            "mnemonic": "PHP",
            "numeric_code": 608
        },
        "TWD": {
            "name": "Taiwan New Dollar",
            "symbol": "圓",
            "mnemonic": "TWD",
            "numeric_code": 901
        },
        "COP": {
            "name": "Colombian Peso",
            "symbol": "$",
            "mnemonic": "COP",
            "numeric_code": 170
        },
        "CLP": {
            "name": "Chilean Peso",
            "symbol": "$",
            "mnemonic": "CLP",
            "numeric_code": 152
        },
        "MAD": {
            "name": "Moroccan Dirham",
            "symbol": "DH",
            "mnemonic": "MAD",
            "numeric_code": 504
        },
        "KWD": {
            "name": "Kuwaiti Dinar",
            "symbol": "د.ك",
            "mnemonic": "KWD",
            "numeric_code": 414
        },
        "VND": {
            "name": "Vietnamese Dong",
            "symbol": "₫",
            "mnemonic": "VND",
            "numeric_code": 704
        },
        "RUB": {
            "name": "Russian Ruble",
            "symbol": "₽",
            "mnemonic": "RUB",
            "numeric_code": 643
        },
        "RON": {
            "name": "Romanian Leu",
            "symbol": "lei",
            "mnemonic": "RON",
            "numeric_code": 946
        },
        "BGN": {
            "name": "Bulgarian lev",
            "symbol": "лв",
            "mnemonic": "BGN",
            "numeric_code": 975
        },
        "PEN": {
            "name": "Peruvian Sol",
            "symbol": "S",
            "mnemonic": "PEN",
            "numeric_code": 604
        }
    }
    Currency = app.get_model('currency', 'Currency')
    for mnemonic, currency_data in currencies_data.items():
        currency, created = Currency.objects.get_or_create(mnemonic=mnemonic)
        currency.name = currency_data['name']
        currency.symbol = currency_data['symbol']
        currency.numeric_code = currency_data['numeric_code']
        currency.save()


class Migration(migrations.Migration):
    dependencies = [
        ('currency', '0014_currency_symbol_location'),
    ]

    operations = [
        migrations.RunPython(update_currencies)
    ]
