# Generated by Django 4.2.3 on 2023-12-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0015_auto_20231205_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='symbol_location',
            field=models.CharField(choices=[('prefix', 'Prefix'), ('suffix', 'Suffix')], default='prefix', max_length=6),
        ),
    ]
