# Generated by Django 4.2.3 on 2023-12-07 16:53

from django.db import migrations

import logging

logger = logging.getLogger(__name__)


def create_pairs_from_currencies(app, schema_editor):
    Currency = app.get_model('currency', 'Currency')
    FxPair = app.get_model('currency', 'FxPair')

    currencies = Currency.objects.all()

    pairs_to_create = []

    for base_currency in currencies:
        for quote_currency in currencies:
            if base_currency == quote_currency:
                continue
            if not FxPair.objects.filter(base_currency=base_currency, quote_currency=quote_currency).exists():
                logger.debug(f"Pair missing {base_currency.mnemonic}/{quote_currency.mnemonic}, creating new pair!")
                pair = FxPair(
                    base_currency=base_currency,
                    quote_currency=quote_currency
                )
                pairs_to_create.append(pair)
    FxPair.objects.bulk_create(pairs_to_create)


class Migration(migrations.Migration):
    dependencies = [
        ('currency', '0016_alter_currency_symbol_location'),
    ]

    operations = [
        migrations.RunPython(create_pairs_from_currencies)
    ]
