# Generated by Django 4.2.3 on 2023-12-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0017_auto_20231207_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['mnemonic'], 'verbose_name_plural': 'currencies'},
        ),
        migrations.AlterModelOptions(
            name='fxpair',
            options={'ordering': ['base_currency__mnemonic', 'quote_currency__mnemonic'], 'verbose_name_plural': 'FX Pairs'},
        ),
    ]
