# Generated by Django 4.2.10 on 2024-03-11 07:40

from django.db import migrations


def add_same_currency_pairs(apps, schema_editor):
    CurrencyDefinition = apps.get_model('corpay', 'CurrencyDefinition')
    FxPair = apps.get_model('currency', 'FxPair')
    Currency = apps.get_model('currency', 'Currency')

    usd = Currency.objects.get(mnemonic='USD')
    currency_definitions = CurrencyDefinition.objects.exclude(currency=usd).all()

    for currency_definition in currency_definitions:
        pair = FxPair.objects.update_or_create(
            base_currency=currency_definition.currency,
            quote_currency=currency_definition.currency
        )

def remove_same_currency_pairs(apps, schema_editor):
    CurrencyDefinition = apps.get_model('corpay', 'CurrencyDefinition')
    FxPair = apps.get_model('currency', 'FxPair')
    Currency = apps.get_model('currency', 'Currency')

    usd = Currency.objects.get(mnemonic='USD')
    currency_definitions = CurrencyDefinition.objects.exclude(currency=usd).all()

    for currency_definition in currency_definitions:
        pair = FxPair.objects.get(
            base_currency=currency_definition.currency,
            quote_currency=currency_definition.currency
        )
        if pair:
            pair.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0019_deliverytime'),
    ]

    operations = [
        migrations.RunPython(add_same_currency_pairs, remove_same_currency_pairs),
    ]
