# Generated by Django 4.2.10 on 2024-03-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0020_auto_20240311_1851'),
        ('currency', '0020_populate_same_currency_pair'),
    ]

    operations = [
    ]
