# Generated by Django 4.2.10 on 2024-03-11 18:51

from django.db import migrations

import logging

logger = logging.getLogger(__name__)


def update_currencies(app, schema_editor):
    currencies_data = {
        "TZS": {
            "name": "Tanzanian shilling",
            "symbol": "TSh",
            "mnemonic": "TZS",
            "numeric_code": 834,
        },
        "XOF": {
            "name": "West African CFA franc",
            "symbol": "F.CFA",
            "mnemonic": "XOF",
            "numeric_code": 952,
        },
        "XAF": {
            "name": "Central African CFA franc",
            "symbol": "F.CFA",
            "mnemonic": "XAF",
            "numeric_code": 950,
        },
        "MWK": {
            "name": "Malawian kwacha",
            "symbol": "MK",
            "mnemonic": "MWK",
            "numeric_code": 454,
        },
    }
    Currency = app.get_model('currency', 'Currency')
    for mnemonic, currency_data in currencies_data.items():
        currency, created = Currency.objects.get_or_create(mnemonic=mnemonic)
        currency.name = currency_data['name']
        currency.symbol = currency_data['symbol']
        currency.numeric_code = currency_data['numeric_code']
        currency.save()


def create_pairs_from_currencies(app, schema_editor):
    Currency = app.get_model('currency', 'Currency')
    FxPair = app.get_model('currency', 'FxPair')

    base_currencies = Currency.objects.all()
    currencies = Currency.objects.all()

    pairs_to_create = []

    VALID = ('USD','EUR','JPY','GBP','CAD')

    for base_currency in base_currencies:
        for quote_currency in currencies:
            if base_currency.mnemonic not in VALID and quote_currency.mnemonic not in VALID: continue
            if not FxPair.objects.filter(base_currency=base_currency, quote_currency=quote_currency).exists():
                logger.debug(f"Pair missing {base_currency.mnemonic}/{quote_currency.mnemonic}, creating new pair!")
                pair = FxPair(
                    base_currency=base_currency,
                    quote_currency=quote_currency
                )
                pairs_to_create.append(pair)
    if pairs_to_create:
        FxPair.objects.bulk_create(pairs_to_create)


class Migration(migrations.Migration):
    dependencies = [
        ('currency', '0024_auto_20240501_1234'),
    ]

    operations = [
        migrations.RunPython(update_currencies),
        migrations.RunPython(create_pairs_from_currencies)
    ]
