# Generated by Django 4.2.11 on 2024-06-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0025_auto_20240514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
