# Generated by Django 4.2.15 on 2024-08-23 23:59

from django.db import migrations


def add_etb_currency(apps, schema_editor):
    currencies_data = {
        "ETB": {
            "name": "Ethiopian birr",
            "symbol": "Br",
            "mnemonic": "ETB",
            "numeric_code": 230
        }
    }
    Currency = apps.get_model("currency", "Currency")
    for mnemonic, currency_data in currencies_data.items():
        currency, created = Currency.objects.get_or_create(
            mnemonic=mnemonic,
            defaults={
                "name": currency_data["name"],
                "symbol": currency_data["symbol"],
                "mnemonic": currency_data["mnemonic"],
                "numeric_code": currency_data["numeric_code"]
            }
        )


class Migration(migrations.Migration):
    dependencies = [
        ('currency', '0027_convert_ccys'),
    ]

    operations = [
        migrations.RunPython(add_etb_currency)
    ]
