# Generated by Django 4.2.15 on 2024-08-25 06:46
import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def create_pairs_from_currencies(app, schema_editor):
    Currency = app.get_model('currency', 'Currency')
    FxPair = app.get_model('currency', 'FxPair')

    base_currencies = Currency.objects.all()
    currencies = Currency.objects.all()

    pairs_to_create = []

    for base_currency in base_currencies:
        for quote_currency in currencies:
            if not FxPair.objects.filter(base_currency=base_currency, quote_currency=quote_currency).exists():
                logger.debug(f"Pair missing {base_currency.mnemonic}/{quote_currency.mnemonic}, creating new pair!")
                pair = FxPair(
                    base_currency=base_currency,
                    quote_currency=quote_currency
                )
                pairs_to_create.append(pair)
    FxPair.objects.bulk_create(pairs_to_create)


class Migration(migrations.Migration):
    dependencies = [
        ('currency', '0028_auto_20240823_2359'),
    ]

    operations = [
        migrations.RunPython(create_pairs_from_currencies)
    ]
