# Generated by Django 4.2.15 on 2024-11-07 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0031_add_sierra_leon_and_rwandan_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverytime',
            options={'verbose_name': 'Bank Country Session', 'verbose_name_plural': 'Bank Country Sessions'},
        ),
        migrations.AddField(
            model_name='deliverytime',
            name='banking_close_utc',
            field=models.TimeField(help_text='Bank session open time in UTC', null=True),
        ),
        migrations.AddField(
            model_name='deliverytime',
            name='banking_open_utc',
            field=models.TimeField(help_text='Bank session open time in UTC', null=True),
        ),
        migrations.AlterField(
            model_name='deliverytime',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Bank Country'),
        ),
        migrations.AlterField(
            model_name='deliverytime',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency', verbose_name='Default Currency'),
        ),
        migrations.AlterField(
            model_name='deliverytime',
            name='deadline',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='deliverytime',
            name='delivery_method',
            field=models.CharField(choices=[('W', 'Wire'), ('E', 'iACH'), ('C', 'FXBalance')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliverytime',
            name='delivery_sla',
            field=models.IntegerField(null=True),
        ),
    ]
