# Generated by Django 3.2.8 on 2022-10-23 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0002_auto_20220702_1908'),
        ('account', '0053_auto_20221019_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='CnyExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staging', models.BooleanField(default=False)),
                ('default_algo', models.CharField(default='LIQUID_TWAP1', max_length=255)),
                ('use_triggers', models.BooleanField(default=True)),
                ('calendar_code', models.CharField(default='STANDARD', max_length=255)),
                ('dest', models.CharField(default='INTERNAL_EMS', max_length=255)),
                ('sub_dest', models.CharField(default='IBKR_FIX', max_length=255)),
                ('trader', models.CharField(default='Auto', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('order_length', models.IntegerField(default=15)),
                ('order_size_limit', models.FloatField(default=5000000.0)),
                ('max_daily_tickets', models.IntegerField(default=100)),
                ('broker_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.brokeraccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.fxpair')),
            ],
            options={
                'db_table': 'cny_execution',
                'unique_together': {('company', 'market')},
            },
        ),
    ]
