# Generated by Django 3.2.8 on 2022-10-29 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_auto_20221019_2204'),
        ('currency', '0002_auto_20220702_1908'),
        ('oems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cnyexecution',
            old_name='market',
            new_name='fxpair',
        ),
        migrations.AlterUniqueTogether(
            name='cnyexecution',
            unique_together={('company', 'fxpair')},
        ),
    ]
