# Generated by Django 3.2.8 on 2022-10-30 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0002_auto_20221029_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cnyexecution',
            name='broker_account',
        ),
    ]
