# Generated by Django 3.2.8 on 2022-11-02 19:46

from django.db import migrations

from main.apps.account.models import Company
from main.apps.currency.models import FxPair
from main.apps.oems.models import CnyExecution


def populate_ccny_exec(apps, schema_editor):
    fx_pairs = list(FxPair.objects.all())
    for company in Company.objects.all():
        for fxpair in fx_pairs:
            CnyExecution.objects.create(
                company=company,
                fxpair=fxpair,
            )


class Migration(migrations.Migration):
    dependencies = [
        ('oems', '0003_remove_cnyexecution_broker_account'),
    ]

    operations = [
        migrations.RunPython(populate_ccny_exec)
    ]
