# Generated by Django 4.2.3 on 2023-09-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0004_populate_ccny_exec'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnyexecution',
            name='fut_base',
            field=models.CharField(default='', max_length=5),
        ),
    ]
