# Generated by Django 4.2.3 on 2024-01-24 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currency', '0019_deliverytime'),
        ('account', '0092_delete_broker_delete_brokeraccount_and_more'),
        ('broker', '0002_auto_20240105_0032'),
        ('oems', '0005_cnyexecution_fut_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('amount', models.FloatField()),
                ('instrument', models.CharField(choices=[('forward', 'Forward'), ('future', 'Future'), ('option', 'Option'), ('spot', 'Spot')], max_length=100)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('failed', 'Failed'), ('in_progress', 'In Progress'), ('new', 'New'), ('partial_filled', 'Partial Filled')], default='new', max_length=50)),
                ('order_configs', models.JSONField()),
                ('broker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_broker', to='broker.broker')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_company', to='account.company')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('event', models.CharField(choices=[('quote_created', 'Quote Created'), ('get_wait_condition', 'Get Wait Condition'), ('store_wait_condition', 'Store Wait Condition'), ('confirm_execution', 'Confirm Execution'), ('convert_quote_to_order', 'Convert Quote to Order'), ('assign_order_to_quote', 'Assign Order to quote')])),
                ('object_id', models.IntegerField(null=True)),
                ('object_class', models.CharField(max_length=255, null=True)),
                ('data', models.TextField(null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_company', to='account.company')),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quote_order', to='oems.order')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_pair', to='currency.fxpair')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quote_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WaitCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('expected_saving', models.FloatField(null=True)),
                ('expected_saving_percentage', models.FloatField(null=True)),
                ('lower_bound', models.FloatField(null=True)),
                ('min_lower', models.FloatField(null=True)),
                ('rate_start', models.FloatField(null=True)),
                ('regime', models.IntegerField(null=True)),
                ('upper_bound', models.FloatField(null=True)),
                ('upper_mid', models.FloatField(null=True)),
                ('wait_time', models.FloatField(null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('recomendation_time', models.DateTimeField(null=True)),
                ('quote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wait_condition_quote', to='oems.quote')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderqueue_order', to='oems.order')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderBrokerExecutionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('actual_price', models.FloatField(null=True)),
                ('filled_amount', models.FloatField(null=True)),
                ('actual_wait_time', models.FloatField(null=True)),
                ('actual_execution_time', models.DateTimeField(null=True)),
                ('filled', models.BooleanField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brokerexecution_order', to='oems.order')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
