# Generated by Django 4.2.7 on 2024-02-15 20:27

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import main.apps.oems.models.ticket
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0089_auto_20240122_1554'),
        ('currency', '0019_deliverytime'),
        ('oems', '0005_cnyexecution_fut_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('payment_id', models.UUIDField(default=uuid.uuid4)),
                ('amount', models.FloatField()),
                ('lock_side', models.CharField(choices=[('from', 'From'), ('to', 'To')], max_length=4)),
                ('tenor', models.CharField(choices=[('ON', 'ON'), ('TN', 'TN'), ('SPOT', 'SPOT'), ('SN', 'SN'), ('SW', 'SW'), ('1W', '1W'), ('2W', '2W'), ('3W', '3W'), ('1M', '1M'), ('2M', '2M'), ('3M', '3M'), ('4M', '4M'), ('5M', '5M'), ('6M', '6M'), ('7M', '7M'), ('8M', '8M'), ('9M', '9M'), ('1Y', '1Y')], max_length=10)),
                ('value_date', models.DateField()),
                ('draft', models.BooleanField(default=True)),
                ('time_in_force', models.CharField(choices=[('10sec', '10s'), ('1min', '1min'), ('1hr', '1hr')], max_length=10)),
                ('ticket_type', models.CharField(choices=[('payment', 'Payment'), ('rfq', 'RFQ'), ('execute', 'Execute'), ('hedge', 'Hedge')], max_length=10)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('order_length', models.IntegerField(blank=True, null=True)),
                ('date_conversion', models.CharField(blank=True, null=True)),
                ('execution_strategy', models.CharField(blank=True, choices=[('market', 'Market'), ('strategic_execution', 'Strategic Execution'), ('smart', 'SMART')], max_length=32, null=True)),
                ('upper_trigger', models.FloatField(blank=True, null=True)),
                ('lower_trigger', models.FloatField(blank=True, null=True)),
                ('ref_price', models.FloatField(blank=True, null=True)),
                ('trader', models.IntegerField(blank=True, null=True)),
                ('market_name', models.CharField(blank=True, max_length=16, null=True)),
                ('ticket_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=32, null=True)),
                ('instrument_type', models.CharField(blank=True, max_length=32, null=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('internal_trader', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=32, null=True)),
                ('paused', models.BooleanField(default=False)),
                ('destination', models.CharField(blank=True, max_length=32, null=True)),
                ('sub_destination', models.CharField(blank=True, max_length=32, null=True)),
                ('oms_owner', models.CharField(blank=True, max_length=32, null=True)),
                ('ems_owner', models.CharField(blank=True, max_length=32, null=True)),
                ('last_message_id', models.IntegerField(blank=True, null=True)),
                ('external_quote', models.FloatField(blank=True, null=True)),
                ('internal_quote', models.FloatField(blank=True, null=True)),
                ('phase', models.CharField(blank=True, choices=[('pretrade', 'Pretrade'), ('trade', 'Trade'), ('settle', 'Settle'), ('recon', 'Recon')], max_length=10, null=True, verbose_name=main.apps.oems.models.ticket.Ticket.Phases)),
                ('internal_state', models.CharField(blank=True, max_length=10, null=True)),
                ('external_state', models.CharField(blank=True, max_length=10, null=True)),
                ('internal_state_start', models.DateTimeField(blank=True, null=True)),
                ('external_state_start', models.DateTimeField(blank=True, null=True)),
                ('remaining_qty', models.IntegerField(blank=True, null=True)),
                ('done', models.FloatField(blank=True, null=True)),
                ('cntr_done', models.FloatField(blank=True, null=True)),
                ('all_in_done', models.FloatField(blank=True, null=True)),
                ('all_in_cntr_done', models.FloatField(blank=True, null=True)),
                ('penalty', models.FloatField(blank=True, null=True)),
                ('avg_price', models.FloatField(blank=True, null=True)),
                ('all_in_avg_price', models.FloatField(blank=True, null=True)),
                ('fee_avg_price', models.FloatField(blank=True, null=True)),
                ('fee', models.FloatField(blank=True, null=True)),
                ('fee_cntr', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('settlement_amount', models.FloatField(blank=True, null=True)),
                ('settlement_rate', models.FloatField(blank=True, null=True)),
                ('settlement_all_in_rate', models.FloatField(blank=True, null=True)),
                ('settlement_fee', models.FloatField(blank=True, null=True)),
                ('settlement_allocated', models.FloatField(blank=True, null=True)),
                ('settlement_unallocated', models.FloatField(blank=True, null=True)),
                ('settlement_info', models.JSONField(blank=True, null=True)),
                ('recon_info', models.JSONField(blank=True, null=True)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='broker.broker')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='account.company')),
                ('from_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_currency_ticket', to='currency.currency')),
                ('ref_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oems.ticket')),
                ('to_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_currency_ticket', to='currency.currency')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
