# Generated by Django 4.2.10 on 2024-02-16 15:40

from django.db import migrations, models
import main.apps.oems.models.ticket
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0089_auto_20240122_1554'),
        ('oems', '0006_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='company_id',
            new_name='company',
        ),
        migrations.AddField(
            model_name='ticket',
            name='algo',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='algo_fields',
            field=models.JSONField(blank=True, encoder=main.apps.oems.models.ticket.DateTimeEncoder, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='external_quote_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='internal_quote_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='internal_quote_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='quote_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='quote_type',
            field=models.CharField(blank=True, choices=[('api', 'API'), ('manual', 'MANUAL')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='qutoe_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='transaction_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='action',
            field=models.TextField(blank=True, choices=[('rfq', 'RFQ'), ('execute', 'Execute')], null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='broker',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_conversion',
            field=models.CharField(blank=True, choices=[('modified_follow', 'Modified Follow')], null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='destination',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ems_owner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='execution_strategy',
            field=models.CharField(blank=True, choices=[('market', 'Market'), ('strategic_execution', 'Strategic Execution'), ('smart', 'SMART')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='external_state',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='group_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='instrument_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='internal_state',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='internal_trader',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='last_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='market_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='oms_owner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='order_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phase',
            field=models.CharField(blank=True, choices=[('pretrade', 'Pretrade'), ('trade', 'Trade'), ('settle', 'Settle'), ('recon', 'Recon')], max_length=64, null=True, verbose_name=[('pretrade', 'Pretrade'), ('trade', 'Trade'), ('settle', 'Settle'), ('recon', 'Recon')]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='recon_info',
            field=models.JSONField(blank=True, encoder=main.apps.oems.models.ticket.DateTimeEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='remaining_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='settlement_info',
            field=models.JSONField(blank=True, encoder=main.apps.oems.models.ticket.DateTimeEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sub_destination',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tags',
            field=models.JSONField(blank=True, encoder=main.apps.oems.models.ticket.DateTimeEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('payment_rfq', 'Payment RFQ'), ('rfq', 'RFQ'), ('execute', 'Execute'), ('hedge', 'Hedge')], max_length=32),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time_in_force',
            field=models.CharField(choices=[('10sec', '10s'), ('1min', '1min'), ('1hr', '1hr'), ('gtc', 'GTC'), ('day', 'DAY')], max_length=8),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='trader',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('transaction_id', 'company')},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_id',
        ),
    ]
