# Generated by Django 4.2.7 on 2024-02-21 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0098_parachutedata_floating_pnl_fraction"),
        ("currency", "0019_deliverytime"),
        ("oems", "0006_order_orderevent_quote_waitcondition_orderqueue_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParachuteForwardConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_order_size", models.FloatField(default=0.0)),
                ("use_multiples", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.company",
                    ),
                ),
                (
                    "fxpair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="currency.fxpair",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "fxpair")},
            },
        ),
    ]
