# Generated by Django 4.2.3 on 2024-01-30 11:05

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0007_orderevent_order_orderevent_quote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderExecutionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('rate', models.FloatField(null=True)),
                ('rate_bid', models.FloatField(null=True)),
                ('rate_ask', models.FloatField(null=True)),
                ('execution_price', models.FloatField(null=True)),
                ('filled_amount', models.FloatField(null=True)),
                ('execution_time', models.DateTimeField(null=True)),
                ('filled', models.BooleanField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_result_order', to='oems.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='orderevent',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderevent',
            name='quote',
        ),
        migrations.AlterModelOptions(
            name='waitcondition',
            options={},
        ),
        migrations.RemoveField(
            model_name='waitcondition',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='waitcondition',
            name='min_lower',
        ),
        migrations.RemoveField(
            model_name='waitcondition',
            name='rate_start',
        ),
        migrations.RemoveField(
            model_name='waitcondition',
            name='upper_mid',
        ),
        migrations.RemoveField(
            model_name='waitcondition',
            name='wait_time',
        ),
        migrations.AddField(
            model_name='waitcondition',
            name='ai_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wait_condition_aimodel', to='ai.aimodel'),
        ),
        migrations.AddField(
            model_name='waitcondition',
            name='rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='waitcondition',
            name='rate_ask',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='waitcondition',
            name='rate_bid',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='OrderBrokerExecutionResult',
        ),
        migrations.DeleteModel(
            name='OrderEvent',
        ),
        migrations.AddField(
            model_name='orderexecutionresult',
            name='wait_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wait_condition_execution_result', to='oems.waitcondition'),
        ),
    ]
