# Generated by Django 4.2.10 on 2024-02-19 16:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0019_deliverytime'),
        ('account', '0089_auto_20240122_1554'),
        ('oems', '0007_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='qutoe_source',
            new_name='quote_source',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='all_in_cntr_done',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='all_in_done',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='amount',
            field=models.FloatField(help_text='The amount of currency being transferred in the transaction.'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cntr_done',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Related company associated with the transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='account.company'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer_id',
            field=models.TextField(blank=True, help_text='Identifier for the customer associated with the company for the transaction.', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='done',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='draft',
            field=models.BooleanField(default=True, help_text='Specifies whether the transaction is in draft stage or not.'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fee',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fee_cntr',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='from_currency',
            field=models.ForeignKey(blank=True, help_text='The currency being transferred from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_currency_ticket', to='currency.currency'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='lock_side',
            field=models.CharField(choices=[('from', 'From'), ('to', 'To')], help_text="The side of the transaction being locked, either 'From' or 'To'.", max_length=4),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='penalty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tenor',
            field=models.CharField(choices=[('ON', 'ON'), ('TN', 'TN'), ('SPOT', 'SPOT'), ('SN', 'SN'), ('SW', 'SW'), ('1W', '1W'), ('2W', '2W'), ('3W', '3W'), ('1M', '1M'), ('2M', '2M'), ('3M', '3M'), ('4M', '4M'), ('5M', '5M'), ('6M', '6M'), ('7M', '7M'), ('8M', '8M'), ('9M', '9M'), ('1Y', '1Y')], help_text='The tenor of the transaction, representing the settlement period.', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('payment_rfq', 'Payment RFQ'), ('rfq', 'RFQ'), ('execute', 'Execute'), ('hedge', 'Hedge')], help_text="Specifies the type of transaction, whether it's a payment, RFQ, execute, or hedge.", max_length=32),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time_in_force',
            field=models.CharField(choices=[('10sec', '10s'), ('1min', '1min'), ('1hr', '1hr'), ('gtc', 'GTC'), ('day', 'DAY')], help_text='Specifies the duration for which the transaction is valid.', max_length=8),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='to_currency',
            field=models.ForeignKey(blank=True, help_text='The currency being transferred to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_currency_ticket', to='currency.currency'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='transaction_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, help_text='Unique identifier for the transaction. Must be provided by the client to ensure idempotency.', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='value_date',
            field=models.DateField(help_text='The date when the transaction value will be settled.'),
        ),
    ]
