# Generated by Django 4.2.3 on 2024-02-01 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0008_orderexecutionresult_remove_orderevent_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitcondition',
            old_name='recomendation_time',
            new_name='recommendation_time',
        ),
    ]
