# Generated by Django 4.2.3 on 2024-02-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0009_rename_recomendation_time_waitcondition_recommendation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderexecutionresult',
            name='order_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
