# Generated by Django 4.2.10 on 2024-02-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0010_ticket_error_message_ticket_execution_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='rfq_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
