# Generated by Django 4.2.7 on 2024-02-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0007_parachuteforwardconfiguration'),
        ('oems', '0010_orderexecutionresult_order_number'),
    ]

    operations = [
    ]
