# Generated by Django 4.2.10 on 2024-02-21 15:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0013_alter_ticket_execution_strategy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='eid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
