# Generated by Django 4.2.10 on 2024-02-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0015_queue_alter_ticket_end_time_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['eid'], name='oems_ticket_eid_4a263d_idx'),
        ),
    ]
