# Generated by Django 4.2.10 on 2024-02-21 18:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0016_ticket_oems_ticket_eid_4a263d_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique identifier for the transaction. Must be provided by the client to ensure idempotency.'),
        ),
    ]
