# Generated by Django 4.2.10 on 2024-02-21 20:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0017_alter_ticket_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='eid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='execution_strategy',
            field=models.CharField(blank=True, choices=[('market', 'Market'), ('strategic_execution', 'Strategic Execution'), ('smart', 'SMART'), ('bestx', 'Best Execution')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tenor',
            field=models.CharField(blank=True, choices=[('ON', 'ON'), ('TN', 'TN'), ('SPOT', 'SPOT'), ('SN', 'SN'), ('SW', 'SW'), ('1W', '1W'), ('2W', '2W'), ('3W', '3W'), ('1M', '1M'), ('2M', '2M'), ('3M', '3M'), ('4M', '4M'), ('5M', '5M'), ('6M', '6M'), ('7M', '7M'), ('8M', '8M'), ('9M', '9M'), ('1Y', '1Y'), ('FWD', 'FWD')], help_text='The tenor of the transaction, representing the settlement period.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the transaction. Must be provided by the client to ensure idempotency.'),
        ),
    ]
