# Generated by Django 4.2.10 on 2024-02-21 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0019_deliverytime'),
        ('oems', '0019_remove_ticket_oems_ticket_eid_4a263d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fxpair',
            field=models.ForeignKey(blank=True, help_text='FxPair Object Reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_fx_pair', to='currency.fxpair'),
        ),
    ]
