# Generated by Django 4.2.10 on 2024-02-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0020_ticket_fxpair'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='limit_trigger',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='stop_trigger',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='execution_strategy',
            field=models.CharField(blank=True, choices=[('market', 'Market'), ('limit', 'Limit'), ('stop', 'Stop'), ('trigger', 'Trigger'), ('strategic_execution', 'Strategic Execution'), ('smart', 'SMART'), ('bestx', 'Best Execution')], max_length=128, null=True),
        ),
    ]
