# Generated by Django 4.2.10 on 2024-02-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0021_ticket_limit_trigger_ticket_stop_trigger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='transaction_group',
            field=models.TextField(blank=True, help_text='Identifier to provide transaction grouping.', null=True),
        ),
    ]
