# Generated by Django 4.2.10 on 2024-02-23 14:22

from django.db import migrations, models
import main.apps.oems.models.extensions


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0022_ticket_transaction_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='auth_time',
            field=main.apps.oems.models.extensions.DateTimeWithoutTZField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='auth_user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
