# Generated by Django 4.2.10 on 2024-02-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0024_queue_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='all_in_avg_price',
            new_name='all_in_rate',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='avg_price',
            new_name='rate',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='value_date',
            field=models.DateField(help_text='The date when the transaction value will be settled. Defaults to next business day if non-settlement day provided.'),
        ),
    ]
