# Generated by Django 4.2.10 on 2024-02-23 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0011_merge_20240221_1555'),
        ('oems', '0025_rename_all_in_avg_price_ticket_all_in_rate_and_more'),
    ]

    operations = [
    ]
