# Generated by Django 4.2.10 on 2024-02-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0026_merge_20240223_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='limit_trigger',
            field=models.FloatField(blank=True, help_text='Execution will leave a resting order to execute at a maximum of this price or better. This is a resting order.', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='lower_trigger',
            field=models.FloatField(blank=True, help_text='Execution begins when price goes below this threshold.', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='stop_trigger',
            field=models.FloatField(blank=True, help_text='Execution will begin when price crosses below this threshold. This is a stop-loss order. This is a resting order.', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='upper_trigger',
            field=models.FloatField(blank=True, help_text='Execution begins when price goes above this threshold.', null=True),
        ),
        migrations.AlterField(
            model_name='waitcondition',
            name='ai_model',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
