# Generated by Django 4.2.10 on 2024-02-27 21:15

from django.db import migrations, models
import main.apps.oems.models.extensions


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0028_ticket_beneficiaries_alter_ticket_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='resp_at',
            field=main.apps.oems.models.extensions.DateTimeWithoutTZField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tenor',
            field=models.CharField(blank=True, choices=[('ON', 'ON'), ('TN', 'TN'), ('spot', 'Spot'), ('SN', 'SN'), ('SW', 'SW'), ('1W', '1W'), ('2W', '2W'), ('3W', '3W'), ('1M', '1M'), ('2M', '2M'), ('3M', '3M'), ('4M', '4M'), ('5M', '5M'), ('6M', '6M'), ('7M', '7M'), ('8M', '8M'), ('9M', '9M'), ('1Y', '1Y'), ('fwd', 'Fwd')], help_text='The tenor of the transaction, representing the settlement period.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Unique identifier for the transaction. Must be provided by the client to ensure idempotency.', max_length=255, null=True),
        ),
    ]
