# Generated by Django 4.2.10 on 2024-02-28 15:48

from django.db import migrations
import main.apps.oems.models.extensions


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0030_alter_ticket_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='trigger_time',
            field=main.apps.oems.models.extensions.DateTimeWithoutTZField(blank=True, null=True),
        ),
    ]
