# Generated by Django 4.2.10 on 2024-02-28 05:11

from django.db import migrations
import main.apps.oems.models.extensions


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0030_alter_ticket_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderexecutionresult',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderexecutionresult',
            name='wait_condition',
        ),
        migrations.RemoveField(
            model_name='orderqueue',
            name='order',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderExecutionResult',
        ),
        migrations.DeleteModel(
            name='OrderQueue',
        ),
    ]
