# Generated by Django 4.2.10 on 2024-02-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0031_ticket_trigger_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cashflow_id',
            field=models.TextField(blank=True, help_text='Unique identifier for the cashflow.', null=True),
        ),
    ]
