# Generated by Django 4.2.10 on 2024-02-28 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0031_remove_orderexecutionresult_order_and_more'),
        ('oems', '0032_ticket_cashflow_id'),
    ]

    operations = [
    ]
