# Generated by Django 4.2.10 on 2024-02-29 00:23

from django.db import migrations, models
import main.apps.oems.backend.utils


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0033_merge_20240228_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='beneficiaries',
            field=models.JSONField(blank=True, encoder=main.apps.oems.backend.utils.DateTimeEncoder, help_text='Generic beneficiary and settlement information.', null=True),
        ),
    ]
