# Generated by Django 4.2.10 on 2024-02-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0034_alter_ticket_beneficiaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='cashflow_id',
            field=models.TextField(blank=True, help_text='Unique identifier for the cashflow. If cashflow_id is provided, required fields are not necessary as they will be filled in appropriated from the cashflow.', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='lock_side',
            field=models.CharField(choices=[('from', 'From'), ('to', 'To')], help_text="The side of the transaction being locked, either 'from' or 'to'.", max_length=4),
        ),
    ]
