# Generated by Django 4.2.10 on 2024-03-01 19:10

from django.db import migrations, models
import main.apps.oems.backend.utils
import main.apps.oems.models.extensions


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0035_alter_ticket_cashflow_id_alter_ticket_lock_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='hedge_strategy',
            field=models.TextField(blank=True, choices=[('self_directed', 'Self-Directed'), ('autopilot', 'Autopilot'), ('parachute', 'Parachute'), ('zero_gravity', 'Zero-Gravity')], help_text='User-defined hedging strategy', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='hedge_strategy_fields',
            field=models.JSONField(blank=True, encoder=main.apps.oems.backend.utils.DateTimeEncoder, help_text='Hedging-strategy specific fields. Please see documentation for defaults and customization.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='internal_quote_info',
            field=models.JSONField(blank=True, encoder=main.apps.oems.backend.utils.DateTimeEncoder, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_mark_time',
            field=main.apps.oems.models.extensions.DateTimeWithoutTZField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='mark_to_market',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='mtm_info',
            field=models.JSONField(blank=True, encoder=main.apps.oems.backend.utils.DateTimeEncoder, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='quote_indicative',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cashflow_id',
            field=models.TextField(blank=True, help_text='Unique identifier for the cashflow. If cashflow_id is provided, required fields are not necessary as they will be filled in appropriately from the cashflow.', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='lower_trigger',
            field=models.FloatField(blank=True, help_text='Execution begins when client price goes below this threshold.', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='transaction_id',
            field=models.TextField(blank=True, help_text='Client-supplied unique identifier for the transaction.', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='upper_trigger',
            field=models.FloatField(blank=True, help_text='Execution begins when client price goes above this threshold.', null=True),
        ),
    ]
