# Generated by Django 4.2.10 on 2024-03-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0036_ticket_hedge_strategy_ticket_hedge_strategy_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fixing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fixing_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fixing_venue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='amount',
            field=models.FloatField(help_text='The amount of lock_side currency being transferred in the transaction.'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='transaction_group',
            field=models.TextField(blank=True, help_text='Client-supplied identifier to provide transaction grouping.', null=True),
        ),
    ]
