# Generated by Django 4.2.10 on 2024-03-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0037_ticket_fixing_date_ticket_fixing_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cnyexecution',
            old_name='order_size_limit',
            new_name='max_order_size_from',
        ),
        migrations.RemoveField(
            model_name='cnyexecution',
            name='calendar_code',
        ),
        migrations.RemoveField(
            model_name='cnyexecution',
            name='dest',
        ),
        migrations.RemoveField(
            model_name='cnyexecution',
            name='order_length',
        ),
        migrations.RemoveField(
            model_name='cnyexecution',
            name='sub_dest',
        ),
        migrations.RemoveField(
            model_name='cnyexecution',
            name='trader',
        ),
        migrations.AddField(
            model_name='cnyexecution',
            name='default_broker',
            field=models.TextField(default='CORPAY'),
        ),
        migrations.AddField(
            model_name='cnyexecution',
            name='default_exec_strat',
            field=models.TextField(default='MARKET'),
        ),
        migrations.AddField(
            model_name='cnyexecution',
            name='default_hedge_strat',
            field=models.TextField(default='SELFDIRECTED'),
        ),
        migrations.AddField(
            model_name='cnyexecution',
            name='fwd_dest',
            field=models.CharField(default='CORPAY', max_length=255),
        ),
        migrations.AddField(
            model_name='cnyexecution',
            name='fwd_rfq_dest',
            field=models.CharField(default='RFQ', max_length=255),
        ),
        migrations.AddField(
            model_name='cnyexecution',
            name='max_order_size_to',
            field=models.FloatField(default=5000000.0),
        ),
        migrations.AddField(
            model_name='cnyexecution',
            name='min_order_size_from',
            field=models.FloatField(default=0.01),
        ),
        migrations.AddField(
            model_name='cnyexecution',
            name='min_order_size_to',
            field=models.FloatField(default=0.01),
        ),
        migrations.AddField(
            model_name='cnyexecution',
            name='rfq_type',
            field=models.CharField(choices=[('api', 'API'), ('manual', 'MANUAL'), ('unsupported', 'UNSUPPORTED'), ('indicative', 'INDICATIVE')], default='unsupported', max_length=16),
        ),
        migrations.AddField(
            model_name='cnyexecution',
            name='spot_dest',
            field=models.CharField(default='CORPAY', max_length=255),
        ),
        migrations.AddField(
            model_name='cnyexecution',
            name='spot_rfq_dest',
            field=models.CharField(default='RFQ', max_length=255),
        ),
        migrations.AlterField(
            model_name='cnyexecution',
            name='default_algo',
            field=models.CharField(default='MARKET', max_length=255),
        ),
    ]
