# Generated by Django 4.2.10 on 2024-03-07 19:03

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0019_deliverytime'),
        ('oems', '0040_remove_cnyexecution_fut_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('external_id', models.UUIDField(default=uuid.uuid4)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('expired', 'Expired'), ('complete', 'Complete')], max_length=8)),
                ('lock_side', models.CharField(choices=[('from', 'From'), ('to', 'To')], max_length=4)),
                ('amount', models.FloatField()),
                ('rate', models.FloatField()),
                ('premium', models.FloatField()),
                ('fee', models.FloatField()),
                ('all_in_rate', models.FloatField()),
                ('value_date', models.DateField()),
                ('fixing_date', models.DateField()),
                ('time_in_force', models.CharField(choices=[('15min', '15min')], max_length=5)),
                ('exec_user', models.CharField(max_length=40)),
                ('expiration_time', models.DateField()),
                ('slack_channel', models.CharField(max_length=100)),
                ('slack_ts', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=256)),
                ('email_status', models.CharField(max_length=100)),
                ('victor_ops_id', models.CharField(max_length=100)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='currency.currency')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_request', to='oems.ticket')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='currency.currency')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
