# Generated by Django 4.2.10 on 2024-03-11 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0019_deliverytime'),
        ('oems', '0042_cnyexecution_max_tenor_alter_cnyexecution_rfq_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='from_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quote_from_currency', to='currency.currency'),
        ),
        migrations.AddField(
            model_name='quote',
            name='to_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quote_to_currency', to='currency.currency'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quote_pair', to='currency.fxpair'),
        ),
    ]
