# Generated by Django 4.2.10 on 2024-03-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0045_manualrequest_action_manualrequest_ref_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualrequest',
            name='ticket',
            field=models.IntegerField(),
        ),
    ]
