# Generated by Django 4.2.10 on 2024-03-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0046_alter_manualrequest_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualrequest',
            name='fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manualrequest',
            name='on_behalf_of',
            field=models.TextField(blank=True, null=True),
        ),
    ]
