# Generated by Django 4.2.10 on 2024-03-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0048_auto_20240313_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualrequest',
            name='exec_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
