# Generated by Django 4.2.10 on 2024-03-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0050_alter_manualrequest_time_in_force'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='side',
            field=models.CharField(blank=True, choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('BuySell', 'BuySell'), ('SellBuy', 'SellBuy')], max_length=10, null=True),
        ),
    ]
