# Generated by Django 4.2.10 on 2024-03-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0051_ticket_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='side',
            field=models.CharField(blank=True, choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('BuySell', 'BuySell'), ('SellBuy', 'SellBuy'), ('Transfer', 'Transfer')], max_length=10, null=True),
        ),
    ]
