# Generated by Django 4.2.10 on 2024-03-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0052_alter_ticket_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='lock_side',
            field=models.CharField(choices=[('from', 'From'), ('to', 'To')], help_text="The side of the transaction being locked, either 'buy' or 'sell'.", max_length=4),
        ),
    ]
