# Generated by Django 4.2.10 on 2024-03-25 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0022_alter_deliverytime_country'),
        ('oems', '0052_alter_ticket_side'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manualrequest',
            old_name='to_currency',
            new_name='buy_currency',
        ),
        migrations.RenameField(
            model_name='manualrequest',
            old_name='from_currency',
            new_name='sell_currency',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='to_currency',
            new_name='buy_currency',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='from_currency',
            new_name='sell_currency',
        ),
        migrations.AlterField(
            model_name='manualrequest',
            name='lock_side',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='currency.currency'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='lock_side',
            field=models.ForeignKey(blank=True, help_text='ISO 4217 Standard 3-Letter Currency Code used to reference the amount currency.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lock_side_currency_ticket', to='currency.currency'),
        ),
    ]
