# Generated by Django 5.0.3 on 2024-03-27 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0023_currency_populate_unit'),
        ('oems', '0053_rename_to_currency_manualrequest_buy_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='lock_side',
            field=models.ForeignKey(blank=True, help_text='ISO 4217 Standard 3-Letter Currency Code used to reference the amount of currency.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lock_side_currency_ticket', to='currency.currency'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tenor',
            field=models.CharField(blank=True, choices=[('RTP', 'RTP'), ('ON', 'ON'), ('TN', 'TN'), ('spot', 'Spot'), ('SN', 'SN'), ('SW', 'SW'), ('1W', '1W'), ('2W', '2W'), ('3W', '3W'), ('1M', '1M'), ('2M', '2M'), ('3M', '3M'), ('4M', '4M'), ('5M', '5M'), ('6M', '6M'), ('7M', '7M'), ('8M', '8M'), ('9M', '9M'), ('1Y', '1Y'), ('fwd', 'Fwd')], help_text='The tenor of the transaction, representing the settlement period.', max_length=10, null=True),
        ),
    ]
