# Generated by Django 4.2.11 on 2024-03-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0053_alter_ticket_lock_side'),
        ('oems', '0054_alter_ticket_lock_side_alter_ticket_tenor'),
    ]

    operations = [
    ]
