# Generated by Django 4.2.10 on 2024-04-02 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0023_currency_populate_unit'),
        ('oems', '0055_merge_20240328_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='with_care',
            field=models.BooleanField(default=True, help_text='Specifies whether the transaction should be manual.'),
        ),
    ]
