# Generated by Django 4.2.11 on 2024-04-04 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0023_currency_populate_unit'),
        ('oems', '0056_ticket_with_care_alter_ticket_lock_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tenor',
            field=models.CharField(blank=True, choices=[('RTP', 'RTP'), ('ON', 'ON'), ('TN', 'TN'), ('spot', 'Spot'), ('SN', 'SN'), ('SW', 'SW'), ('1W', '1W'), ('2W', '2W'), ('3W', '3W'), ('1M', '1M'), ('2M', '2M'), ('3M', '3M'), ('4M', '4M'), ('5M', '5M'), ('6M', '6M'), ('7M', '7M'), ('8M', '8M'), ('9M', '9M'), ('1Y', '1Y'), ('fwd', 'Fwd'), ('ndf', 'NDF')], help_text='The tenor of the transaction, representing the settlement period.', max_length=10, null=True),
        ),
    ]
