# Generated by Django 4.2.11 on 2024-04-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0058_alter_ticket_lock_side'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE oems_ticket DROP COLUMN IF EXISTS lock_side_id"
        ),
    ]
