# Generated by Django 4.2.11 on 2024-04-12 03:40

from django.db import migrations, models
import main.apps.oems.models.extensions


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0061_ticket_external_id_ticket_options_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fwd_points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='transaction_time',
            field=main.apps.oems.models.extensions.DateTimeWithoutTZField(blank=True, null=True),
        ),
    ]
