# Generated by Django 4.2.11 on 2024-04-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0062_ticket_fwd_points_ticket_transaction_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='with_care',
            field=models.BooleanField(default=False, help_text='Specifies whether the transaction should be handled manually by the desk.'),
        ),
    ]
