# Generated by Django 4.2.11 on 2024-04-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0063_alter_ticket_with_care'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='account_id',
            field=models.TextField(blank=True, help_text='Unique identifier for account.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='clearing_account_id',
            field=models.TextField(blank=True, help_text='Unique identifier for the clearing account.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='funding',
            field=models.CharField(blank=True, default='postfunded', help_text='Specifies the ticket funding type.', max_length=32, null=True, verbose_name=[('prefunded', 'prefunded'), ('postfunded', 'postfunded'), ('margined', 'margined')]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='instrument_type',
            field=models.CharField(blank=True, choices=[('spot', 'SPOT'), ('fwd', 'FWD'), ('ndf', 'NDF'), ('option_strategy', 'OPTION_STRATEGY'), ('fut', 'FUT'), ('fut_as_fwd', 'FUT_AS_FWD')], null=True),
        ),
    ]
