# Generated by Django 4.2.11 on 2024-04-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0064_ticket_account_id_ticket_clearing_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fixing_source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
