# Generated by Django 4.2.11 on 2024-04-19 01:31

from django.db import migrations, models
import main.apps.oems.backend.utils


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0068_alter_ticket_lock_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='trade_details',
            field=models.JSONField(blank=True, encoder=main.apps.oems.backend.utils.DateTimeEncoder, null=True),
        ),
    ]
