# Generated by Django 4.2.11 on 2024-04-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0070_cnyexecution_unit_order_size_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='commission',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='commission_ccy',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='funding',
            field=models.CharField(blank=True, default='postfunded', help_text='Specifies the ticket funding type.', max_length=32, null=True, verbose_name=[('prefunded', 'prefunded'), ('postfunded', 'postfunded'), ('premargined', 'premargined'), ('postmargined', 'postmargined')]),
        ),
    ]
