# Generated by Django 4.2.11 on 2024-04-22 19:17

from django.db import migrations
import main.apps.oems.models.extensions


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0072_alter_ticket_funding'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='funding_deadline',
            field=main.apps.oems.models.extensions.DateTimeWithoutTZField(blank=True, null=True),
        ),
    ]
