# Generated by Django 4.2.11 on 2024-04-30 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oems', '0073_ticket_funding_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='instrument_type',
            field=models.CharField(blank=True, choices=[('spot', 'SPOT'), ('fwd', 'FWD'), ('ndf', 'NDF'), ('option_strategy', 'OPTION_STRATEGY'), ('fut', 'FUT'), ('fut_as_fwd', 'FUT_AS_FWD'), ('fwd_then_spot', 'FWD_THEN_SPOT'), ('ndf_then_spot', 'NDF_THEN_SPOT')], null=True),
        ),
    ]
