# Generated by Django 4.2.11 on 2024-05-03 14:04

from django.db import migrations, models
import main.apps.oems.backend.utils


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0074_alter_quote_user_alter_ticket_instrument_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='instrument_fields',
            field=models.JSONField(blank=True, encoder=main.apps.oems.backend.utils.DateTimeEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='instrument_type',
            field=models.CharField(blank=True, choices=[('spot', 'SPOT'), ('fwd', 'FWD'), ('ndf', 'NDF'), ('window_fwd', 'WINDOW_FWD'), ('option_strategy', 'OPTION_STRATEGY'), ('fut', 'FUT'), ('fut_as_fwd', 'FUT_AS_FWD'), ('fwd_then_spot', 'FWD_THEN_SPOT'), ('ndf_then_spot', 'NDF_THEN_SPOT')], null=True),
        ),
    ]
