# Generated by Django 4.2.11 on 2024-05-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0076_cnyexecution_fwd_broker_cnyexecution_spot_broker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='payment_memo',
            field=models.TextField(blank=True, help_text='Internal free-form payment memo.', null=True),
        ),
    ]
