# Generated by Django 4.2.11 on 2024-05-13 17:02

import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def update_cny_execute(app, schema_editor):
    CnyExecution = app.get_model('oems', 'CnyExecution')

    cny = CnyExecution.objects.all()
    cny_to_update = []

    for _ in cny:
        if _.fwd_rfq_type != 'unsupported':
            _.spot_rfq_type = 'api'
            cny_to_update.append(_)
    CnyExecution.objects.bulk_update(cny_to_update, ['spot_rfq_type'])


class Migration(migrations.Migration):
    dependencies = [
        ('oems', '0079_update_cny_execute'),
    ]

    operations = [
        migrations.RunPython(update_cny_execute),
    ]
