# Generated by Django 4.2.11 on 2024-05-13 17:02

import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def update_cny_execute(app, schema_editor):
    CnyExecution = app.get_model('oems', 'CnyExecution')
    # FxPair = app.get_model('currency','FxPair')
    Currency = app.get_model('currency','Currency')

    cny = CnyExecution.objects.all()
    cny_to_update = []
    NDF_CURRENCIES = ('INR','UGX','KES','TZS','ZMW','ARS','PEN','CLP','COP','TWD','VND','KRW','CNY','PHP')

    for _ in cny:
        if _.fwd_rfq_type == 'api':

            base_currency = Currency.objects.get(pk=_.fxpair.base_currency_id)
            quote_currency = Currency.objects.get(pk=_.fxpair.quote_currency_id)

            if base_currency.mnemonic in NDF_CURRENCIES or quote_currency.mnemonic in NDF_CURRENCIES:
                # print( 'setting', base_currency.mnemonic, quote_currency.mnemonic)
                _.fwd_rfq_type = 'manual'
                cny_to_update.append(_)
            # print( 'keeping api', base_currency.mnemonic, quote_currency.mnemonic)

    if cny_to_update:
        CnyExecution.objects.bulk_update(cny_to_update, ['fwd_rfq_type'])


class Migration(migrations.Migration):
    dependencies = [
        ('oems', '0081_auto_20240514_0119'),
    ]

    operations = [
        migrations.RunPython(update_cny_execute),
    ]
