# Generated by Django 4.2.11 on 2024-05-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0082_auto_20240514_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='delivery_fee',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='delivery_fee_unit',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
