# Generated by Django 4.2.11 on 2024-05-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0085_ticket_mass_payment_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualrequest',
            name='time_in_force',
            field=models.CharField(choices=[('15min', '15min'), ('1hour', '1hour'), ('day', 'day'), ('gtc', 'gtc')], default='1hour', max_length=5),
        ),
    ]
