# Generated by Django 4.2.11 on 2024-05-13 17:02

import logging

from django.db import migrations
from main.apps.oems.models import CnyExecution
from main.apps.oems.backend.trading_utils import get_reference_data

logger = logging.getLogger(__name__)


def update_cny_execute(app, schema_editor):

    cny = CnyExecution.objects.all()
    cny_to_update = []

    for _ in cny:
        mkt = _.fxpair.market
        if 'RUB' in mkt: continue

        if _.spot_rfq_type == CnyExecution.RfqTypes.UNSUPPORTED and ('USD' in mkt or 'EUR' in mkt):
            logger.info(f'turning on spot api for {mkt}')
            _.spot_rfq_type = CnyExecution.RfqTypes.API
            cny_to_update.append(_)
        if _.fwd_rfq_type == CnyExecution.RfqTypes.UNSUPPORTED and 'USD' in mkt:
            ref = get_reference_data(mkt)
            if ref:
                rfq_type = CnyExecution.RfqTypes.API if ref['CCY_TYPE'] == 'Spot' else CnyExecution.RfqTypes.MANUAL
                logger.info(f'turning on fwd api for {mkt} :: {rfq_type}')
                _.fwd_rfq_type = rfq_type

    CnyExecution.objects.bulk_update(cny_to_update, ['spot_rfq_type','fwd_rfq_type'])


class Migration(migrations.Migration):
    dependencies = [
        ('oems', '0088_auto_20240524_0123'),
    ]

    operations = [
        migrations.RunPython(update_cny_execute),
    ]
