# Generated by Django 4.2.11 on 2024-05-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0089_auto_20240528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnyexecution',
            name='spot_broker',
            field=models.TextField(default='CORPAY'),
        ),
    ]
