# Generated by Django 4.2.11 on 2024-05-13 17:02
import csv
import logging

from django.db import migrations
from django.core.paginator import Paginator
from main.apps.currency.models import FxPair
from main.apps.oems.models.cny import CnyExecution

# ====

logger = logging.getLogger(__name__)

# ====

def update_cny_execute(app, schema_editor):

    dry_run = False
    if not dry_run:
        for _ in CnyExecution.objects.iterator():
            if _.spot_broker == 'CORPAY_MP':
                _.spot_broker = 'CORPAY'
                _.save()

class Migration(migrations.Migration):
    dependencies = [
        ('oems', '0091_auto_20240528_0123'),
    ]

    operations = [
        migrations.RunPython(update_cny_execute),
    ]
