# Generated by Django 4.2.11 on 2024-05-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0092_auto_20240529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='draft',
            field=models.BooleanField(default=False, help_text='Specifies whether the transaction is in draft stage or not.'),
        ),
    ]
