# Generated by Django 4.2.11 on 2024-06-03 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0093_alter_ticket_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualrequest',
            name='broker_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='manualrequest',
            name='fwd_points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manualrequest',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_request', to='oems.ticket'),
        ),
    ]
