# Generated by Django 4.2.11 on 2024-06-04 20:37

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0112_remove_user_accounts'),
        ('oems', '0095_manual_corpay_fwd_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeCycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('ticket_id', models.UUIDField(editable=False)),
                ('trader', models.TextField(blank=True, null=True)),
                ('market_name', models.TextField(blank=True, null=True)),
                ('side', models.CharField(blank=True, max_length=10, null=True)),
                ('cashflow_id', models.TextField(blank=True, help_text='Unique identifier for the cashflow. If cashflow_id is provided, required fields are not necessary as they will be filled in appropriately from the cashflow.', null=True)),
                ('transaction_id', models.TextField(blank=True, help_text='Client-supplied unique identifier for the transaction.', null=True)),
                ('transaction_group', models.TextField(blank=True, help_text='Client-supplied identifier to provide transaction grouping.', null=True)),
                ('customer_id', models.TextField(blank=True, help_text='Identifier for the customer associated with the company for the transaction.', null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, help_text='Related company associated with the transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_name', to='account.company')),
            ],
            options={
                'indexes': [models.Index(fields=['ticket_id'], name='oems_lifecy_ticket__bbabfe_idx')],
            },
        ),
    ]
