# Generated by Django 4.2.11 on 2024-05-13 17:02
import csv
import logging

from django.db import migrations
from django.core.paginator import Paginator
from main.apps.currency.models import FxPair
from main.apps.oems.models.cny import CnyExecution
from main.apps.oems.backend.utils import load_yml, Expand
from main.apps.marketdata.models.ref.instrument import Instrument

# ====

logger = logging.getLogger(__name__)

# ====

def update_cny_execute(app, schema_editor):

    path = Expand(__file__) + '/additional_ref.csv'

    ret = {}

    with open( path ) as f:
        reader = csv.DictReader(f, delimiter=',')
        for row in reader:
            row['QT_SPEC'] = int(row['QT_SPEC'])
            ret[ row['MARKET'] ] = row

    for k, v in ret.items():

        try:
            instrument = Instrument.objects.get(name=k)
        except:
            logger.info(f'ERROR: skipping {k}')
            continue

        instrument.reference['QT_SPEC'] = v['QT_SPEC']
        instrument.symbology['BBG']['FIGI'] = v['ID_BB_GLOBAL']
        instrument.save()
        logger.info(f'updated: {k}')
        
class Migration(migrations.Migration):
    dependencies = [
        ('oems', '0096_lifecycleevent'),
    ]

    operations = [
        migrations.RunPython(update_cny_execute),
    ]
