# Generated by Django 4.2.10 on 2024-03-25 16:51

import json

from django.apps.registry import Apps
from django.db import migrations
from django_celery_beat.models import PeriodicTask, IntervalSchedule

def create_rev_reporting_task(apps: Apps, schema_editor):

    schedule, created = IntervalSchedule.objects.get_or_create(
        every=1,
        period=IntervalSchedule.DAYS,
    )

    # Convert Autopilot Forward to Ticket
    task, created = PeriodicTask.objects.get_or_create(
        name='Daily Revenue Reporting',  # Human-readable name of the task
        defaults={
            'interval': schedule,
            'task': 'main.apps.oems.tasks.revenue_reporting.task_revenue_report',
            'args': json.dumps([]),
            'kwargs': json.dumps({'recips':['nicole@pangea.io','matt@pangea.io']}),
            'enabled': False,
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0097_update_ref'),
    ]

    operations = [
        migrations.RunPython(create_rev_reporting_task)
    ]
