# Generated by Django 4.2.11 on 2024-07-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0098_rev_reporting_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cnyexecution',
            name='default_algo',
        ),
        migrations.RemoveField(
            model_name='cnyexecution',
            name='default_exec_strat',
        ),
        migrations.RemoveField(
            model_name='cnyexecution',
            name='default_hedge_strat',
        ),
        migrations.AlterField(
            model_name='cnyexecution',
            name='default_broker',
            field=models.CharField(choices=[('CORPAY', 'CORPAY'), ('IBKR', 'IBKR'), ('CORPAY_MP', 'CORPAY_MP'), ('VERTO', 'VERTO'), ('NIUM', 'NIUM'), ('AZA', 'AZA'), ('MONEX', 'MONEX'), ('CONVERA', 'CONVERA'), ('OFX', 'OFX'), ('XE', 'XE'), ('OANDA', 'OANDA'), ('AIRWALLEX', 'AIRWALLEX')], default='CORPAY', max_length=32),
        ),
        migrations.AlterField(
            model_name='cnyexecution',
            name='fwd_broker',
            field=models.CharField(choices=[('CORPAY', 'CORPAY'), ('IBKR', 'IBKR'), ('CORPAY_MP', 'CORPAY_MP'), ('VERTO', 'VERTO'), ('NIUM', 'NIUM'), ('AZA', 'AZA'), ('MONEX', 'MONEX'), ('CONVERA', 'CONVERA'), ('OFX', 'OFX'), ('XE', 'XE'), ('OANDA', 'OANDA'), ('AIRWALLEX', 'AIRWALLEX')], default='CORPAY', max_length=32),
        ),
        migrations.AlterField(
            model_name='cnyexecution',
            name='spot_broker',
            field=models.CharField(choices=[('CORPAY', 'CORPAY'), ('IBKR', 'IBKR'), ('CORPAY_MP', 'CORPAY_MP'), ('VERTO', 'VERTO'), ('NIUM', 'NIUM'), ('AZA', 'AZA'), ('MONEX', 'MONEX'), ('CONVERA', 'CONVERA'), ('OFX', 'OFX'), ('XE', 'XE'), ('OANDA', 'OANDA'), ('AIRWALLEX', 'AIRWALLEX')], default='CORPAY', max_length=32),
        ),
    ]
