# Generated by Django 4.2.11 on 2024-07-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0009_brokercompanyinstrument_max_tenor_months_and_more'),
        ('oems', '0099_remove_cnyexecution_default_algo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cnyexecution',
            name='max_daily_tickets',
        ),
        migrations.RemoveField(
            model_name='cnyexecution',
            name='max_order_size_from',
        ),
        migrations.RemoveField(
            model_name='cnyexecution',
            name='max_order_size_to',
        ),
        migrations.RemoveField(
            model_name='cnyexecution',
            name='min_order_size_from',
        ),
        migrations.RemoveField(
            model_name='cnyexecution',
            name='min_order_size_to',
        ),
        migrations.RemoveField(
            model_name='cnyexecution',
            name='unit_order_size_from',
        ),
        migrations.RemoveField(
            model_name='cnyexecution',
            name='unit_order_size_to',
        ),
    ]
