# Generated by Django 4.2.14 on 2024-08-05 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0100_remove_cnyexecution_max_daily_tickets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cnyexecution',
            name='default_broker',
        ),
    ]
