# Generated by Django 4.2.15 on 2024-09-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0101_remove_cnyexecution_default_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualrequest',
            name='last_reminder_sent',
            field=models.DateTimeField(null=True),
        ),
    ]
