# Generated by Django 4.2.15 on 2024-09-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0101_remove_cnyexecution_default_broker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='phase',
            field=models.CharField(blank=True, choices=[('PRETRADE', 'Pretrade'), ('TRADE', 'Trade'), ('SETTLE', 'Settle'), ('RECON', 'Recon')], max_length=64, null=True, verbose_name=[('PRETRADE', 'Pretrade'), ('TRADE', 'Trade'), ('SETTLE', 'Settle'), ('RECON', 'Recon')]),
        ),
    ]
