# Generated by Django 4.2.15 on 2024-09-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0102_manualrequest_last_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualrequest',
            name='slack_form_link',
            field=models.CharField(null=True),
        ),
    ]
