# Generated by Django 4.2.15 on 2024-09-04 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0102_alter_ticket_phase'),
        ('oems', '0103_manualrequest_slack_form_link_alter_ticket_phase'),
    ]

    operations = [
    ]
