# Generated by Django 4.2.15 on 2024-09-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0105_alter_ticket_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='settlement_attempt',
            field=models.IntegerField(default=0, help_text='Settlement retry attempt', null=True),
        ),
    ]
