# Generated by Django 4.2.15 on 2024-10-11 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_alter_payment_payment_status'),
        ('cashflow', '0024_alter_singlecashflow_tickets'),
        ('oems', '0107_alter_waitcondition_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashflow',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cashflow.singlecashflow',),
        ),
        migrations.CreateModel(
            name='CashflowGenerator',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Cashflow Generators',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cashflow.cashflowgenerator',),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payment.payment',),
        ),
    ]
