# Generated by Django 4.2.15 on 2024-10-24 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0116_alter_company_currency_alter_company_onboarded'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLimitSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_amount_sell_spot', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum spot transaction sell amount', max_digits=20, verbose_name='Spot Max Sell Amount')),
                ('max_amount_buy_spot', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum spot transaction buy amount', max_digits=20, verbose_name='Spot Max Buy Amount')),
                ('max_amount_sell_fwd', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum forward transaction sell amount', max_digits=20, verbose_name='Forward Max Sell Amount')),
                ('max_amount_buy_fwd', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum forward transaction buy amount', max_digits=20, verbose_name='Forward Max Buy Amount')),
                ('max_tenor_in_month', models.IntegerField(help_text='Maximum forward transaction tenor in month', null=True, verbose_name='Maximum Tenor in Month')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limit_setting', to='account.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyApprovalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_method', models.CharField(choices=[('no_approval', 'No Approval Required'), ('approval_required', 'Approval Required')], default='no_approval', max_length=50)),
                ('approval_trigger', models.CharField(choices=[('all_approvals', 'All Transactions Require Approval'), ('min_approval', 'Approval Required If Exceeding Min Trigger')], default='all_approvals', max_length=50, null=True)),
                ('min_approval_trigger_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('enable_dual_approval', models.BooleanField(default=False, help_text='Enable dual concurrent approval?', verbose_name='Enable Dual Approval')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_setting', to='account.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyApprovalBypass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Approval Bypass User',
            },
        ),
        migrations.CreateModel(
            name='ApprovalLevelLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_level', models.CharField(choices=[('approval_level_1', 'Approval Level 1'), ('approval_level_2', 'Approval Level 2')], default='approval_level_1', max_length=50)),
                ('max_approval_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
        migrations.CreateModel(
            name='GroupApprovalAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('admin_customer-success', 'Admin - Customer Success'), ('admin_read-only', 'Admin - Read-only'), ('customer_admin', 'Customer - Admin'), ('customer_creator', 'Customer - Creator'), ('customer_manager', 'Customer - Manager'), ('customer_viewer', 'Customer - Viewer'), ('customer_corpay', 'Customer - CorPay'), ('customer_ibkr', 'Customer - IBKR'), ('admin_group', 'Group - Admin'), ('account_owner_group', 'Group - Account Owner'), ('manager_group', 'Group - Manager')], max_length=50)),
                ('approval_level', models.CharField(choices=[('approval_level_1', 'Approval Level 1'), ('approval_level_2', 'Approval Level 2')], null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
            options={
                'unique_together': {('company', 'group', 'approval_level')},
            },
        ),
    ]
