# Generated by Django 4.2.15 on 2024-10-24 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0116_alter_company_currency_alter_company_onboarded'),
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approvallevellimit',
            unique_together={('company', 'approval_level')},
        ),
    ]
