apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
    name: gcp-store-for-pangea-staging
spec:
    provider:
        gcpsm:
            projectID: pangea-staging-338618
            auth:
                workloadIdentity:
                    clusterLocation: us-central1
                    clusterName: pangea-staging-autopilot-cluster
                    clusterProjectID: pangea-staging-338618
                    serviceAccountRef:
                        name: external-secrets
                        namespace: pangea-staging
