# Generated by Django 4.2.10 on 2024-03-27 14:04

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashflow', '0009_cashflowgenerator_periodicity_end_date'),
        ('payment', '0004_remove_transaction_payment_delete_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('origin_account_id', models.CharField(max_length=50)),
                ('destination_account_id', models.CharField(max_length=50)),
                ('purpose_of_payment', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(choices=[('awaiting_funds', 'Awaiting Funds'), ('booked', 'Booked'), ('delivered', 'Delivered'), ('drafting', 'Drafting'), ('in_transit', 'In Transit'), ('scheduled', 'Scheduled'), ('working', 'Working')], default='drafting', max_length=25)),
                ('fee_in_bps', models.IntegerField(default=0, null=True)),
                ('fee', models.FloatField(default=0, null=True)),
                ('cashflow_generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_cashflow_generator', to='cashflow.cashflowgenerator')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
