# Generated by Django 4.2.11 on 2024-04-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_add_payment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='execution_timing',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('strategic_execution', 'Strategic Execution'), ('scheduled', 'Scheduled Transaction')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('awaiting_funds', 'Awaiting Funds'), ('booked', 'Booked'), ('delivered', 'Delivered'), ('drafting', 'Drafting'), ('in_transit', 'In Transit'), ('scheduled', 'Scheduled'), ('working', 'Working'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='drafting', max_length=25),
        ),
    ]
