# Generated by Django 4.2.11 on 2024-04-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_payment_execution_timing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='destination_account_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='origin_account_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
