# Generated by Django 4.2.11 on 2024-04-18 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0018_alter_cashflowgenerator_lock_side_and_more'),
        ('payment', '0007_alter_payment_destination_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cashflow_generator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='cashflow.cashflowgenerator'),
        ),
    ]
