# Generated by Django 4.2.11 on 2024-05-23 19:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_rename_payment_id_payment_payment_ident'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
