# Generated by Django 4.2.11 on 2024-05-23 19:56
import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    Payment = apps.get_model('payment', 'Payment')
    for row in Payment.objects.all():
        row.payment_id = uuid.uuid4()
        row.save()


class Migration(migrations.Migration):
    dependencies = [
        ('payment', '0012_payment_payment_id'),
    ]

    operations = [
        migrations.RunPython(gen_uuid)
    ]
