# Generated by Django 4.2.11 on 2024-05-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_alter_payment_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('awaiting_funds', 'Awaiting Funds'), ('booked', 'Booked'), ('delivered', 'Delivered'), ('drafting', 'Drafting'), ('in_transit', 'In Transit'), ('scheduled', 'Scheduled'), ('working', 'Working'), ('canceled', 'Canceled'), ('failed', 'Failed'), ('settlement_issue', 'Settlement Issue'), ('pend_auth', 'Pending Authorization'), ('strategic_execution', 'Strategic Ex')], default='drafting', max_length=25),
        ),
    ]
