# Generated by Django 4.2.11 on 2024-06-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_group',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
