# Generated by Django 4.2.11 on 2024-06-05 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_payment_auth_user_payment_create_user'),
        ('payment', '0016_payment_payment_group'),
    ]

    operations = [
    ]
