# Generated by Django 4.2.11 on 2024-06-11 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0112_remove_user_accounts'),
        ('payment', '0017_merge_20240605_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.company'),
        ),
    ]
