# Generated by Django 4.2.11 on 2024-06-11 02:01

from django.db import migrations
from django.apps.registry import Apps


def fill_payment_company_field(apps:Apps, schema_editor):
    Payment = apps.get_model('payment', 'Payment')

    payments = Payment.objects.all()
    for payment in payments:
        payment.company = payment.cashflow_generator.company
    Payment.objects.bulk_update(payments, ['company'])


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_payment_company'),
    ]

    operations = [
        migrations.RunPython(fill_payment_company_field, migrations.RunPython.noop)
    ]
