# Generated by Django 4.2.15 on 2024-08-29 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0112_remove_user_accounts'),
        ('payment', '0020_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_auth_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.company'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='execution_timing',
            field=models.CharField(blank=True, choices=[('immediate', 'Immediate'), ('strategic_execution', 'Strategic Execution'), ('scheduled', 'Scheduled Transaction')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='fee',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='fee_in_bps',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
