# Generated by Django 4.2.15 on 2024-10-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('awaiting_funds', 'Awaiting Funds'), ('booked', 'Booked'), ('delivered', 'Delivered'), ('drafting', 'Drafting'), ('in_transit', 'In Transit'), ('scheduled', 'Scheduled'), ('working', 'Working'), ('canceled', 'Canceled'), ('failed', 'Failed'), ('settlement_issue', 'Settlement Issue'), ('pend_auth', 'Pending Authorization'), ('strategic_execution', 'Strategic Ex'), ('expired', 'Expired'), ('pending_approval', 'Pending Approval'), ('trade_desk', 'Trade Desk'), ('pending_beneficiary', 'Pending Beneficiary'), ('payment_issue', 'Payment Issue'), ('settled', 'Settled'), ('approved', 'Approved')], default='drafting', max_length=25),
        ),
    ]
