# Generated by Django 4.2.15 on 2024-11-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='execution_option',
            field=models.CharField(blank=True, choices=[('immediate_spot', 'Immediate Spot'), ('immediate_forward', 'Immediate Forward'), ('immediate_ndf', 'Immediate NDF'), ('strategic_spot', 'Strategic Spot'), ('strategic_forward', 'Strategic Forward'), ('strategic_ndf', 'Strategic Execution NDF'), ('scheduled_spot', 'Scheduled Spot')], max_length=25, null=True),
        ),
    ]
