# Generated by Django 4.2.15 on 2024-10-11 11:11

import django.contrib.auth.models
from django.db import migrations
import main.apps.account.models.user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0030_rename_account_companysnapshotconfiguration_account_id'),
        ('django_rest_passwordreset', '0004_alter_resetpasswordtoken_user_agent'),
        ('drf_simple_invite', '0001_initial'),
        ('account', '0115_beneficiary_payment_wallet'),
        ('trench', '0003_auto_20190213_2330'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='InvitationToken',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('drf_simple_invite.invitationtoken',),
        ),
        migrations.CreateModel(
            name='MFAMethod',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trench.mfamethod',),
        ),
        migrations.CreateModel(
            name='ResetPasswordToken',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_rest_passwordreset.resetpasswordtoken',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.user',),
            managers=[
                ('objects', main.apps.account.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('history.useractivity',),
        ),
    ]
