# Generated by Django 3.2.8 on 2023-05-03 21:42

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_auto_20230323_0038'),
        ('corpay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardGuidelines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('bookdate', models.DateTimeField()),
                ('forward_maturity_days', models.IntegerField()),
                ('client_limit_amount', models.FloatField()),
                ('allow_book_deals', models.BooleanField()),
                ('forward_maturity_dates', models.IntegerField()),
                ('margin_call_percent', models.FloatField()),
                ('max_days', models.IntegerField()),
                ('forward_max_open_contract_interval', models.IntegerField()),
                ('hedging_agreement', models.BooleanField()),
                ('allow_book', models.BooleanField()),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency')),
                ('client_limit_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_client_limit_currency', to='currency.currency')),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpay.credentials')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForwardQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('quote_id', models.TextField()),
                ('rate_value', models.FloatField()),
                ('rate_lockside', models.CharField(choices=[('Payment', 'PAYMENT'), ('Settlement', 'SETTLEMENT')], max_length=24)),
                ('rate_operation', models.CharField(choices=[('Divide', 'DIVIDE'), ('Multiply', 'MULTIPLY')], max_length=24)),
                ('payment_amount', models.FloatField()),
                ('settlement_amount', models.FloatField()),
                ('forward_guideline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_forward_guideline', to='corpay.forwardguidelines')),
                ('payment_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_payment_currency', to='currency.currency')),
                ('rate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_rate_type', to='currency.fxpair')),
                ('settlement_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_settlement_currency', to='currency.currency')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
