# Generated by Django 3.2.8 on 2023-05-24 20:34

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0076_alter_cashflow_status'),
        ('currency', '0006_auto_20230323_0038'),
        ('corpay', '0003_beneficiary_beneficiarytemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FXBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateField()),
                ('order_number', models.IntegerField()),
                ('amount', models.FloatField()),
                ('is_posted', models.BooleanField()),
                ('balance', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FXBalanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('transaction_id', models.IntegerField()),
                ('order_number', models.IntegerField()),
                ('identifier', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency')),
                ('fx_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpay.fxbalance')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
