# Generated by Django 3.2.8 on 2023-05-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0004_fxbalance_fxbalancedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='fxbalance',
            name='account_number',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fxbalance',
            name='credit_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fxbalance',
            name='debit_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
