# Generated by Django 3.2.8 on 2023-05-25 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_auto_20230323_0038'),
        ('corpay', '0006_alter_fxbalancedetail_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='fxbalance',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency.currency'),
            preserve_default=False,
        ),
    ]
