# Generated by Django 3.2.8 on 2023-05-25 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0007_fxbalance_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxbalancedetail',
            name='fx_balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='corpay.fxbalance'),
        ),
    ]
