# Generated by Django 3.2.8 on 2023-06-25 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0009_fxforwardcosts'),
        ('corpay', '0010_auto_20230624_1725'),
    ]

    operations = [
    ]
