# Generated by Django 3.2.8 on 2023-07-06 00:19

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0011_merge_0009_fxforwardcosts_0010_auto_20230624_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpaysettings',
            name='credit_facility',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='CreditUtilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('used_credit', models.FloatField(default=0.0)),
                ('company_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpay.corpaysettings')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
