# Generated by Django 3.2.8 on 2023-08-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0014_alter_corpaysettings_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fxforwardcosts',
            name='average_volume',
        ),
        migrations.RemoveField(
            model_name='fxforwardcosts',
            name='min_notional',
        ),
        migrations.AddField(
            model_name='fxforwardcosts',
            name='average_volume_high',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fxforwardcosts',
            name='average_volume_low',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
