# Generated by Django 3.2.8 on 2023-08-09 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0016_beneficiary_is_withdraw'),
        ('corpay', '0017_auto_20230808_2301'),
    ]

    operations = [
    ]
