# Generated by Django 3.2.8 on 2023-08-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0017_auto_20230808_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxforwardcosts',
            name='average_volume_high',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fxforwardcosts',
            name='average_volume_low',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fxforwardcosts',
            name='cost_in_bps',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fxforwardcosts',
            name='notional_high',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fxforwardcosts',
            name='notional_low',
            field=models.FloatField(null=True),
        ),
    ]
