# Generated by Django 4.2 on 2023-08-14 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0018_auto_20230811_1322'),
        ('corpay', '0018_merge_20230809_2343'),
    ]

    operations = [
    ]
