# Generated by Django 4.2 on 2023-08-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0019_apirequestlog_apiresponselog'),
        ('corpay', '0019_merge_20230814_2020'),
    ]

    operations = [
    ]
