# Generated by Django 4.2.4 on 2023-08-26 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0078_alter_cashflow_currency_alter_draftcashflow_currency'),
        ('currency', '0007_auto_20230808_2148'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corpay', '0020_merge_20230815_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('type', models.CharField(choices=[('cashflow_details', 'Cashflow Details'), ('risk_details', 'Risk Details'), ('drawdown', 'drawdown'), ('ndf', 'NDF')])),
                ('request_details', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('processing', 'Processing'), ('processed', 'Processed'), ('closed', 'Closed')], default='new')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='account.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UpdateNDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('amount', models.FloatField()),
                ('delivery_date', models.DateField()),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.fxpair')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ndf_request', to='corpay.updaterequest')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
