# Generated by Django 4.2 on 2023-09-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0021_updaterequest_updatendf'),
    ]

    operations = [
        migrations.AddField(
            model_name='fxbalance',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('processing', 'Processing'), ('complete', 'Complete'), ('error', 'Error')], default='complete', max_length=10),
            preserve_default=False,
        ),
    ]
