# Generated by Django 4.2.4 on 2023-08-29 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0021_updaterequest_updatendf'),
        ('corpay', '0022_remove_forwardguidelines_forward_maturity_dates'),
    ]

    operations = [
    ]
