# Generated by Django 4.2.3 on 2023-09-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0022_fxbalance_status'),
        ('corpay', '0023_merge_20230829_1352'),
    ]

    operations = [
    ]
