# Generated by Django 4.2.3 on 2023-09-15 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0023_alter_fxbalancedetail_options_and_more'),
        ('corpay', '0024_merge_0022_fxbalance_status_0023_merge_20230829_1352'),
    ]

    operations = [
    ]
