# Generated by Django 4.2.3 on 2023-10-04 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0025_merge_20230915_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='forward',
            name='cash_settle_account',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='forward',
            name='destination_account',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='forward',
            name='drowdown_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='forward',
            name='funding_account',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='forward',
            name='is_cash_settle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forward',
            name='maturity_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forward',
            name='origin_account',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
