# Generated by Django 4.2.3 on 2023-10-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0026_forward_cash_settle_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forward',
            name='drawdown_order_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='forward',
            name='purpose_of_payment',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
