# Generated by Django 4.2.3 on 2023-10-13 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import main.apps.corpay.models.onboarding


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0081_company_service_interested_in'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corpay', '0029_alter_forward_order_number_alter_forward_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('client_onboarding_id', models.CharField(max_length=32)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OnboardingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=60)),
                ('file', models.FileField(upload_to=main.apps.corpay.models.onboarding.file_uploaded_to)),
                ('status', models.CharField(choices=[('new', 'New'), ('send_to_corpay', 'Sent to Corpay'), ('reviewed', 'Reviewed'), ('error', 'Error')], default='new', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpay.onboarding')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
