# Generated by Django 4.2.3 on 2023-10-26 20:28

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0030_onboarding_onboardingfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('currency_category', models.TextField(choices=[('p10', 'P10'), ('other', 'Other')], max_length=10)),
                ('average_volume_low', models.FloatField(null=True)),
                ('average_volume_high', models.FloatField(null=True)),
                ('notional_low', models.FloatField(null=True)),
                ('notional_high', models.FloatField(null=True)),
                ('cost_in_bps', models.FloatField(null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
