# Generated by Django 4.2.3 on 2023-10-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0032_aumcost_transactioncost_delete_currencycost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aumcost',
            name='currency_category',
            field=models.CharField(choices=[('p10', 'P10'), ('other', 'Other'), ('all', 'All')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transactioncost',
            name='currency_category',
            field=models.CharField(choices=[('p10', 'P10'), ('other', 'Other'), ('all', 'All')], max_length=10),
        ),
    ]
