# Generated by Django 4.2.3 on 2023-11-06 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0034_auto_20231026_2229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FxForwardCosts',
        ),
    ]
