# Generated by Django 4.2.3 on 2023-11-06 17:30

from django.db import migrations


def update_notional_high_null(apps, schema_editor):
    TransactionCost = apps.get_model('corpay', 'TransactionCost')
    TransactionCost.objects.filter(notional_high__isnull=True).update(notional_high=float('inf'))


class Migration(migrations.Migration):
    dependencies = [
        ('corpay', '0035_delete_fxforwardcosts'),
    ]

    operations = [
        migrations.RunPython(update_notional_high_null)
    ]
