# Generated by Django 4.2.3 on 2023-11-20 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0031_currencydefinition_fwd_delivery_buying_and_more'),
        ('corpay', '0036_auto_20231106_1730'),
    ]

    operations = [
    ]
