# Generated by Django 4.2.3 on 2023-11-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0037_merge_20231120_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpaysettings',
            name='max_horizon',
            field=models.IntegerField(default=365),
        ),
    ]
