# Generated by Django 4.2.3 on 2023-12-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0037_spotrate'),
        ('corpay', '0038_corpaysettings_max_horizon'),
    ]

    operations = [
    ]
