# Generated by Django 4.2.3 on 2023-12-19 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0039_merge_0037_spotrate_0038_corpaysettings_max_horizon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forward',
            old_name='drowdown_date',
            new_name='drawdown_date',
        ),
    ]
