# Generated by Django 4.2.7 on 2024-01-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0040_rename_drowdown_date_forward_drawdown_date'),
        ('corpay', '0040_rename_manualforwardrequest'),
        ('corpay', '0040_update_currency_definition'),
    ]

    operations = [
    ]
