# Generated by Django 4.2.3 on 2023-12-18 04:43

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0040_rename_drowdown_date_forward_drawdown_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDealRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('quote_id', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstructDealRequestSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('delivery_method', models.CharField(choices=[('W', 'Wire'), ('E', 'iACH'), ('C', 'FXBalance')])),
                ('account_id', models.CharField(max_length=50)),
                ('purpose', models.CharField(choices=[('All', 'All'), ('Allocation', 'Allocation'), ('Fee', 'Fee'), ('Spot', 'Spot'), ('Spot_trade', 'Spot Trade'), ('Drawdown', 'Drawdown')])),
                ('book_deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpay.bookdealrequest')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstructDealRequestPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('delivery_method', models.CharField(choices=[('W', 'Wire'), ('E', 'iACH'), ('C', 'FXBalance')])),
                ('beneficiary_id', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('purpose_of_payment', models.CharField(max_length=255)),
                ('payment_reference', models.CharField(max_length=255)),
                ('book_deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpay.bookdealrequest')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstructDealRequestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('order_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('book_deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpay.bookdealrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
