# Generated by Django 4.2.3 on 2024-01-16 11:31

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0019_deliverytime'),
        ('corpay', '0041_bookdealrequest_instructdealrequestsettlement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('amount', models.FloatField()),
                ('from_account_id', models.CharField(blank=True, max_length=50, null=True)),
                ('to_account_id', models.CharField(blank=True, max_length=50, null=True)),
                ('beneficiary_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('purpose_of_payment', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('purpose', models.CharField(choices=[('All', 'All'), ('Allocation', 'Allocation'), ('Fee', 'Fee'), ('Spot', 'Spot'), ('Spot_trade', 'Spot Trade'), ('Drawdown', 'Drawdown')])),
                ('delivery_method', models.CharField(choices=[('W', 'Wire'), ('E', 'iACH'), ('C', 'FXBalance')])),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruct_deal_request_to_currency', to='currency.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruct_deal_request_from_currency', to='currency.currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='instructdealrequestorder',
            name='book_deal',
        ),
        migrations.RemoveField(
            model_name='instructdealrequestpayment',
            name='book_deal',
        ),
        migrations.RemoveField(
            model_name='instructdealrequestpayment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='instructdealrequestsettlement',
            name='book_deal',
        ),
        migrations.RemoveField(
            model_name='instructdealrequestsettlement',
            name='currency',
        ),
        migrations.DeleteModel(
            name='BookDealRequest',
        ),
        migrations.DeleteModel(
            name='InstructDealRequestOrder',
        ),
        migrations.DeleteModel(
            name='InstructDealRequestPayment',
        ),
        migrations.DeleteModel(
            name='InstructDealRequestSettlement',
        ),
    ]
