# Generated by Django 4.2.10 on 2024-03-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0041_merge_20240116_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxbalance',
            name='order_number',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='fxbalancedetail',
            name='order_number',
            field=models.CharField(max_length=60),
        ),
    ]
