# Generated by Django 4.2.7 on 2024-02-22 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0019_deliverytime'),
        ('corpay', '0041_merge_20240116_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotrate',
            name='fx_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.fxpair'),
        ),
    ]
