# Generated by Django 4.2.10 on 2024-03-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0042_alter_fxbalance_order_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotrate',
            name='order_number',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
