# Generated by Django 4.2.7 on 2024-01-18 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0041_merge_20240116_1546'),
        ('corpay', '0043_remove_instructrequest_purpose_and_more'),
    ]

    operations = [
    ]
