# Generated by Django 4.2.3 on 2024-01-24 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0006_order_orderevent_quote_waitcondition_orderqueue_and_more'),
        ('corpay', '0043_remove_instructrequest_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructrequest',
            name='quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instruct_deal_request_quote', to='oems.quote'),
        ),
    ]
