# Generated by Django 4.2.3 on 2024-01-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0041_merge_20240116_1546'),
        ('corpay', '0044_instructrequest_quote'),
    ]

    operations = [
    ]
