# Generated by Django 4.2.7 on 2024-01-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0044_merge_20240118_2011'),
        ('corpay', '0045_merge_20240124_0024'),
    ]

    operations = [
    ]
