# Generated by Django 4.2.10 on 2024-02-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0042_alter_spotrate_fx_pair'),
        ('corpay', '0046_merge_20240124_1910'),
    ]

    operations = [
    ]
