# Generated by Django 4.2.10 on 2024-02-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0047_merge_20240222_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpaysettings',
            name='fee_wallet_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corpaysettings',
            name='pangea_beneficiary_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
