# Generated by Django 4.2.10 on 2024-03-27 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0043_alter_spotrate_order_number'),
        ('corpay', '0048_corpaysettings_fee_wallet_id_and_more'),
    ]

    operations = [
    ]
