# Generated by Django 4.2.11 on 2024-04-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0042_manualforwardrequest_cashflow'),
        ('corpay', '0049_merge_20240327_1934'),
    ]

    operations = [
    ]
