# Generated by Django 4.2.11 on 2024-04-23 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0023_currency_populate_unit'),
        ('account', '0110_alter_autopilotdata_account_and_more'),
        ('corpay', '0051_confirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementAccount',
            fields=[
                ('settlement_account_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('delivery_method', models.CharField(choices=[('W', 'Wire'), ('E', 'EFT'), ('C', 'FX Balance')], max_length=1)),
                ('text', models.CharField(max_length=255)),
                ('payment_ident', models.CharField(blank=True, max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_account', models.CharField(blank=True, max_length=255)),
                ('preferred', models.BooleanField(default=False)),
                ('selected', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency')),
            ],
        ),
    ]
