# Generated by Django 4.2.11 on 2024-04-23 19:48
import json
import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def create_cache_corpay_settlement_account_task(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    IntervalSchedule = apps.get_model('django_celery_beat', 'IntervalSchedule')
    every_5_min, created = IntervalSchedule.objects.update_or_create(
        every=5,
        period='minutes'
    )
    task, created = PeriodicTask.objects.get_or_create(
        name="Cache Corpay Settlement Account",
        defaults={
            'interval': every_5_min,
            'task': 'cache_all_corpay_settlement_accounts',
            'args': json.dumps([]),
            'kwargs': json.dumps([]),
            'enabled': True
        }
    )


def remove_cache_corpay_settlement_account_task(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    try:
        task = PeriodicTask.objects.get(name="Cache Corpay Settlement Account")
        task.delete()
    except Exception as e:
        logger.error(e)


class Migration(migrations.Migration):
    dependencies = [
        ('corpay', '0052_settlementaccount'),
    ]

    operations = [
        migrations.RunPython(create_cache_corpay_settlement_account_task, remove_cache_corpay_settlement_account_task),
    ]
