# Generated by Django 4.2.11 on 2024-04-24 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0023_currency_populate_unit'),
        ('corpay', '0053_auto_20240423_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='client_code',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='corpay_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corpay_beneficiaries', to='currency.currency'),
        ),
    ]
