# Generated by Django 4.2.11 on 2024-04-24 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0023_currency_populate_unit'),
        ('account', '0110_alter_autopilotdata_account_and_more'),
        ('corpay', '0054_beneficiary_client_code_beneficiary_corpay_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FXBalanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=60)),
                ('ledger_balance', models.DecimalField(decimal_places=4, max_digits=20)),
                ('balance_held', models.DecimalField(decimal_places=4, max_digits=20)),
                ('available_balance', models.DecimalField(decimal_places=4, max_digits=20)),
                ('account_number', models.CharField(max_length=60)),
                ('client_code', models.CharField(max_length=60)),
                ('client_division_id', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency')),
            ],
        ),
        migrations.CreateModel(
            name='FXBalanceAccountSettlementInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_na_associated', models.BooleanField(default=False)),
                ('incoming_account_number', models.CharField(max_length=60)),
                ('curr_name', models.CharField(max_length=50)),
                ('is_iban', models.BooleanField(default=False)),
                ('bene_info', models.TextField()),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_address', models.TextField()),
                ('bank_swift', models.CharField(max_length=60)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency')),
                ('fx_balance_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_instructions', to='corpay.fxbalanceaccount')),
            ],
        ),
    ]
