# Generated by Django 4.2.11 on 2024-04-30 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0056_auto_20240430_0311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SettlementAccount',
        ),
    ]
