# Generated by Django 4.2.11 on 2024-05-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0058_settlementaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlementaccount',
            name='bank_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
