# Generated by Django 4.2.11 on 2024-05-17 16:50

from django.db import migrations, models
def fix_dashes_in_beneficiary_id(apps, schema_editor):
    Beneficiary = apps.get_model('corpay', 'Beneficiary')
    for bene in Beneficiary.objects.all():
        bene.client_integration_id = str(bene.client_integration_id).replace('-', '')
        bene.save()

class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0059_alter_settlementaccount_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='client_integration_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(fix_dashes_in_beneficiary_id),
    ]
