# Generated by Django 4.2.11 on 2024-05-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0061_auto_20240517_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='corpay_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
