# Generated by Django 4.2.11 on 2024-05-20 20:54
import json
import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def create_sweep_corpay_fxaccount_balance_task(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    IntervalSchedule = apps.get_model('django_celery_beat', 'IntervalSchedule')
    every_1_day, created = IntervalSchedule.objects.update_or_create(
        every=1,
        period='days'
    )
    task, created = PeriodicTask.objects.get_or_create(
        name="Sweep Corpay FXAccount Balance",
        defaults={
            'interval': every_1_day,
            'task': 'sweep_corpay_fxaccount_balance',
            'args': json.dumps([]),
            'kwargs': json.dumps([]),
            'enabled': False
        }
    )


def remove_sweep_corpay_fxaccount_balance_task(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    try:
        task = PeriodicTask.objects.get(name="Sweep Corpay FXAccount Balance")
        task.delete()
    except Exception as e:
        logger.error(e)


class Migration(migrations.Migration):
    dependencies = [
        ('corpay', '0062_alter_beneficiary_corpay_id'),
    ]

    operations = [
        migrations.RunPython(create_sweep_corpay_fxaccount_balance_task, remove_sweep_corpay_fxaccount_balance_task)
    ]
