# Generated by Django 4.2.11 on 2024-06-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0063_auto_20240520_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='delivery_method',
            field=models.CharField(choices=[('W', 'Wire'), ('E', 'EFT'), ('C', 'FX Balance')], max_length=1, null=True),
        ),
    ]
