# Generated by Django 4.2.11 on 2024-06-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpay', '0064_beneficiary_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpaysettings',
            name='user_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
