# Generated by Django 3.2.8 on 2022-09-18 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_alter_brokeraccount_company'),
        ('ibkr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingrequest',
            name='broker_account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='funding_requests', to='account.brokeraccount'),
            preserve_default=False,
        ),
    ]
