# Generated by Django 3.2.8 on 2022-09-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0002_fundingrequest_broker_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingrequest',
            name='request_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
