# Generated by Django 3.2.8 on 2022-09-18 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0003_fundingrequest_request_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositfundresponse',
            name='ib_inst_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundingrequeststatus',
            name='error_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fundingrequeststatus',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundingrequeststatus',
            name='funding_request',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ibkr.fundingrequest'),
            preserve_default=False,
        ),
    ]
