# Generated by Django 3.2.8 on 2022-09-18 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0004_auto_20220918_0659'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DepositFundResponse',
            new_name='DepositFundsResponse',
        ),
    ]
