# Generated by Django 3.2.8 on 2022-09-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0008_auto_20220918_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositfundsresponse',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
