# Generated by Django 3.2.8 on 2022-09-18 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20220702_1908'),
        ('ibkr', '0009_depositfundsresponse_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositfundsresponse',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depositfundsresponse',
            name='method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
