# Generated by Django 3.2.8 on 2022-09-18 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0010_auto_20220918_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositfundsresponse',
            old_name='ib_inst_id',
            new_name='ib_instr_id',
        ),
    ]
