# Generated by Django 3.2.8 on 2022-09-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0011_rename_ib_inst_id_depositfundsresponse_ib_instr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingrequeststatus',
            name='response_data',
            field=models.JSONField(null=True),
        ),
    ]
