# Generated by Django 3.2.8 on 2022-09-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0012_fundingrequeststatus_response_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundingrequeststatus',
            name='response_data',
        ),
        migrations.AddField(
            model_name='fundingrequest',
            name='response_data',
            field=models.JSONField(null=True),
        ),
    ]
