# Generated by Django 3.2.8 on 2022-10-03 00:16

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_alter_brokeraccount_company'),
        ('ibkr', '0013_auto_20220918_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='IbkrAccountSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('broker_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_summaries', to='account.brokeraccount')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
