# Generated by Django 3.2.8 on 2022-10-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0016_auto_20221004_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibkraccountsummary',
            name='account_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
