# Generated by Django 3.2.8 on 2022-12-07 18:28

import django.db.models.deletion
from django.db import migrations, models


def initialize_wire_instructions(apps, schema_editor):
    currency = apps.get_model('currency', 'Currency')
    usd = currency.objects.filter(mnemonic='USD').first()
    if usd is not None:
        instructions = [
            {
                "currency": usd,
                "title": "United State Dollar (USD)",
                "destination": """JPMORGAN CHASE BANK, N.A.
    383 Madison Avenue
    New York 10179""",
                "routing_number": "021000021 (ABA)",
                "swift_bic_code": "CHASUS33XXX",
                "account_title": "Interactive Brokers LLC",
                "account_address": """One Pickwick Plaza
    Greenwich, Connecticut 06830
    United States""",
                "account_number": "633736902",
                "account_info": "",
                "payment_reference": "Account#/Account Name"
            },
            {
                "currency": usd,
                "title": "United State Dollar (USD) *From HK Bank",
                "destination": """HONGKONG AND SHANGHAI BANKING CORPORATION LIMITED
    1 Queen's Road Central
    Hong Kong""",
                "routing_number": "004/848",
                "swift_bic_code": "HSBCHKHHHKH",
                "account_title": "Interactive Brokers LLC",
                "account_address": """One Pickwick Plaza
    Greenwich, Connecticut 06830
    United States""",
                "account_number": "848-075750-201",
                "account_info": "",
                "payment_reference": "Account#/Account Name"
            }
        ]
        model = apps.get_model('ibkr', 'WireInstruction')
        for instruction in instructions:
            wire_instruction = model(**instruction)
            wire_instruction.save()

class Migration(migrations.Migration):
    dependencies = [
        ('currency', '0002_auto_20220702_1908'),
        ('ibkr', '0017_alter_ibkraccountsummary_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WireInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('destination', models.TextField(blank=True, null=True)),
                ('routing_number', models.CharField(blank=True, max_length=60, null=True)),
                ('swift_bic_code', models.CharField(blank=True, max_length=60, null=True)),
                ('account_title', models.CharField(blank=True, max_length=60, null=True)),
                ('account_address', models.TextField(blank=True, null=True)),
                ('account_number', models.CharField(blank=True, max_length=60, null=True)),
                ('account_info', models.TextField(blank=True, null=True)),
                ('payment_reference', models.TextField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency')),
            ],
        ),
        migrations.RunPython(initialize_wire_instructions)
    ]
