# Generated by Django 3.2.8 on 2022-12-07 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0068_switch_low_high'),
        ('ibkr', '0018_wireinstruction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wireinstruction',
            options={'verbose_name_plural': 'Wire Instructions'},
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=60)),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=11)),
                ('account', models.CharField(max_length=60)),
                ('entity', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ibkr_application', to='account.company')),
            ],
        ),
    ]
