# Generated by Django 3.2.8 on 2022-12-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0019_auto_20221207_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wireinstruction',
            old_name='destination',
            new_name='bank_address',
        ),
        migrations.RenameField(
            model_name='wireinstruction',
            old_name='account_number',
            new_name='beneficiary_account_number',
        ),
        migrations.RenameField(
            model_name='wireinstruction',
            old_name='account_address',
            new_name='beneficiary_address',
        ),
        migrations.RenameField(
            model_name='wireinstruction',
            old_name='account_title',
            new_name='beneficiary_name',
        ),
        migrations.RenameField(
            model_name='wireinstruction',
            old_name='routing_number',
            new_name='beneficiary_routing_number',
        ),
        migrations.RenameField(
            model_name='wireinstruction',
            old_name='payment_reference',
            new_name='wire_reference',
        ),
        migrations.AddField(
            model_name='wireinstruction',
            name='bank_name',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
