# Generated by Django 3.2.8 on 2023-01-09 01:20

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0020_auto_20221214_0304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depositfundsresponse',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='depositfundsresponse',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depositfundsresponse',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
