# Generated by Django 4.2 on 2023-09-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0023_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='base_currency',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='future_start_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='ib_last_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='sec_type',
        ),
        migrations.AddField(
            model_name='contract',
            name='base',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='contract',
            name='fut_cont_size',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='contract',
            name='fut_start_dt',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='fut_val_pt',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='contract',
            name='ib_base',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='contract',
            name='ib_ccy',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='ib_conid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='ib_desc',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='ib_exch',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='ib_lastdt',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='ib_liquid_hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='ib_locsym',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='ib_mintick',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='ib_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='ib_mult',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='ib_name',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='ib_pricemag',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='ib_symbol',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='ib_timezone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='ib_trading_hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='ib_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='lcode_long',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='contract',
            name='month',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='contract',
            name='roll_dt',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='year',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='contract',
            name='symbol',
            field=models.CharField(default='', max_length=10),
        ),
    ]
