# Generated by Django 4.2 on 2023-09-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0024_remove_contract_base_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='symbol',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
