# Generated by Django 4.2 on 2023-09-06 02:12

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0025_alter_contract_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('future_symbol', models.CharField(default='', max_length=10, unique=True)),
                ('future_base', models.CharField(default='', max_length=5)),
                ('future_month', models.CharField(default='', max_length=5)),
                ('year', models.IntegerField(default=-1)),
                ('lcode_long', models.IntegerField(default=-1)),
                ('fut_val_pt', models.IntegerField(default=-1)),
                ('fut_cont_size', models.IntegerField(default=-1)),
                ('fut_start_dt', models.DateField(null=True)),
                ('roll_dt', models.DateField(null=True)),
                ('base', models.CharField(default='', max_length=5)),
                ('name', models.CharField(max_length=5, null=True)),
                ('desc', models.CharField(max_length=150, null=True)),
                ('symbol', models.CharField(max_length=5, null=True)),
                ('conid', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=10, null=True)),
                ('mult', models.IntegerField(null=True)),
                ('exch', models.CharField(max_length=5, null=True)),
                ('ccy', models.CharField(max_length=5, null=True)),
                ('locsym', models.CharField(max_length=5, null=True)),
                ('mintick', models.FloatField(null=True)),
                ('pricemag', models.IntegerField(null=True)),
                ('lastdt', models.DateField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('timezone', models.CharField(max_length=10, null=True)),
                ('trading_hours', models.IntegerField(null=True)),
                ('liquid_hours', models.IntegerField(null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
