# Generated by Django 4.2 on 2023-09-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0026_futurecontract_delete_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futurecontract',
            old_name='conid',
            new_name='con_id',
        ),
        migrations.RenameField(
            model_name='futurecontract',
            old_name='ccy',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='futurecontract',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='futurecontract',
            old_name='exch',
            new_name='exchange',
        ),
        migrations.RenameField(
            model_name='futurecontract',
            old_name='future_base',
            new_name='fut_base',
        ),
        migrations.RenameField(
            model_name='futurecontract',
            old_name='future_month',
            new_name='fut_month_symbol',
        ),
        migrations.RenameField(
            model_name='futurecontract',
            old_name='future_symbol',
            new_name='fut_symbol',
        ),
        migrations.RenameField(
            model_name='futurecontract',
            old_name='lastdt',
            new_name='last_dt',
        ),
        migrations.RenameField(
            model_name='futurecontract',
            old_name='name',
            new_name='market_name',
        ),
        migrations.RenameField(
            model_name='futurecontract',
            old_name='mintick',
            new_name='min_tick',
        ),
        migrations.RenameField(
            model_name='futurecontract',
            old_name='mult',
            new_name='multiplier',
        ),
        migrations.RenameField(
            model_name='futurecontract',
            old_name='pricemag',
            new_name='price_magnifier',
        ),
        migrations.RenameField(
            model_name='futurecontract',
            old_name='type',
            new_name='sec_type',
        ),
        migrations.RemoveField(
            model_name='futurecontract',
            name='locsym',
        ),
        migrations.RemoveField(
            model_name='futurecontract',
            name='month',
        ),
        migrations.RemoveField(
            model_name='futurecontract',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='futurecontract',
            name='year',
        ),
        migrations.AddField(
            model_name='futurecontract',
            name='exchanges',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='futurecontract',
            name='fut_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='futurecontract',
            name='fut_year',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='futurecontract',
            name='local_symbol',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='futurecontract',
            name='timezone_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='futurecontract',
            name='base',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='futurecontract',
            name='lcode_long',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='futurecontract',
            name='liquid_hours',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='futurecontract',
            name='trading_hours',
            field=models.TextField(null=True),
        ),
    ]
