# Generated by Django 4.2.3 on 2023-09-18 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0027_rename_conid_futurecontract_con_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureContractIntra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('base', models.CharField(default='', max_length=10)),
                ('rate', models.FloatField(null=True)),
                ('rate_bid', models.FloatField(null=True)),
                ('rate_ask', models.FloatField(null=True)),
                ('future_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibkr.futurecontract')),
            ],
            options={
                'unique_together': {('future_contract',)},
            },
        ),
    ]
