# Generated by Django 4.2.3 on 2023-12-07 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0018_alter_currency_options_alter_fxpair_options'),
        ('ibkr', '0028_futurecontractintra'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedFxPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fxpair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.fxpair', unique=True)),
            ],
            options={
                'ordering': ['fxpair__base_currency', 'fxpair__quote_currency'],
            },
        ),
    ]
