# Generated by Django 4.2.3 on 2024-01-04 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_auto_20240105_0032'),
        ('ibkr', '0031_alter_supportedfxpair_fxpair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingrequest',
            name='broker_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_requests', to='broker.brokeraccount'),
        ),
        migrations.AlterField(
            model_name='ibkraccountsummary',
            name='broker_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_summaries', to='broker.brokeraccount'),
        ),
    ]
