# Generated by Django 4.2.11 on 2024-06-26 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', 'add_corpay_fees_20240513'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerUserInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, default='admin', max_length=255, null=True)),
                ('staging', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('default_exec_strat', models.TextField(default='MARKET')),
                ('default_hedge_strat', models.TextField(default='SELFDIRECTED')),
                ('default_algo', models.CharField(default='MARKET', max_length=255)),
                ('use_triggers', models.BooleanField(default=True)),
                ('rfq_type', models.CharField(choices=[('api', 'API'), ('manual', 'MANUAL'), ('unsupported', 'UNSUPPORTED'), ('indicative', 'INDICATIVE'), ('norfq', 'NORFQ')], default='unsupported', max_length=16)),
                ('min_order_size_buy', models.FloatField(default=0.01)),
                ('max_order_size_buy', models.FloatField(default=5000000.0)),
                ('min_order_size_sell', models.FloatField(default=0.01)),
                ('max_order_size_sell', models.FloatField(default=5000000.0)),
                ('max_daily_tickets', models.IntegerField(default=100)),
                ('unit_order_size_buy', models.FloatField(default=0.0)),
                ('unit_order_size_sell', models.FloatField(default=0.0)),
                ('broker_instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.brokerinstrument')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'company', 'broker_instrument')},
            },
        ),
        migrations.CreateModel(
            name='BrokerCompanyInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staging', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('default_exec_strat', models.TextField(default='MARKET')),
                ('default_hedge_strat', models.TextField(default='SELFDIRECTED')),
                ('default_algo', models.CharField(default='MARKET', max_length=255)),
                ('use_triggers', models.BooleanField(default=True)),
                ('rfq_type', models.CharField(choices=[('api', 'API'), ('manual', 'MANUAL'), ('unsupported', 'UNSUPPORTED'), ('indicative', 'INDICATIVE'), ('norfq', 'NORFQ')], default='unsupported', max_length=16)),
                ('min_order_size_buy', models.FloatField(default=0.01)),
                ('max_order_size_buy', models.FloatField(default=5000000.0)),
                ('min_order_size_sell', models.FloatField(default=0.01)),
                ('max_order_size_sell', models.FloatField(default=5000000.0)),
                ('max_daily_tickets', models.IntegerField(default=100)),
                ('unit_order_size_buy', models.FloatField(default=0.0)),
                ('unit_order_size_sell', models.FloatField(default=0.0)),
                ('broker_instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.brokerinstrument')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
            options={
                'unique_together': {('company', 'broker_instrument')},
            },
        ),
    ]
