# Generated by Django 4.2.11 on 2024-05-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', 'fix_corpay_fees_20240510'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyfee',
            name='broker_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='currencyfee',
            name='rev_share',
            field=models.FloatField(default=0.4),
        ),
    ]
