# Generated by Django 4.2.3 on 2024-01-04 14:48

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('account', '0090_broker_supported_instruments_brokersupportedspot_and_more'),
        ('currency', '0019_deliverytime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('broker_provider',
                 models.CharField(blank=True, choices=[('Corpay', 'Corpay'), ('IBKR', 'IBKR')], max_length=50)),
                ('execution_method',
                 models.CharField(choices=[('asynchronous', 'Asynchronous'), ('synchronous', 'Synchronous')],
                                  max_length=50, null=True)),
                ('supported_instruments', multiselectfield.db.fields.MultiSelectField(blank=True,
                                                                                      choices=[('forward', 'Forward'),
                                                                                               ('future', 'Future'),
                                                                                               ('option', 'Option'),
                                                                                               ('spot', 'Spot')],
                                                                                      help_text='Supported instruments',
                                                                                      max_length=26, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerAccountCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('trade', 'Trade'), ('fund', 'Fund'), ('backtest', 'Backtest')],
                                          max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Broker Account Capabilities',
            },
        ),
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_account_name', models.CharField(max_length=255)),
                ('account_type', models.IntegerField(choices=[(1, 'Live'), (2, 'Paper')])),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='broker.broker')),
                ('capabilities', models.ManyToManyField(to='broker.brokeraccountcapability')),
                ('company',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_accounts',
                                   to='account.company')),
            ],
        ),
        migrations.CreateModel(
            name='BrokerSupportedSpotPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='broker.broker')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currency.fxpair')),
            ],
            options={
                'abstract': False,
                'unique_together': {('broker', 'pair')},
            },
        ),
        migrations.CreateModel(
            name='BrokerSupportedForwardPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='broker.broker')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currency.fxpair')),
            ],
            options={
                'abstract': False,
                'unique_together': {('broker', 'pair')},
            },
        )
    ]
