# Generated by Django 4.2.3 on 2024-01-05 00:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO broker_broker (
                id,
                name,
                execution_method,
                broker_provider,
                supported_instruments
            )
            SELECT
                id,
                name,
                execution_method,
                broker_provider,
                supported_instruments
            FROM
                account_broker;
            SELECT setval(pg_get_serial_sequence('"broker_broker"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "broker_broker";
        """, reverse_sql="""
            INSERT INTO account_broker(
                id,
                name,
                execution_method,
                broker_provider,
                supported_instruments
            )
            SELECT
                id,
                name,
                execution_method,
                broker_provider,
                supported_instruments
            FROM
                broker_broker;
            SELECT setval(pg_get_serial_sequence('"account_broker"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "account_broker";
        """),
        migrations.RunSQL("""
            INSERT INTO broker_brokeraccount (
                id,
                broker_account_name,
                account_type,
                broker_id,
                company_id
            )
            SELECT
                id,
                broker_account_name,
                account_type,
                broker_id,
                company_id
            FROM
                account_brokeraccount;
            SELECT setval(pg_get_serial_sequence('"broker_brokeraccount"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "broker_brokeraccount";
        """, reverse_sql="""
            INSERT INTO account_brokeraccount (
                id,
                broker_account_name,
                account_type,
                broker_id,
                company_id
            )
            SELECT
                id,
                broker_account_name,
                account_type,
                broker_id,
                company_id
            FROM
                broker_brokeraccount;
            SELECT setval(pg_get_serial_sequence('"account_brokeraccount"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "account_brokeraccount";
        """),
        migrations.RunSQL("""
            INSERT INTO broker_brokeraccountcapability (
                id,
                type
            )
            SELECT
                id,
                type
            FROM
                account_brokeraccountcapability;
            SELECT setval(pg_get_serial_sequence('"broker_brokeraccountcapability"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "broker_brokeraccountcapability";
        """, reverse_sql="""
            INSERT INTO account_brokeraccountcapability (
                id,
                type
            )
            SELECT
                id,
                type
            FROM
                broker_brokeraccountcapability;
            SELECT setval(pg_get_serial_sequence('"account_brokeraccountcapability"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "account_brokeraccountcapability";
        """),
        migrations.RunSQL("""
            INSERT INTO broker_brokeraccount_capabilities (
                id,
                brokeraccount_id,
                brokeraccountcapability_id
            )
            SELECT
                id,
                brokeraccount_id,
                brokeraccountcapability_id
            FROM
                account_brokeraccount_capabilities;
            SELECT setval(pg_get_serial_sequence('"broker_brokeraccount_capabilities"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "broker_brokeraccount_capabilities";
        """, reverse_sql="""
            INSERT INTO account_brokeraccount_capabilities (
                id,
                brokeraccount_id,
                brokeraccountcapability_id
            )
            SELECT
                id,
                brokeraccount_id,
                brokeraccountcapability_id
            FROM
                broker_brokeraccount_capabilities;
            SELECT setval(pg_get_serial_sequence('"account_brokeraccount_capabilities"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "account_brokeraccount_capabilities";
        """)
    ]
