# Generated by Django 4.2.11 on 2024-06-05 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0112_remove_user_accounts'),
        ('broker', '0002_auto_20240530_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokercompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
    ]
