# Generated by Django 4.2.10 on 2024-02-27 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0019_deliverytime'),
        ('broker', '0003_alter_brokersupportedspotpair_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_fees', to='broker.broker')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency')),
            ],
            options={
                'verbose_name': 'Broker Fees',
                'ordering': ['currency__mnemonic'],
                'unique_together': {('broker', 'currency')},
            },
        ),
    ]
