# Generated by Django 4.2.11 on 2024-05-06 18:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_alter_broker_supported_instruments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='api_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('rest', 'rest'), ('fix', 'fix'), ('websocket', 'websocket'), ('python_sdk_sync', 'python_sdk_sync'), ('python_sdk_async', 'python_sdk_async'), ('manual', 'manual')], help_text='Supported api types', max_length=58, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='supported_execution_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('rfq', 'rfq'), ('quote_lock', 'quote_lock'), ('limit', 'limit'), ('market', 'market'), ('twap', 'twap'), ('vwap', 'vwap'), ('voice', 'voice'), ('algo', 'algo')], help_text='Supported execution types', max_length=48, null=True),
        ),
    ]
