# Generated by Django 4.2.11 on 2024-07-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_alter_brokercompany_company'),
        ('broker', '002_add_company_perms'),
    ]

    operations = [
    ]
