# Generated by Django 4.2.10 on 2024-02-27 23:21

from django.db import migrations

import csv
from io import StringIO

content = """
Currency,Pangea Rate
AED,0.50%
ALL,1.00%
AMD,1.00%
ANG,1.00%
AOA,1.00%
ARS,0.70%
AUD,0.50%
AWG,1.00%
AZN,1.00%
BAM,1.00%
BBD,1.00%
BDT,0.70%
BGN,0.60%
BHD,1.00%
BIF,1.00%
BMD,1.00%
BND,1.00%
BOB,0.80%
BRL,0.80%
BSD,1.00%
BTN,1.00%
BWP,1.00%
BZD,0.80%
CAD,0.50%
CHF,0.50%
CLP,0.80%
CNH,0.70%
CNY,0.70%
COP,0.80%
CRC,0.80%
CVE,1.00%
CZK,0.60%
DJF,1.00%
DKK,0.50%
DOP,0.80%
DZD,1.00%
EGP,0.80%
ERN,1.00%
ETB,0.90%
EUR,0.50%
FKP,1.00%
GBP,0.50%
GEL,0.80%
GHS,0.80%
GIP,1.00%
GMD,1.00%
GNF,1.00%
GTQ,0.80%
GYD,1.00%
HKD,0.50%
HNL,0.80%
HTG,1.00%
HUF,0.60%
IDR,0.60%
ILS,0.60%
INR,0.50%
ISK,0.60%
JMD,1.00%
JOD,1.00%
JPY,0.50%
KES,0.80%
KGS,1.00%
KHR,0.80%
KMF,1.00%
KRW,0.60%
KWD,0.60%
KYD,1.00%
KZT,1.00%
LAK,0.80%
LKR,0.70%
LRD,1.00%
LSL,1.00%
LTL,1.00%
MAD,1.00%
MDL,0.80%
MGA,0.90%
MKD,1.00%
MNT,1.00%
MOP,1.00%
MRU,1.00%
MUR,1.00%
MVR,1.00%
MWK,0.90%
MXN,0.50%
MYR,0.60%
MZN,0.90%
NAD,1.00%
NGN,0.90%
NIO,1.00%
NOK,0.50%
NPR,0.80%
NZD,0.50%
OMR,1.00%
PAB,0.80%
PEN,0.80%
PGK,1.00%
PHP,0.60%
PKR,0.70%
PLN,0.60%
PYG,1.00%
QAR,1.00%
RON,0.60%
RSD,0.80%
RWF,0.90%
SAR,1.00%
SBD,1.00%
SCR,1.00%
SEK,0.50%
SGD,0.50%
SLL,1.00%
SRD,1.00%
STN,1.00%
SZL,1.00%
THB,0.60%
TJS,1.00%
TMT,1.00%
TND,1.00%
TOP,1.00%
TRY,0.80%
TTD,1.00%
TWD,0.50%
TZS,0.90%
UGX,0.80%
UYU,0.80%
UZS,1.00%
VND,0.80%
VUV,1.00%
WST,1.00%
XAF,0.90%
XOF,0.90%
XPF,1.00%
ZAR,0.70%
ZMW,0.90%
USD,0.0
"""


def create_fees(app, *_, **__):
    Broker = app.get_model('broker', 'Broker')
    Currency = app.get_model('currency', 'Currency')
    Fee = app.get_model('broker', 'CurrencyFee')

    reader = csv.DictReader(StringIO(content.strip()), dialect='excel')
    broker = Broker.objects.get(name='Corpay')
    if broker is None:
        return

    for row in reader:
        currency = Currency.objects.filter(mnemonic=row['Currency']).first()
        if not currency:  # Ignore missing currency
            continue
        cost_str = row['Pangea Rate'].replace('%', '')
        cost = round(float(cost_str)/100, 3)
        Fee.objects.create(broker=broker, currency=currency, cost=cost)


class Migration(migrations.Migration):
    dependencies = [
        ('broker', '0004_currencyfee'),
    ]

    operations = [
        migrations.RunPython(create_fees)
    ]
