# Generated by Django 4.2.11 on 2024-05-07 02:48

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0036_alter_instrument_instrument_type'),
        ('broker', '0004_alter_broker_api_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('buy', models.BooleanField(default=False)),
                ('sell', models.BooleanField(default=False)),
                ('buy_wallet', models.BooleanField(default=False)),
                ('sell_wallet', models.BooleanField(default=False)),
                ('buy_cost', models.FloatField(blank=True, null=True)),
                ('buy_cost_unit', models.CharField(blank=True, choices=[('pct', 'pct'), ('usd', 'usd'), ('local', 'local')], null=True)),
                ('sell_cost', models.FloatField(blank=True, null=True)),
                ('sell_cost_unit', models.CharField(blank=True, choices=[('pct', 'pct'), ('usd', 'usd'), ('local', 'local')], null=True)),
                ('buy_fee', models.FloatField(blank=True, null=True)),
                ('buy_fee_unit', models.CharField(blank=True, choices=[('pct', 'pct'), ('usd', 'usd'), ('local', 'local')], null=True)),
                ('sell_fee', models.FloatField(blank=True, null=True)),
                ('sell_fee_unit', models.CharField(blank=True, choices=[('pct', 'pct'), ('usd', 'usd'), ('local', 'local')], null=True)),
                ('delivery_sla', models.IntegerField()),
                ('cutoff_time', models.TimeField()),
                ('funding_models', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('prefunded', 'prefunded'), ('postfunded', 'postfunded'), ('premargined', 'premargined'), ('postmargined', 'postmargined'), ('flexible', 'flexible')], help_text='Supported funding models', max_length=54, null=True)),
                ('execution_types', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('rfq', 'rfq'), ('quote_lock', 'quote_lock'), ('limit', 'limit'), ('market', 'market'), ('twap', 'twap'), ('vwap', 'vwap'), ('voice', 'voice'), ('algo', 'algo')], help_text='Supported execution types', max_length=48, null=True)),
                ('api_types', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('rest', 'rest'), ('fix', 'fix'), ('websocket', 'websocket'), ('python_sdk_sync', 'python_sdk_sync'), ('python_sdk_async', 'python_sdk_async'), ('manual', 'manual')], help_text='Supported api types', max_length=58, null=True)),
                ('wire_fee', models.FloatField(blank=True, null=True)),
                ('wire_fee_unit', models.CharField(blank=True, choices=[('pct', 'pct'), ('usd', 'usd'), ('local', 'local')], null=True)),
                ('custom', models.JSONField(blank=True, help_text='Custom Information.', null=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.broker')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketdata.instrument')),
            ],
            options={
                'unique_together': {('broker', 'instrument')},
            },
        ),
    ]
