# Generated by Django 4.2.11 on 2024-07-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_merge_20240702_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokercompanyinstrument',
            name='default_exec_strat',
            field=models.CharField(default='MARKET', max_length=255),
        ),
        migrations.AlterField(
            model_name='brokercompanyinstrument',
            name='default_hedge_strat',
            field=models.CharField(default='SELFDIRECTED', max_length=255),
        ),
        migrations.AlterField(
            model_name='brokeruserinstrument',
            name='default_exec_strat',
            field=models.CharField(default='MARKET', max_length=255),
        ),
        migrations.AlterField(
            model_name='brokeruserinstrument',
            name='default_hedge_strat',
            field=models.CharField(default='SELFDIRECTED', max_length=255),
        ),
    ]
