# Generated by Django 4.2.11 on 2024-05-01 16:08

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0005_auto_20240227_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='api_config',
            field=models.JSONField(blank=True, help_text='API config.', null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='api_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('rest', 'rest'), ('fix', 'fix'), ('websocket', 'websocket'), ('python_sync', 'python_sync'), ('python_async', 'python_async')], help_text='Supported api types', max_length=43, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='funding_models',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('prefunded', 'prefunded'), ('postfunded', 'postfunded'), ('premargined', 'premargined'), ('postmargined', 'postmargined'), ('flexible', 'flexible')], help_text='Supported funding models', max_length=54, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='maximum_rfq_expiry',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='minimum_rfq_expiry',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='supported_execution_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('rfq', 'rfq'), ('quote_lock', 'quote_lock'), ('limit', 'limit'), ('market', 'market'), ('twap', 'twap'), ('vwap', 'vwap')], help_text='Supported execution types', max_length=37, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='broker_provider',
            field=models.CharField(blank=True, choices=[('Corpay', 'Corpay'), ('IBKR', 'IBKR'), ('CORPAY_MP', 'Corpay MP'), ('VERTO', 'VERTO'), ('NIUM', 'NIUM'), ('AZA', 'AZA'), ('MONEX', 'MONEX'), ('CONVERA', 'CONVERA'), ('OFX', 'OFX'), ('XE', 'XE'), ('OANDA', 'OANDA'), ('AIRWALLEX', 'AIRWALLEX')], max_length=50),
        ),
        migrations.AlterField(
            model_name='broker',
            name='supported_instruments',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('forward', 'Forward'), ('future', 'Future'), ('option', 'Option'), ('spot', 'Spot'), ('window_forward', 'window_forward'), ('ndf', 'Ndf'), ('swap', 'Swap'), ('nds', 'Nds'), ('rtp', 'RTP')], help_text='Supported instrument', max_length=58, null=True),
        ),
    ]
