# Generated by Django 4.2.11 on 2024-05-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0005_brokerinstrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerinstrument',
            name='base_ccy',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brokerinstrument',
            name='counter_ccy',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brokerinstrument',
            name='buy_cost_unit',
            field=models.CharField(blank=True, choices=[('bps', 'bps'), ('pct', 'pct'), ('usd', 'usd'), ('local', 'local')], null=True),
        ),
        migrations.AlterField(
            model_name='brokerinstrument',
            name='buy_fee_unit',
            field=models.CharField(blank=True, choices=[('bps', 'bps'), ('pct', 'pct'), ('usd', 'usd'), ('local', 'local')], null=True),
        ),
        migrations.AlterField(
            model_name='brokerinstrument',
            name='sell_cost_unit',
            field=models.CharField(blank=True, choices=[('bps', 'bps'), ('pct', 'pct'), ('usd', 'usd'), ('local', 'local')], null=True),
        ),
        migrations.AlterField(
            model_name='brokerinstrument',
            name='sell_fee_unit',
            field=models.CharField(blank=True, choices=[('bps', 'bps'), ('pct', 'pct'), ('usd', 'usd'), ('local', 'local')], null=True),
        ),
        migrations.AlterField(
            model_name='brokerinstrument',
            name='wire_fee_unit',
            field=models.CharField(blank=True, choices=[('bps', 'bps'), ('pct', 'pct'), ('usd', 'usd'), ('local', 'local')], null=True),
        ),
    ]
