# Generated by Django 4.2.11 on 2024-05-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0006_brokerinstrument_base_ccy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerinstrument',
            name='cutoff_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brokerinstrument',
            name='delivery_sla',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
