# Generated by Django 4.2.11 on 2024-05-01 16:57

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0006_broker_api_config_broker_api_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='contact_email',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='contact_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='domicile',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='api_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('rest', 'rest'), ('fix', 'fix'), ('websocket', 'websocket'), ('python_sdk_sync', 'python_sdk_sync'), ('python_sdk_async', 'python_sdk_async')], help_text='Supported api types', max_length=51, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='broker_provider',
            field=models.CharField(blank=True, choices=[('Corpay', 'Corpay'), ('IBKR', 'IBKR'), ('CORPAY_MP', 'CORPAY_MP'), ('VERTO', 'VERTO'), ('NIUM', 'NIUM'), ('AZA', 'AZA'), ('MONEX', 'MONEX'), ('CONVERA', 'CONVERA'), ('OFX', 'OFX'), ('XE', 'XE'), ('OANDA', 'OANDA'), ('AIRWALLEX', 'AIRWALLEX')], max_length=50),
        ),
        migrations.AlterField(
            model_name='broker',
            name='supported_instruments',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('forward', 'Forward'), ('future', 'Future'), ('option', 'Option'), ('spot', 'Spot'), ('window_forward', 'window_forward'), ('ndf', 'Ndf'), ('swap', 'Swap'), ('nds', 'Nds'), ('rtp', 'RTP'), ('continuous_spot', 'continuous_spot')], help_text='Supported instrument', max_length=74, null=True),
        ),
    ]
