# Generated by Django 4.2.11 on 2024-07-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '008_populate_monex_instruments'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokercompanyinstrument',
            name='max_tenor_months',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='brokeruserinstrument',
            name='max_tenor_months',
            field=models.IntegerField(default=12),
        ),
    ]
