# Generated by Django 4.2.11 on 2024-07-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0009_brokercompanyinstrument_max_tenor_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokercompany',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
