# Generated by Django 4.2.11 on 2024-07-18 07:27

from django.db import migrations


def enable_broker_company(apps, schema_editor):
    BrokerCompany = apps.get_model('broker', 'BrokerCompany')
    for broker_company in BrokerCompany.objects.all():
        broker_company.enabled = True
        broker_company.save()


class Migration(migrations.Migration):
    dependencies = [
        ('broker', '0010_brokercompany_enabled'),
    ]

    operations = [
        migrations.RunPython(enable_broker_company)
    ]
