# Generated by Django 4.2.15 on 2024-08-23 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0027_convert_ccys'),
        ('broker', '0011_auto_20240718_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_type', models.CharField(choices=[('spot', 'Spot'), ('forward', 'Forward')], max_length=50)),
                ('broker_markup', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_cny_broker_config_template', to='currency.currency')),
                ('preferred_broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.broker')),
                ('sell_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_cny_broker_config_template', to='currency.currency')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationTemplateBroker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.BooleanField(default=False)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.broker')),
                ('configuration_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.configurationtemplate')),
            ],
        ),
    ]
