# Generated by Django 4.2.15 on 2024-08-24 06:43

from django.db import migrations

from main.apps.broker.configurations.configuraiton_templates import BROKER_CONFIGURATION_TEMPLATES


def seed_broker_template_configuration(apps, schema_editor):
    ConfigurationTemplate = apps.get_model('broker', 'ConfigurationTemplate')
    ConfigurationTemplateBroker = apps.get_model('broker', 'ConfigurationTemplateBroker')
    Broker = apps.get_model('broker', 'Broker')
    Currency = apps.get_model('currency', 'Currency')
    for template_data in BROKER_CONFIGURATION_TEMPLATES:
        sell_currency = Currency.objects.get(mnemonic=template_data['sell_currency'])
        buy_currency = Currency.objects.get(mnemonic=template_data['buy_currency'])
        preferred_broker = Broker.objects.get(broker_provider=template_data['preferred_broker'])

        configuration_template, created = ConfigurationTemplate.objects.get_or_create(
            id=template_data['id'],
            sell_currency=sell_currency,
            buy_currency=buy_currency,
            instrument_type=template_data['instrument_type'],
            defaults={
                "broker_markup": template_data['broker_markup'],
                "preferred_broker": preferred_broker
            }
        )
        for broker_data in template_data['brokers']:
            broker = Broker.objects.get(broker_provider=broker_data['broker'])
            ConfigurationTemplateBroker.objects.get_or_create(
                configuration_template=configuration_template,
                broker=broker,
                api=broker_data['api']
            )



class Migration(migrations.Migration):
    dependencies = [
        ('broker', '0012_configurationtemplate_configurationtemplatebroker'),
        ('currency', '0028_auto_20240823_2359')
    ]

    operations = [
        migrations.RunPython(seed_broker_template_configuration),
    ]
