# Generated by Django 4.2.15 on 2024-08-25 08:02

from django.db import migrations


def add_missing_broker_instruments(apps, schema_editor):
    spot_instruments = [
        'CADUGX',
        'USDETB',
        'USDMWK',
        'USDTZS',
        'USDXOF'
    ]
    fwd_instruments = [
        'CADUGX'
    ]
    Instrument = apps.get_model('marketdata', 'Instrument')
    Broker = apps.get_model('broker', 'Broker')
    BrokerInstrument = apps.get_model('broker', 'BrokerInstrument')
    monex = Broker.objects.get(broker_provider="MONEX")
    corpay = Broker.objects.get(broker_provider="CORPAY")
    brokers = [
        monex,
        corpay
    ]
    for spot_instrument in spot_instruments:
        instrument = Instrument.objects.get(name=f"{spot_instrument}-SPOT")
        for broker in brokers:
            BrokerInstrument.objects.get_or_create(
                broker=broker,
                instrument=instrument,
                base_ccy=spot_instrument[:3],
                counter_ccy=spot_instrument[3:],
                defaults={
                    "active": True,
                    "buy": True,
                    "sell": True,
                    "buy_wallet": True,
                    "sell_wallet": True,
                    "buy_cost": 0.6,
                    "buy_cost_unit": 'pct',
                    "sell_cost": 0.6,
                    "sell_cost_unit": 'pct',
                    "buy_fee": 0.2,
                    "buy_fee_unit": 'pct',
                    "sell_fee": 0.2,
                    "sell_fee_unit": 'pct',
                    "funding_models": ['postfunded'],
                    "execution_types": ['voice'],
                    "api_types": ['manual'],
                    "wire_fee": 0.0,
                    "wire_fee_unit": 'usd'
                }

            )
    for fwd_instrument in fwd_instruments:
        instrument = Instrument.objects.get(name=f"{fwd_instrument}-FWD")
        for broker in brokers:
            BrokerInstrument.objects.get_or_create(
                broker=broker,
                instrument=instrument,
                base_ccy=fwd_instrument[:3],
                counter_ccy=fwd_instrument[3:],
                defaults={
                    "active": True,
                    "buy": True,
                    "sell": True,
                    "buy_wallet": True,
                    "sell_wallet": True,
                    "buy_cost": 0.6,
                    "buy_cost_unit": 'pct',
                    "sell_cost": 0.6,
                    "sell_cost_unit": 'pct',
                    "buy_fee": 0.2,
                    "buy_fee_unit": 'pct',
                    "sell_fee": 0.2,
                    "sell_fee_unit": 'pct',
                    "funding_models": ['postfunded'],
                    "execution_types": ['voice'],
                    "api_types": ['manual'],
                    "wire_fee": 0.0,
                    "wire_fee_unit": 'usd'
                }

            )


class Migration(migrations.Migration):
    dependencies = [
        ('broker', '0013_auto_20240824_0643'),
        ('marketdata', '0044_auto_20240825_0752')
    ]

    operations = [
        migrations.RunPython(add_missing_broker_instruments)
    ]
