# Generated by Django 4.2.15 on 2024-08-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0014_auto_20240825_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationtemplate',
            name='instrument_type',
            field=models.CharField(choices=[('spot', 'Spot'), ('forward', 'Forward'), ('ndf', 'NDF')], max_length=50),
        ),
    ]
