# Generated by Django 4.2.15 on 2024-09-19 13:26

from django.db import migrations

from django.apps.registry import Apps

from main.apps.marketdata.models.ref.instrument import InstrumentTypes


def populate_fee_template_data(apps: Apps, schema_editor):
    ConfigTemplate = apps.get_model('broker', 'ConfigurationTemplate')
    FeeTemplate = apps.get_model('broker', 'FeeTemplate')

    templates = ConfigTemplate.objects.all()
    for item in templates:
        fee_temp, create = FeeTemplate.objects.update_or_create(
            sell_currency=item.sell_currency,
            buy_currency=item.buy_currency,
            instrument_type=item.instrument_type,
            broker_markup=item.broker_markup
        )

def re_populate_config_template_fee(apps: Apps, schema_editor):
    ConfigTemplate = apps.get_model('broker', 'ConfigurationTemplate')
    FeeTemplate = apps.get_model('broker', 'FeeTemplate')

    templates = FeeTemplate.objects.all()
    for item in templates:
        try:
            config_temp = ConfigTemplate.objects.get(
                sell_currency=item.sell_currency,
                buy_currency=item.buy_currency,
                instrument_type=item.instrument_type
            )

            config_temp.broker_markup = item.broker_markup
            config_temp.save()
        except Exception as e:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0016_alter_configurationtemplate_broker_markup_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_fee_template_data, re_populate_config_template_fee)
    ]
