# Generated by Django 4.2.15 on 2024-09-19 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0017_populate_fee_template_data_from_config_template_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationtemplate',
            name='broker_markup',
        ),
    ]
