# Generated by Django 4.2.15 on 2024-09-24 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0114_company_postal_company_region'),
        ('currency', '0029_auto_20240825_0646'),
        ('broker', '0020_alter_currencyfee_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerFeeCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_type', models.CharField(choices=[('fxrate', 'FxRate'), ('forward', 'Forward'), ('future', 'Future'), ('base_future', 'BaseFuture'), ('continuous_future', 'ContinuousFuture'), ('cash_equity', 'CashEquity'), ('option', 'Option'), ('spot', 'Spot'), ('window_forward', 'Window Forward'), ('ndf', 'Ndf'), ('swap', 'Swap'), ('nds', 'Nds'), ('rtp', 'Realtime Payment'), ('continuous_spot', 'Continuous Spot'), ('currency', 'Currency')], max_length=50, null=True)),
                ('broker_cost', models.FloatField(default=0.0)),
                ('broker_fee', models.FloatField(default=0.0)),
                ('pangea_fee', models.FloatField(default=0.0)),
                ('rev_share', models.FloatField(default=0.0)),
                ('wire_fee', models.FloatField(default=0.0)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.broker')),
                ('buy_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_fee_company_buy_currency', to='currency.currency')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('sell_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_fee_company_sell_currency', to='currency.currency')),
            ],
            options={
                'unique_together': {('broker', 'buy_currency', 'sell_currency', 'instrument_type', 'company')},
            },
        ),
    ]
