# Generated by Django 4.2.15 on 2024-10-01 18:00

from django.db import migrations
from django.db import connection


def update_pk_sequence(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT setval(pg_get_serial_sequence('"broker_configurationtemplate"', 'id'), 46, false);
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0021_brokerfeecompany'),
    ]

    operations = [
        migrations.RunPython(update_pk_sequence),
    ]
