# Generated by Django 4.2.15 on 2024-10-11 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0029_auto_20240825_0646'),
        ('broker', '0023_auto_20241002_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTime',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('currency.deliverytime',),
        ),
    ]
