# Generated by Django 4.2.15 on 2024-11-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0026_add_sle_and_rwf_broker_instrument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverytime',
            options={'verbose_name': 'Bank Country Session', 'verbose_name_plural': 'Bank Country Sessions'},
        ),
    ]
