# Generated by Django 4.2.15 on 2024-11-07 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0027_alter_deliverytime_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerTradingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_country', models.CharField(max_length=255)),
                ('session_open_utc', models.TimeField(help_text='Trading session open time in UTC')),
                ('session_close_utc', models.TimeField(help_text='Trading session close time in UTC')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.broker')),
            ],
            options={
                'verbose_name': 'Broker Trading Session',
                'verbose_name_plural': 'Broker Trading Sessions',
            },
        ),
    ]
