# Generated by Django 4.2.15 on 2024-11-11 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0029_add_cad_ghs_broker_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerinstrument',
            name='cutoff_time',
            field=models.TimeField(default=datetime.time(21, 0), help_text='Cutoff time format hh:mm', verbose_name='Cutoff time in UTC'),
        ),
        migrations.AlterField(
            model_name='brokerinstrument',
            name='delivery_sla',
            field=models.FloatField(default=0, help_text='Delivery SLA in hours. e.g 0.5 for 30 minutes or 48 for 2 days', verbose_name='Delivery SLA in hours'),
        ),
    ]
