# Generated by Django 4.2.11 on 2024-06-05 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0112_remove_user_accounts'),
        ('nium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niumsettings',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
    ]
