# Generated by Django 4.2.11 on 2024-06-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nium', '0002_alter_niumsettings_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='niumsettings',
            name='api_key',
        ),
        migrations.AlterField(
            model_name='niumsettings',
            name='customer_hash_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
