# Generated by Django 4.2.11 on 2024-04-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0002_sample_data_for_feed_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed", name="enabled", field=models.BooleanField(default=False),
        ),
    ]
