# Generated by Django 4.2.11 on 2024-04-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0003_feed_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="collector_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="feed",
            name="fwd_point_src",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="feed",
            name="tag",
            field=models.CharField(
                blank=True, editable=False, max_length=512, null=True
            ),
        ),
        migrations.AddField(
            model_name="feed",
            name="type_feed",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="feed",
            name="value_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
