# Generated by Django 4.2.11 on 2024-04-17 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0004_feed_collector_name_feed_fwd_point_src_feed_tag_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feed", old_name="type_feed", new_name="feed_type",
        ),
    ]
