# Generated by Django 4.2.15 on 2024-10-09 09:28

from django.db import migrations
from django.db import connection


def drop_fee_app_tables(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute('''DROP TABLE IF EXISTS fee_feed, fee_feedinstrument''')


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_remove_feed_ask_markup_remove_feed_bid_markup_and_more'),
    ]

    operations = [
        migrations.RunPython(drop_fee_app_tables, migrations.RunPython.noop)
    ]
