# Generated by Django 4.2.3 on 2023-10-01 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hedge", "0046_remove_draftfxforwardposition_delivery_time_and_more"),
        ("account", "0079_account_strategy_parachutecashflow_parachutedata"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForwardSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("settlement_time", models.DateTimeField()),
                ("amount_unwound", models.FloatField(default=0.0)),
                ("amount_remaining", models.FloatField(default=0.0)),
                ("unwind_fx_rate", models.FloatField(default=0.0)),
                (
                    "parent_forward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hedge.fxforwardposition",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Company FX Positions",
                "unique_together": {("parent_forward", "settlement_time")},
            },
        ),
        migrations.CreateModel(
            name="CashflowRolloff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rolloff_time", models.DateTimeField()),
                ("amount", models.FloatField(default=0.0)),
                ("final_rate", models.FloatField(default=0.0)),
                (
                    "parent_cashflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.cashflow",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Company FX Positions",
                "unique_together": {("parent_cashflow", "rolloff_time")},
            },
        ),
    ]
