# Generated by Django 4.2.3 on 2024-01-18 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cashflowrolloff",
            options={"verbose_name_plural": "Cashflow Rolloffs"},
        ),
        migrations.AlterUniqueTogether(
            name="cashflowrolloff",
            unique_together=set(),
        ),
    ]
