# Generated by Django 4.2.7 on 2024-02-20 18:30

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0019_deliverytime'),
        ('account', '0102_remove_hedgingstrategy_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HedgingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('draft', 'DRAFT'), ('pending', 'PENDING'), ('approved', 'APPROVED'), ('live', 'LIVE'), ('canceled', 'CANCELED')], default='draft', help_text='The status of the strategy', max_length=24)),
                ('name', models.CharField(help_text='A name for the strategy', max_length=255, null=True)),
                ('description', models.TextField(help_text='A description of the strategy', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_strategies', to='account.company')),
                ('currency', models.ForeignKey(help_text='The currency of the strategy', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_currency', to='currency.currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutopilotHedgingStrategy',
            fields=[
                ('hedgingstrategy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='strategy.hedgingstrategy')),
                ('risk_reduction', models.FloatField(help_text='The amount of the strategy')),
                ('upper_bound', models.FloatField(help_text='The upper bound for the strategy used to define a take-profilt bound', null=True)),
                ('lower_bound', models.FloatField(help_text='The lower bound for the strategy used to define a stop loss bound', null=True)),
            ],
            options={
                'verbose_name': 'Autopilot Hedging Strategy',
                'verbose_name_plural': 'Autopilot Hedging Strategies',
            },
            bases=('strategy.hedgingstrategy',),
        ),
        migrations.CreateModel(
            name='ParachuteHedgingStrategy',
            fields=[
                ('hedgingstrategy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='strategy.hedgingstrategy')),
                ('lower_limit', models.FloatField(help_text='The value that the account value should not drop below')),
                ('lower_p', models.FloatField(default=0.95, help_text='The probability of breaching the lower limit')),
                ('upper_p', models.FloatField(default=0.99, help_text='The probability that is adjusted to')),
                ('lock_lower_limit', models.BooleanField(default=False, help_text='If true, the first time the account value is in p-danger of breaching the lower limit, a full hedge will be put on. If false, we just hedge back to upper-p, as usual.')),
            ],
            options={
                'verbose_name': 'Parachute Hedging Strategy',
                'verbose_name_plural': 'Parachute Hedging Strategies',
            },
            bases=('strategy.hedgingstrategy',),
        ),
        migrations.CreateModel(
            name='ZeroGravityHedgingStrategy',
            fields=[
                ('hedgingstrategy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='strategy.hedgingstrategy')),
                ('margin_budget', models.FloatField(default=20000000000.0, help_text='The margin budget for the strategy')),
                ('method', models.CharField(default='MIN_VAR', help_text='The method used to calculate the strategy', max_length=255)),
                ('max_horizon_days', models.IntegerField(default=7300, help_text='The maximum horizon days for the strategy')),
                ('vol_target_reduction', models.FloatField(help_text='The vol target reduction for the strategy')),
                ('var_95_exposure_ratio', models.FloatField(help_text='The VaR 95 exposure ratio for the strategy', null=True)),
                ('var_95_exposure_window', models.IntegerField(help_text='The VaR 95 exposure window for the strategy', null=True)),
            ],
            options={
                'verbose_name': 'Zero Gravity Hedging Strategy',
                'verbose_name_plural': 'Zero Gravity Hedging Strategies',
            },
            bases=('strategy.hedgingstrategy',),
        ),
    ]
