# Generated by Django 4.2.10 on 2024-02-29 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_hedgingstrategy_polymorphic_ctype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfGuidedHedgingStrategy',
            fields=[
                ('hedgingstrategy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='strategy.hedgingstrategy')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('strategy.hedgingstrategy',),
        ),
    ]
