# Generated by Django 4.2.10 on 2024-03-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0004_rename_selfguidedhedgingstrategy_selfdirectedhedgingstrategy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hedgingstrategy',
            name='lock_side',
            field=models.CharField(blank=True, choices=[('from', 'From'), ('to', 'To')], max_length=4, null=True),
        ),
    ]
