# Generated by Django 4.2.10 on 2024-03-05 01:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0007_alter_hedgingstrategy_strategy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopilothedgingstrategy',
            name='lower_target',
            field=models.FloatField(blank=True, help_text='The lower target for the strategy used to define a stop-loss bound', null=True),
        ),
        migrations.AlterField(
            model_name='autopilothedgingstrategy',
            name='upper_target',
            field=models.FloatField(blank=True, help_text='The upper target for the strategy used to define a take-profit bound', null=True),
        ),
        migrations.AlterField(
            model_name='hedgingstrategy',
            name='strategy_id',
            field=models.UUIDField(default=uuid.UUID('0b50e99c-946f-4abb-8c64-778416b008a4'), editable=False),
        ),
    ]
