# Generated by Django 4.2.10 on 2024-03-05 02:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0019_deliverytime'),
        ('strategy', '0008_alter_autopilothedgingstrategy_lower_target_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hedgingstrategy',
            name='currency',
        ),
        migrations.AddField(
            model_name='hedgingstrategy',
            name='from_currency',
            field=models.ForeignKey(blank=True, help_text='The from currency of the strategy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_from_currency', to='currency.currency'),
        ),
        migrations.AddField(
            model_name='hedgingstrategy',
            name='to_currency',
            field=models.ForeignKey(blank=True, help_text='The to currency of the strategy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_to_currency', to='currency.currency'),
        ),
        migrations.AlterField(
            model_name='hedgingstrategy',
            name='strategy_id',
            field=models.UUIDField(default=uuid.UUID('1c356f4f-13e7-4a1b-bdaf-4c72e44df9ad'), editable=False),
        ),
    ]
