# Generated by Django 4.2.10 on 2024-03-06 01:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0009_remove_hedgingstrategy_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hedgingstrategy',
            name='strategy_id',
            field=models.UUIDField(default=uuid.UUID('d58f437b-b084-4d87-b4bf-285751c2a88f'), editable=False),
        ),
    ]
