# Generated by Django 4.2.11 on 2024-04-18 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0023_currency_populate_unit'),
        ('strategy', '0013_alter_hedgingstrategy_lock_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hedgingstrategy',
            name='lock_side',
            field=models.ForeignKey(blank=True, help_text='ISO 4217 Standard 3-Letter Currency Code used to indicate which amount you are defining the value of. The non-Lockside amount will be calculated.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lock_side', to='currency.currency'),
        ),
    ]
