FROM python:3.10-slim

############################
# Setup environmental variables
############################
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1


############################
# Install system libraries
############################
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libpq-dev apt-transport-https ca-certificates gnupg curl tini git libpangocairo-1.0-0 libpango-1.0-0 && \
    echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | \
    tee /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg && \
    apt-get update && apt-get install -y google-cloud-sdk && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

############################
# Install project libraries
############################
WORKDIR /tmp
COPY requirements requirements
COPY external external
RUN pip install \
    --disable-pip-version-check \
    --no-cache-dir \
    -r requirements/production.txt && \
    rm -rf /tmp/requirements && \
    rm -rf /tmp/external
