# Generated by Django 3.2.8 on 2023-08-08 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0008_add_fields_to_stabilityindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='sge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value_type', models.CharField(max_length=50)),
                ('value', models.FloatField(blank=True, null=True)),
                ('country_codes', models.CharField(max_length=250)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sges', to='currency.currency', to_field='mnemonic')),
            ],
        ),
    ]
