# Generated by Django 3.2.8 on 2022-06-24 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0019_remove_cashflow_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_time', models.DateTimeField()),
                ('realized_pnl', models.FloatField(default=0)),
                ('unrealized_pnl', models.FloatField(default=0)),
                ('total_cash_holding', models.FloatField(default=0)),
                ('excess_liquidity', models.FloatField(default=0)),
                ('total_maintainance_margin', models.FloatField(default=0)),
                ('total_asset_value', models.FloatField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
        migrations.CreateModel(
            name='AccountSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_time', models.DateTimeField()),
                ('change_in_realized_pnl', models.FloatField(default=0)),
                ('total_realized_pnl', models.FloatField(default=0)),
                ('unrealized_pnl', models.FloatField(default=0)),
                ('total_positions_value', models.FloatField(default=0)),
                ('cashflow_npv', models.FloatField(default=0)),
                ('cashflow_roll_off', models.FloatField(default=0)),
                ('cashflow_roll_on', models.FloatField(default=0)),
                ('total_cashflow_roll_off', models.FloatField(default=0)),
                ('daily_commission', models.FloatField(default=0)),
                ('total_commission', models.FloatField(default=0)),
                ('daily_trading', models.FloatField(default=0)),
                ('cumulative_unhedged_variance', models.FloatField(default=0)),
                ('cumulative_hedged_variance', models.FloatField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
            options={
                'verbose_name_plural': 'Account Snapshots',
                'unique_together': {('account', 'snapshot_time')},
            },
        ),
    ]
