# Generated by Django 3.2.8 on 2022-06-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsnapshot',
            name='hedged_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='accountsnapshot',
            name='unhedged_value',
            field=models.FloatField(default=0),
        ),
    ]
