# Generated by Django 3.2.8 on 2022-06-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20220624_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsnapshot',
            old_name='total_positions_value',
            new_name='directional_positions_value',
        ),
    ]
