# Generated by Django 3.2.8 on 2022-06-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_rename_total_positions_value_accountsnapshot_directional_positions_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsnapshot',
            name='change_in_npv',
            field=models.FloatField(default=0),
        ),
    ]
