# Generated by Django 3.2.8 on 2022-06-28 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_accountsnapshot_change_in_npv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsnapshot',
            old_name='total_commission',
            new_name='cashflow_fwd',
        ),
        migrations.AddField(
            model_name='accountsnapshot',
            name='cumulative_commission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='accountsnapshot',
            name='cumulative_roll_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='accountsnapshot',
            name='daily_roll_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='accountsnapshot',
            name='last_snapshot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last', to='history.accountsnapshot'),
        ),
        migrations.AddField(
            model_name='accountsnapshot',
            name='next_snapshot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='history.accountsnapshot'),
        ),
    ]
