# Generated by Django 3.2.8 on 2022-07-12 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_auto_20220628_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysnapshot',
            name='daily_roll_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='companysnapshot',
            name='last_snapshot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last', to='history.companysnapshot'),
        ),
        migrations.AddField(
            model_name='companysnapshot',
            name='next_snapshot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='history.companysnapshot'),
        ),
    ]
