# Generated by Django 3.2.8 on 2022-07-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_auto_20220712_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsnapshot',
            name='margin',
            field=models.FloatField(default=0),
        ),
    ]
