# Generated by Django 3.2.8 on 2022-08-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_accountsnapshot_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsnapshot',
            name='num_cashflows_rolled_off',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accountsnapshot',
            name='num_cashflows_rolled_on',
            field=models.IntegerField(default=0),
        ),
    ]
