# Generated by Django 3.2.8 on 2022-09-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_auto_20220816_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysnapshot',
            name='demo_position_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='companysnapshot',
            name='demo_unrealized_pnl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='companysnapshot',
            name='live_position_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='companysnapshot',
            name='live_unrealized_pnl',
            field=models.FloatField(default=0.0),
        ),
    ]
