# Generated by Django 3.2.8 on 2022-10-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0009_auto_20220913_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsnapshot',
            name='cashflow_abs_fwd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='companysnapshot',
            name='cashflow_abs_fwd',
            field=models.FloatField(default=0),
        ),
    ]
