# Generated by Django 3.2.8 on 2022-10-11 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0010_auto_20221011_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companysnapshot',
            old_name='total_maintainance_margin',
            new_name='total_maintenance_margin',
        ),
    ]
