# Generated by Django 3.2.8 on 2022-10-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0011_rename_total_maintainance_margin_companysnapshot_total_maintenance_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysnapshot',
            name='excess_liquidity',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='companysnapshot',
            name='total_asset_value',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='companysnapshot',
            name='total_cash_holding',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='companysnapshot',
            name='total_maintenance_margin',
            field=models.FloatField(default=None, null=True),
        ),
    ]
