# Generated by Django 3.2.8 on 2022-10-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0012_auto_20221011_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsnapshot',
            name='num_cashflows_in_window',
            field=models.IntegerField(default=0),
        ),
    ]
