# Generated by Django 3.2.8 on 2022-10-27 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_auto_20221019_2204'),
        ('currency', '0002_auto_20220702_1908'),
        ('history', '0014_auto_20221015_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_time', models.DateTimeField()),
                ('total_account_requested_change', models.FloatField(default=0.0)),
                ('absolute_sum_of_account_requests', models.FloatField(default=0.0)),
                ('absolute_sum_of_desired_account_positions', models.FloatField(default=0.0)),
                ('initial_amount', models.FloatField(default=0.0)),
                ('final_amount', models.FloatField(default=0.0)),
                ('amount_filled', models.FloatField(default=None, null=True)),
                ('commission', models.FloatField(default=None, null=True)),
                ('cntr_commission', models.FloatField(default=None, null=True)),
                ('average_price', models.FloatField(default=None, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('fx_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.fxpair')),
            ],
            options={
                'unique_together': {('reference_time', 'fx_pair', 'company')},
            },
        ),
    ]
