# Generated by Django 3.2.8 on 2022-12-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0017_auto_20221207_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsnapshot',
            old_name='cumulative_hedged_variance',
            new_name='daily_hedged_variance',
        ),
        migrations.RenameField(
            model_name='accountsnapshot',
            old_name='cumulative_unhedged_variance',
            new_name='daily_unhedged_variance',
        ),
    ]
