# Generated by Django 3.2.8 on 2023-01-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0018_auto_20221211_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsnapshot',
            name='cashflow_abs_npv',
            field=models.FloatField(default=0),
        ),
    ]
