# Generated by Django 3.2.8 on 2023-01-16 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0020_auto_20230116_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='company',
        ),
    ]
