# Generated by Django 3.2.8 on 2023-01-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0019_accountsnapshot_cashflow_abs_npv'),
        ('history', '0022_populate_activites'),
    ]

    operations = [
    ]
