# Generated by Django 3.2.8 on 2023-02-21 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0023_merge_20230124_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsnapshot',
            old_name='change_in_realized_pnl',
            new_name='change_in_realized_pnl_fxspot',
        ),
        migrations.RenameField(
            model_name='accountsnapshot',
            old_name='unrealized_pnl',
            new_name='unrealized_pnl_fxspot',
        ),
    ]
