# Generated by Django 3.2.8 on 2023-02-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0024_auto_20230221_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsnapshot',
            name='change_in_realized_pnl_fxforward',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='accountsnapshot',
            name='unrealized_pnl_fxforward',
            field=models.FloatField(default=0),
        ),
    ]
