# Generated by Django 3.2.8 on 2023-04-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0025_auto_20230221_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsnapshot',
            name='cashflow_meddling_adjustment',
            field=models.FloatField(null=True),
        ),
    ]
