# Generated by Django 4.2.3 on 2024-01-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0026_accountsnapshot_cashflow_meddling_adjustment"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountsnapshot",
            name="fxforward_theta_approximate",
            field=models.FloatField(default=None, null=True),
        ),
    ]
