# Generated by Django 4.2.10 on 2024-03-16 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0027_accountsnapshot_fxforward_theta_approximate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSnapshotTemplateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_time', models.DateTimeField()),
                ('change_in_realized_pnl_fxspot', models.FloatField(default=0)),
                ('change_in_realized_pnl_fxforward', models.FloatField(default=0)),
                ('total_realized_pnl', models.FloatField(default=0)),
                ('unrealized_pnl_fxspot', models.FloatField(default=0)),
                ('unrealized_pnl_fxforward', models.FloatField(default=0)),
                ('fxforward_theta_approximate', models.FloatField(default=None, null=True)),
                ('directional_positions_value', models.FloatField(default=0)),
                ('cashflow_npv', models.FloatField(default=0)),
                ('cashflow_abs_npv', models.FloatField(default=0)),
                ('change_in_npv', models.FloatField(default=0)),
                ('cashflow_fwd', models.FloatField(default=0)),
                ('cashflow_abs_fwd', models.FloatField(default=0)),
                ('cashflow_roll_off', models.FloatField(default=0)),
                ('cashflow_roll_on', models.FloatField(default=0)),
                ('num_cashflows_rolled_off', models.IntegerField(default=0)),
                ('num_cashflows_rolled_on', models.IntegerField(default=0)),
                ('num_cashflows_in_window', models.IntegerField(default=0)),
                ('cashflow_meddling_adjustment', models.FloatField(null=True)),
                ('total_cashflow_roll_off', models.FloatField(default=0)),
                ('daily_commission', models.FloatField(default=0)),
                ('cumulative_commission', models.FloatField(default=0)),
                ('daily_roll_value', models.FloatField(default=0)),
                ('cumulative_roll_value', models.FloatField(default=0)),
                ('daily_trading', models.FloatField(default=0)),
                ('daily_unhedged_variance', models.FloatField(default=0)),
                ('daily_hedged_variance', models.FloatField(default=0)),
                ('unhedged_value', models.FloatField(default=0)),
                ('hedged_value', models.FloatField(default=0)),
                ('margin', models.FloatField(default=0)),
                ('template_name', models.CharField(max_length=100)),
                ('template_id', models.BigIntegerField()),
                ('template_uuid', models.SlugField(max_length=100)),
                ('template_source', models.CharField(max_length=11)),
                ('last_snapshot', models.BigIntegerField(null=True)),
                ('next_snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='history.accountsnapshottemplatedata')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
