# Generated by Django 4.2.10 on 2024-03-16 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0107_alter_company_estimated_aum'),
        ('history', '0028_accountsnapshottemplatedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySnapshotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.BigIntegerField()),
                ('template_uuid', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
    ]
