apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
    name: gcp-store-for-pangea-production
    namespace: pangea-production
spec:
    provider:
        gcpsm: # gcpsm provider
            projectID: pangea-production
            auth:
                secretRef:
                    secretAccessKeySecretRef:
                        name: gcpsm-secret-for-pangea-dashboard
                        key: secret-access-credentials
                        namespace: default
