apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
    name: gcp-store-for-pangea-production
spec:
    provider:
        gcpsm:
            projectID: pangea-production
            auth:
                workloadIdentity:
                    clusterLocation: us-central1
                    clusterName: pangea-production-autopilot-cluster
                    clusterProjectID: pangea-production
                    serviceAccountRef:
                        name: external-secrets
                        namespace: pangea-production
