apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: external-secret-for-pangea-production
    namespace: pangea-production
spec:
    refreshInterval: 1h             # rate SecretManager pulls GCPSM
    secretStoreRef:
        kind: ClusterSecretStore
        name: gcp-store-for-pangea-production
    target:
        name: external-secret-for-pangea-production
        creationPolicy: Owner
    data:
        -   secretKey: DB_PASSWORD
            remoteRef:
                key: secret-production-pangea-io-DB_PASSWORD
        -   secretKey: GPG_PASSPHRASE
            remoteRef:
                key: secret-production-pangea-io-GPG_PASSPHRASE
        -   secretKey: STRIPE_API_KEY
            remoteRef:
                key: secret-production-pangea-io-STRIPE_API_KEY
        -   secretKey: SENDGRID_API_KEY
            remoteRef:
                key: secret-production-pangea-io-SENDGRID_API_KEY
        -   secretKey: HUBSPOT_ACCESS_TOKEN
            remoteRef:
                key: secret-production-pangea-io-HUBSPOT_ACCESS_TOKEN
        -   secretKey: SLACK_NOTIFICATIONS_APP_BOT_TOKEN
            remoteRef:
                key: secret-production-pangea-io-SLACK_NOTIFICATIONS_APP_BOT_TOKEN
        -   secretKey: TWILIO_AUTH_TOKEN
            remoteRef:
                key: secret-production-pangea-io-TWILIO_AUTH_TOKEN
        -   secretKey: CORPAY_PARTNER_LEVEL_SIGNATURE
            remoteRef:
                key: secret-production-pangea-io-CORPAY_PARTNER_LEVEL_SIGNATURE
        -   secretKey: CORPAY_CLIENT_LEVEL_SIGNATURE
            remoteRef:
                key: secret-production-pangea-io-CORPAY_CLIENT_LEVEL_SIGNATURE
        -   secretKey: NIUM_API_KEY
            remoteRef:
                key: secret-production-pangea-io-NIUM_API_KEY
        -   secretKey: MONEX_DEV_USERNAME
            remoteRef:
                key: secret-production-pangea-io-MONEX_DEV_USERNAME
        -   secretKey: MONEX_DEV_PASSWORD
            remoteRef:
                key: secret-production-pangea-io-MONEX_DEV_PASSWORD
        -   secretKey: MONEX_API_KEY
            remoteRef:
                key: secret-production-pangea-io-MONEX_API_KEY
