apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: pangea-production
  labels:
    app.kubernetes.io/managed-by: "Helm"  # Required label for Helm management
  annotations:
    iam.gke.io/gcp-service-account: pangea-production-srv-acc-api@pangea-production.iam.gserviceaccount.com
    meta.helm.sh/release-name: external-secrets  # Required annotation for Helm
    meta.helm.sh/release-namespace: pangea-production  # Required annotation for Helm
