# Generated by Django 4.2.11 on 2024-04-11 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0110_alter_autopilotdata_account_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feed_name", models.CharField(max_length=255)),
                (
                    "channel_group",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bid_markup", models.FloatField(default=0.0)),
                ("ask_markup", models.FloatField(default=0.0)),
                ("quote_type", models.CharField(max_length=100)),
                ("tick_type", models.CharField(max_length=100)),
                ("indicative", models.BooleanField()),
                ("raw", models.JSONField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedInstrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instrument_type",
                    models.CharField(
                        choices=[
                            ("spot", "Spot"),
                            ("forward", "Deliverable Forward"),
                            ("ndf", "Non-deliverable Forward"),
                            ("option", "Option"),
                            ("future", "Future"),
                        ],
                        max_length=50,
                    ),
                ),
                ("symbol", models.CharField(max_length=100)),
                (
                    "tenors",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("RTP", "RTP"),
                            ("ON", "ON"),
                            ("TN", "TN"),
                            ("spot", "Spot"),
                            ("SN", "SN"),
                            ("SW", "SW"),
                            ("1W", "1W"),
                            ("2W", "2W"),
                            ("3W", "3W"),
                            ("1M", "1M"),
                            ("2M", "2M"),
                            ("3M", "3M"),
                            ("4M", "4M"),
                            ("5M", "5M"),
                            ("6M", "6M"),
                            ("7M", "7M"),
                            ("8M", "8M"),
                            ("9M", "9M"),
                            ("1Y", "1Y"),
                            ("fwd", "Fwd"),
                            ("ndf", "NDF"),
                        ],
                        max_length=67,
                        null=True,
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fee.feed"
                    ),
                ),
            ],
        ),
    ]
