# Generated by Django 4.2.7 on 2024-02-20 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategy', '0001_initial'),
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlecashflow',
            name='hedge_strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashflows', to='strategy.hedgingstrategy'),
        ),
    ]
