# Generated by Django 4.2.10 on 2024-02-29 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0003_singlecashflow_from_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singlecashflow',
            old_name='self_directed',
            new_name='self_guided',
        ),
    ]
