# Generated by Django 4.2.10 on 2024-02-29 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0019_deliverytime'),
        ('cashflow', '0004_rename_self_directed_singlecashflow_self_guided'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singlecashflow',
            old_name='self_guided',
            new_name='self_directed',
        ),
        migrations.AddField(
            model_name='singlecashflow',
            name='lock_side',
            field=models.CharField(blank=True, choices=[('from', 'From'), ('to', 'To')], help_text="The lock of the cashflow being locked, either 'from' or 'to'.", max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='singlecashflow',
            name='from_currency',
            field=models.ForeignKey(blank=True, help_text='The from currency of the cashflow', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_from_currency', to='currency.currency'),
        ),
        migrations.AlterField(
            model_name='singlecashflow',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('live', 'Live'), ('hedged', 'Hedged'), ('settled', 'Settled'), ('canceled', 'Cancelled')], default='draft', help_text='The status of the cashflow', max_length=24),
        ),
        migrations.AlterField(
            model_name='singlecashflow',
            name='to_currency',
            field=models.ForeignKey(blank=True, help_text='The to currency of the cashflow', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_to_currency', to='currency.currency'),
        ),
    ]
