# Generated by Django 4.2.10 on 2024-02-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0005_rename_self_guided_singlecashflow_self_directed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlecashflow',
            name='pay_date',
            field=models.DateField(help_text='The date the cashflow is paid or received'),
        ),
    ]
