# Generated by Django 4.2.10 on 2024-03-04 23:07

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0103_merge_20240224_0039'),
        ('strategy', '0005_hedgingstrategy_lock_side'),
        ('currency', '0019_deliverytime'),
        ('cashflow', '0006_alter_singlecashflow_pay_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlecashflow',
            name='from_currency',
        ),
        migrations.RemoveField(
            model_name='singlecashflow',
            name='hedge_strategy',
        ),
        migrations.RemoveField(
            model_name='singlecashflow',
            name='lock_side',
        ),
        migrations.RemoveField(
            model_name='singlecashflow',
            name='self_directed',
        ),
        migrations.RemoveField(
            model_name='singlecashflow',
            name='to_currency',
        ),
        migrations.AlterField(
            model_name='singlecashflow',
            name='pay_date',
            field=models.DateTimeField(help_text='The date the cashflow is paid or received'),
        ),
        migrations.AlterField(
            model_name='singlecashflow',
            name='status',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('pending', 'PENDING'), ('approved', 'APPROVED'), ('live', 'LIVE'), ('canceled', 'CANCELED')], default='draft', help_text='The status of the cashflow', max_length=24),
        ),
        migrations.CreateModel(
            name='CashFlowGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('value_date', models.DateField(help_text='The date when the transaction value will be settled. Defaults to next business day if non-settlement day provided.')),
                ('lock_side', models.CharField(blank=True, choices=[('from', 'From'), ('to', 'To')], help_text="The side of the transaction being locked, either 'from' or 'to'.", max_length=4, null=True)),
                ('amount', models.FloatField(help_text='The amount of the cashflow')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('live', 'Live'), ('hedged', 'Hedged'), ('settled', 'Settled'), ('canceled', 'Cancelled')], default='draft', help_text='The status of the cashflow', max_length=24)),
                ('self_directed', models.BooleanField(default=True, help_text='Self-directed cashflow')),
                ('periodicity', recurrence.fields.RecurrenceField(null=True)),
                ('name', models.CharField(help_text='A name for the cashflow', max_length=255, null=True)),
                ('description', models.TextField(help_text='A description of the cashflow', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashflow_generators', to='account.company')),
                ('from_currency', models.ForeignKey(help_text='The from currency of the cashflow', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_from_currency', to='currency.currency')),
                ('hedge_strategy', models.ForeignKey(help_text='The hedging strategy the cashflow is attached to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashflows', to='strategy.hedgingstrategy')),
                ('to_currency', models.ForeignKey(blank=True, help_text='The to currency of the cashflow', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_to_currency', to='currency.currency')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
