# Generated by Django 4.2.10 on 2024-03-05 00:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0007_remove_singlecashflow_from_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowgenerator',
            name='cashflow_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique ID of the cashflow'),
        ),
    ]
