# Generated by Django 4.2.10 on 2024-03-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0008_cashflowgenerator_cashflow_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowgenerator',
            name='periodicity_end_date',
            field=models.DateField(null=True),
        ),
    ]
