# Generated by Django 4.2.10 on 2024-03-27 21:48

from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0023_currency_populate_unit'),
        ('cashflow', '0010_rename_from_currency_cashflowgenerator_buy_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlecashflow',
            name='currency',
        ),
        migrations.AddField(
            model_name='cashflowgenerator',
            name='periodicity_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singlecashflow',
            name='buy_currency',
            field=models.ForeignKey(help_text='The buy currency of the cashflow', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_buy_currency', to='currency.currency'),
        ),
        migrations.AddField(
            model_name='singlecashflow',
            name='generator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashflows', to='cashflow.cashflowgenerator'),
        ),
        migrations.AddField(
            model_name='singlecashflow',
            name='sell_currency',
            field=models.ForeignKey(help_text='The currency of the cashflow', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_sell_currency', to='currency.currency'),
        ),
        migrations.AlterField(
            model_name='cashflowgenerator',
            name='description',
            field=models.TextField(blank=True, help_text='A description of the cashflow', null=True),
        ),
        migrations.AlterField(
            model_name='cashflowgenerator',
            name='name',
            field=models.CharField(blank=True, help_text='A name for the cashflow', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cashflowgenerator',
            name='periodicity',
            field=recurrence.fields.RecurrenceField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashflowgenerator',
            name='periodicity_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
