# Generated by Django 4.2.11 on 2024-04-09 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0023_currency_populate_unit'),
        ('cashflow', '0011_remove_singlecashflow_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlecashflow',
            name='lock_side',
            field=models.ForeignKey(blank=True, help_text='ISO 4217 Standard 3-Letter Currency Code used to reference the amount of currency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lock_side', to='currency.currency'),
        ),
    ]
