# Generated by Django 4.2.11 on 2024-04-05 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0023_currency_populate_unit'),
        ('cashflow', '0011_remove_singlecashflow_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowgenerator',
            name='installment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashflowgenerator',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cashflowgenerator',
            name='amount',
            field=models.FloatField(help_text='The amount of the cashflow', null=True),
        ),
        migrations.AlterField(
            model_name='cashflowgenerator',
            name='lock_side',
            field=models.ForeignKey(blank=True, help_text='ISO 4217 Standard 3-Letter Currency Code used to reference the amount of currency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lock_side', to='currency.currency'),
        ),
        migrations.AlterField(
            model_name='cashflowgenerator',
            name='value_date',
            field=models.DateField(help_text='The date when the transaction value will be settled. Defaults to next business day if non-settlement day provided.', null=True),
        ),
    ]
