# Generated by Django 4.2.11 on 2024-04-09 02:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0012_cashflowgenerator_installment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlecashflow',
            name='cashflow_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique ID of the cashflow'),
        ),
    ]
