# Generated by Django 4.2.11 on 2024-04-10 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0013_alter_cashflowgenerator_lock_side'),
        ('cashflow', '0013_singlecashflow_cashflow_id'),
    ]

    operations = [
    ]
