# Generated by Django 4.2.11 on 2024-04-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0015_singlecashflow_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowgenerator',
            name='cntr_amount',
            field=models.FloatField(help_text='The counter amount of the cashflow', null=True),
        ),
        migrations.AddField(
            model_name='singlecashflow',
            name='cntr_amount',
            field=models.FloatField(help_text='The counter amount of the cashflow', null=True),
        ),
    ]
