# Generated by Django 4.2.11 on 2024-04-18 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0023_currency_populate_unit'),
        ('cashflow', '0017_remove_cashflowgenerator_hedge_strategy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowgenerator',
            name='lock_side',
            field=models.ForeignKey(blank=True, help_text='ISO 4217 Standard 3-Letter Currency Code used to indicate which amount you are defining the value of. The non-lock_side amount will be calculated.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lock_side', to='currency.currency'),
        ),
        migrations.AlterField(
            model_name='singlecashflow',
            name='lock_side',
            field=models.ForeignKey(blank=True, help_text='ISO 4217 Standard 3-Letter Currency Code used to indicate which amount you are defining the value of. The non-lock_side amount will be calculated.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lock_side', to='currency.currency'),
        ),
    ]
