# Generated by Django 4.2.11 on 2024-05-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0087_auto_20240520_0123'),
        ('cashflow', '0018_alter_cashflowgenerator_lock_side_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlecashflow',
            name='tickets',
            field=models.ManyToManyField(to='oems.ticket'),
        ),
    ]
