# Generated by Django 4.2.11 on 2024-07-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0020_auto_20240522_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlecashflow',
            name='transaction_date',
            field=models.DateField(help_text="Payment's cashflow transaction date", null=True),
        ),
    ]
