# Generated by Django 4.2.15 on 2024-09-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oems', '0102_alter_ticket_phase'),
        ('cashflow', '0023_alter_singlecashflow_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlecashflow',
            name='tickets',
            field=models.ManyToManyField(blank=True, to='oems.ticket'),
        ),
    ]
