# Generated by Django 4.2.15 on 2024-10-25 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashflow', '0024_alter_singlecashflow_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowgenerator',
            name='approval_date_1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cashflowgenerator',
            name='approval_date_2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cashflowgenerator',
            name='approval_method',
            field=models.CharField(choices=[('no_approval', 'No Approval Required'), ('approval_required', 'Approval Required')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cashflowgenerator',
            name='approval_trigger',
            field=models.CharField(choices=[('all_approvals', 'All Transactions Require Approval'), ('min_approval', 'Approval Required If Exceeding Min Trigger')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cashflowgenerator',
            name='approver_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashflow_approver_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashflowgenerator',
            name='approver_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashflow_approver_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashflowgenerator',
            name='is_dual_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cashflowgenerator',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('live', 'Live'), ('hedged', 'Hedged'), ('settled', 'Settled'), ('canceled', 'Cancelled'), ('pending_approval', 'Pending Approval')], default='draft', help_text='The status of the cashflow', max_length=24),
        ),
    ]
