# Generated by Django 4.2.15 on 2024-10-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0025_cashflowgenerator_approval_date_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowgenerator',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('live', 'Live'), ('hedged', 'Hedged'), ('settled', 'Settled'), ('canceled', 'Cancelled'), ('pend_auth', 'Pending Authorization')], default='draft', help_text='The status of the cashflow', max_length=24),
        ),
    ]
