# Generated by Django 4.2.11 on 2024-07-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monex', '0002_remove_monexcompanysettings_monex_entity_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monexcompanysettings',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monexcompanysettings',
            name='customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monexcompanysettings',
            name='entity_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
