from dataclasses import dataclass
from typing import Literal, Optional

from main.apps.corpay.services.api.dataclasses.base import JsonDictMixin


@dataclass
class ClientPrefundPayload(JsonDictMixin):

    """
    required
    This field accepts the amount transferred to account
    """
    amount:float

    """
    required
    This field accepts the 3-letter ISO-4217 currency code.
    """
    currencyCode:str

    """
    This field accepts the reference number provided by the bank during fund transfer

    """
    bankReferenceNumber:Optional[str] = None

    """
    This field accepts the virtual account number
    """
    beneAccountNumber:Optional[str] = None

    """
    This field accepts the client's bank account number for reference from which the client has transferred money.

    """
    clientAccountNumber:Optional[str] = None

    """
    This field accepts the comments which need to be passed, if any.

    """
    comments:Optional[str] = None

    """
    This field accepts the date of the client's prefund transfer to the NIUM bank account.
    This request can be raised for a transfer within 30 days.
    """
    dateOfTransfer:Optional[str] = None

    """
    This field accepts the NIUM account number to which the client has transferred the money.
    """
    niumAccountNumber:Optional[str] = None

    """
    This field accepts the client's unique requester ID.
    """
    requesterId:Optional[str] = None


@dataclass
class ClientPrefundResponse(JsonDictMixin):

    """
    This field contains the amount transferred to account.
    """
    amount:float

    """
    This field will return a success message if the prefund request added successfully
    """
    message:str

    """
    This field contains the transaction reference number or
    identifier generated by card issuance platform for the client prefund request.
    """
    systemReferenceNumber:str

    """
    This field contains the status.
    """
    status:Optional[Literal['Pending', 'Approved', 'Rejected']] = None

    """
    This field contains the unique email ID provided to the customer
    in addition to uniquePaymentId for supported regions and configuration,
    or else it will be null, for example, abc12_ca@nium.com.
    """
    uniquePayerId:Optional[str] = None

    """
    This field contains the virtual account number per currency provided to customers
    for supported regions and configuration,
    for example, IBAN in EU, virtual account number from Moonova in AU,
    or else, it will be null.
    """
    uniquePaymentId:Optional[str] = None
