# Generated by Django 3.2.8 on 2022-08-07 19:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0042_companycontactorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('incurred', models.DateTimeField()),
                ('recorded', models.DateTimeField(auto_now_add=True)),
                ('due', models.DateTimeField()),
                ('settled', models.DateTimeField(blank=True, null=True)),
                ('fee_type', models.CharField(choices=[('new_hedge', 'NEW_HEDGE'), ('new_cashflow', 'NEW_CASHFLOW'), ('maintenance', 'MAINTENANCE')], max_length=24)),
                ('status', models.CharField(choices=[('due', 'DUE'), ('paid', 'PAID'), ('waived', 'WAIVED')], default='due', max_length=24)),
                ('cashflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashflows', to='account.cashflow')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='account.company')),
            ],
            options={
                'verbose_name_plural': 'fees',
            },
        ),
        migrations.CreateModel(
            name='FeeTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('tier_from', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('new_cash_fee_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.5)])),
                ('aum_fee_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.5)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_companies', to='account.company')),
            ],
            options={
                'verbose_name_plural': 'feetiers',
                'unique_together': {('company', 'tier_from')},
            },
        ),
    ]
