# Generated by Django 3.2.8 on 2022-11-07 21:56

from django.db import migrations
from main.apps.core.models.config import Config

def create_default_fee_tiers(app, schema_editor):
    config = Config(
        path='billing/fee_tires/default',
        value=[
            {
                "tier_from": 0,
                "new_cash_fee_rate": .005
            },
            {
                "tier_from": 10000000,
                "new_cash_fee_rate": .004
            },
            {
                "tier_from": 100000000,
                "new_cash_fee_rate": .003
            },
            {
                "tier_from": 250000000,
                "new_cash_fee_rate": .0025
            },
            {
                "tier_from": 1000000000,
                "new_cash_fee_rate": .001
            }
        ]
    )
    config.save()


def delete_default_fee_tiers(app, schema_editor):
    Config.objects.filter(path='billing/fee_tires/default').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
        ('billing', '0003_fee_payment'),
    ]

    operations = [
        migrations.RunPython(create_default_fee_tiers, delete_default_fee_tiers)
    ]
