# Generated by Django 3.2.8 on 2022-11-07 22:11

from django.db import migrations

from main.apps.core.models import Config


def update_default_fee_tiers(app, schema_editor):
    config = Config.objects.filter(path='billing/fee_tires/default').first()
    config.value = [
            {
                "tier_from": 0,
                "new_cash_fee_rate": .005,
                "aum_fee_rate": .0009
            },
            {
                "tier_from": 10000000,
                "new_cash_fee_rate": .004,
                "aum_fee_rate": .0007
            },
            {
                "tier_from": 100000000,
                "new_cash_fee_rate": .003,
                "aum_fee_rate": .0005
            },
            {
                "tier_from": 250000000,
                "new_cash_fee_rate": .0025,
                "aum_fee_rate": .0004
            },
            {
                "tier_from": 1000000000,
                "new_cash_fee_rate": .001,
                "aum_fee_rate": .0002
            }
        ]
    config.save()

class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_initialize_default_fee_tiers'),
    ]

    operations = [
        migrations.RunPython(update_default_fee_tiers)
    ]
