# Generated by Django 4.2.3 on 2023-10-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_update_default_fee_tiers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fee",
            name="fee_type",
            field=models.CharField(
                choices=[
                    ("new_cashflow", "NEW_CASHFLOW"),
                    ("maintenance", "MAINTENANCE"),
                ],
                max_length=24,
            ),
        ),
    ]
