
# ==============================================

class INTERNAL_STATES:

    NEW          = 'NEW'
    DRAFT        = 'DRAFT'
    ACTIVE       = 'ACTIVE'
    PENDAUTH     = 'PENDAUTH'
    PENDMARGIN   = 'PENDMARGIN'
    SCHEDULED    = 'SCHEDULED'
    WAITING      = 'WAITING'
    ACCEPTED     = 'ACCEPTED'
    WORKING      = 'WORKING'
    PENDPAUSE    = 'PENDPAUSE'
    PENDRESUME   = 'PENDRESUME'
    PAUSED       = 'PAUSED'
    PENDCANCEL   = 'PENDCANCEL'
    CANCELED     = 'CANCELED'
    CANCELREJECT = 'CANCELREJECT'
    PTLCANCEL    = 'PTLCANCEL'
    FILLED       = 'FILLED'
    PARTIAL      = 'PARTIAL'
    PENDSETTLE   = 'PENDSETTLE'
    PENDBENE     = 'PENDBENE'
    PENDFUNDS    = 'PENDFUNDS'
    BOOKED       = 'BOOKED'
    PENDRECON    = 'PENDRECON'
    DONE         = 'DONE'
    DONE_PENDSETTLE = 'DONE_PENDSETTLE'
    ERROR        = 'ERROR'
    FAILED       = 'FAILED'
    EXPIRED      = 'EXPIRED'
    PEND_RFQ     = 'PEND_RFQ'
    RFQ_DONE     = 'RFQ_DONE'
    MANUAL       = 'MANUAL'
    BOOKING_FAILURE = 'BOOKING_FAILURE'
    SETTLE_FAIL = 'SETTLE_FAIL'

    WORKING_STATES      = { WORKING, PARTIAL }
    SETTLEMENT_STATES   = { FILLED, PTLCANCEL }
    OMS_TERMINAL_STATES = { DONE, FAILED, CANCELED, EXPIRED, RFQ_DONE, DONE_PENDSETTLE }
    EMS_TERMINAL_STATES = { DONE, FAILED, CANCELED, EXPIRED, RFQ_DONE, }
    PENDSETTLE_STATES   = { PENDSETTLE, PENDBENE, PENDFUNDS }
    CANCELLABLE_STATES  = { NEW, DRAFT, PENDAUTH, PENDMARGIN, SCHEDULED, WAITING, ACCEPTED, RFQ_DONE, PEND_RFQ }
    PAUSEABLE_STATES    = { NEW, DRAFT, PENDAUTH, PENDMARGIN, SCHEDULED, WAITING, ACCEPTED }
    MTM_STATES          = { FILLED, PTLCANCEL, PENDSETTLE, PENDBENE, PENDFUNDS, DONE_PENDSETTLE }

    # TODO: need better mapping of which fields can be changed when

    MODIFY_ALL_STATES    = { NEW, DRAFT }
    MODIFY_STRAT_STATES  = { NEW, DRAFT, PENDAUTH, PENDMARGIN, SCHEDULED, WAITING, ACCEPTED }
    MODIFY_SETTLE_STATES = {} # all states prior

class EXTERNAL_STATES:
    NEW        = 'NEW'
    ACTIVE     = 'ACTIVE'
    PENDCANCEL = 'PENDCANCEL'
    CANCELED   = 'CANCELED'
    DONE       = 'DONE'
    FAILED     = 'FAILED'
    PAUSED     = 'PAUSED'
    PENDING    = 'PENDING'
    
class PHASES:
    PRETRADE = 'PRETRADE'
    WORKING  = 'WORKING'
    SETTLE   = 'SETTLE'
    RECON    = 'RECON'

    TRADING = { PRETRADE, WORKING }
    POSTTRADE = { SETTLE, RECON }

class OMS_API_ACTIONS:

    CREATE   = 'CREATE'
    CANCEL   = 'CANCEL'
    PAUSE    = 'PAUSE'
    RESUME   = 'RESUME'
    MODIFY   = 'MODIFY'
    ACTIVATE = 'ACTIVATE'
    AUTHORIZE = 'AUTHORIZE'
    DBSYNC   = 'DBSYNC'
    DELETE   = 'DELETE'
    EXECUTE_RFQ = 'EXECUTE_RFQ'
    
class OMS_EMS_ACTIONS:

    DONE   = 'DONE'
    UPDATE = 'UPDATE'
    CREATE = 'CREATE'
    CANCEL = 'CANCEL'
    CANCELREJECT = 'CANCELREJECT'
    ACCEPT = 'ACCEPT'
    
    # TBD
    MODIFY = 'MODIFY'


# =============================================================================

class ERRORS:
    NO_DESTINATION = 'NO DESTINATION SET. CANNOT ROUTE'
    
