# Generated by Django 4.2.10 on 2024-02-29 01:46

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import django_extensions.db.fields
import multiselectfield.db.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0019_deliverytime'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of the beneficiary', primary_key=True, serialize=False)),
                ('classification', models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate')], help_text='Classification of the beneficiary: individual or corporate')),
                ('name', models.TextField(help_text='Full name of the account holder. Maximum 100 characters.')),
                ('address_1', models.TextField(help_text='Address line 1')),
                ('address_2', models.TextField(help_text='Address line 2')),
                ('city', models.TextField(help_text='City')),
                ('country', django_countries.fields.CountryField(help_text='Country', max_length=2)),
                ('region', models.TextField(help_text='Region')),
                ('postal', models.TextField(help_text='Postal code')),
                ('country_code', models.TextField(help_text='Country code')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number', max_length=128, region=None)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('destination_country', django_countries.fields.CountryField(help_text='Destination country', max_length=2)),
                ('account_number', models.TextField(help_text='Account number')),
                ('bank_name', models.TextField(help_text='Bank name')),
                ('payment_reference', models.TextField(help_text='Payment reference')),
                ('destination_currency', models.ForeignKey(blank=True, help_text='Currency of the destination', null=True, on_delete=django.db.models.deletion.PROTECT, to='currency.currency')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CorpayBeneficiary',
            fields=[
                ('beneficiary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='settlement.beneficiary')),
                ('local_account_number', models.TextField(help_text='Local account number')),
                ('routing_code', models.TextField(help_text='Routing code')),
                ('local_routing_code', models.TextField(help_text='Local routing code')),
                ('send_pay_tracker', models.BooleanField(help_text='Send pay tracker')),
                ('iban', models.TextField(help_text='IBAN')),
                ('swift_bic_code', models.TextField(help_text='SWIFT/BIC code')),
                ('bank_country', django_countries.fields.CountryField(help_text='Bank country', max_length=2)),
                ('bank_region', models.TextField(help_text='Bank region')),
                ('bank_city', models.TextField(help_text='Bank city')),
                ('bank_address_1', models.TextField(help_text='Bank address 1')),
                ('bank_address_2', models.TextField(help_text='Bank address 2')),
                ('bank_postal', models.TextField(help_text='Bank postal code')),
                ('purpose_of_payment', models.TextField(blank=True, help_text='Purpose of payment', null=True)),
                ('internal_payment_alert', models.TextField(blank=True, help_text='Internal payment alert', null=True)),
                ('external_payment_alert', models.TextField(blank=True, help_text='External payment alert', null=True)),
                ('regulatory', models.JSONField(blank=True, help_text='Regulatory information', null=True)),
                ('payment_methods', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('W', 'Wire'), ('E', 'EFT')], help_text='Payment methods', max_length=3, null=True)),
                ('preferred_method', models.CharField(blank=True, choices=[('W', 'Wire'), ('E', 'EFT')], help_text='Preferred payment method', max_length=11, null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('settlement.beneficiary',),
        ),
        migrations.CreateModel(
            name='NiumBeneficiary',
            fields=[
                ('beneficiary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='settlement.beneficiary')),
                ('relationship', models.TextField(help_text='Relationship with the beneficiary')),
                ('alias', models.TextField(help_text='Alias')),
                ('payout_method', models.CharField(blank=True, choices=[('LOCAL', 'Local'), ('SWIFT', 'SWIFT'), ('WALLET', 'Wallet'), ('CARD', 'Card'), ('PROXY', 'Proxy')], help_text='Payout method', max_length=11, null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('settlement.beneficiary',),
        ),
    ]
