# Generated by Django 4.2.10 on 2024-02-29 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0005_auto_20240227_2321'),
        ('account', '0103_merge_20240224_0039'),
        ('settlement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='broker',
            field=models.ForeignKey(blank=True, help_text='The broker the beneficiary belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_beneficiary', to='broker.broker'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='company',
            field=models.ForeignKey(blank=True, help_text='The company the beneficiary belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_beneficiary', to='account.company'),
        ),
    ]
