# Generated by Django 4.2.10 on 2024-03-05 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0002_beneficiary_broker_beneficiary_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpaybeneficiary',
            name='beneficiary_ptr',
        ),
        migrations.RemoveField(
            model_name='niumbeneficiary',
            name='beneficiary_ptr',
        ),
        migrations.DeleteModel(
            name='Beneficiary',
        ),
        migrations.DeleteModel(
            name='CorpayBeneficiary',
        ),
        migrations.DeleteModel(
            name='NiumBeneficiary',
        ),
    ]
