# Generated by Django 4.2.10 on 2024-03-15 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='phone_prefix',
        ),
    ]
