# Generated by Django 4.2.11 on 2024-04-18 17:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0005_remove_beneficiary_phone_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='iban',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='reason',
            field=models.TextField(blank=True, help_text='The reason for deleting the beneficiary', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('synced', 'Synced'), ('pending_update', 'Pending Update'), ('pending_delete', 'Pending Delete'), ('deleted', 'Deleted')], default='draft', help_text='The status of the beneficiary', max_length=60),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='address_1',
            field=models.TextField(help_text='Ex: 123 Main St.'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='address_2',
            field=models.TextField(blank=True, help_text='Ex: Apt. #4', null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='country',
            field=models.CharField(help_text='The country in which the bank account is domiciled. This field accepts the <a href="https://docs.pangea.io/reference/currency-and-country-codes"> ISO-2 country code</a>', max_length=2),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='destination_country',
            field=models.CharField(help_text='The country in which the bank account is domiciled. This field accepts the <a href="https://docs.pangea.io/reference/currency-and-country-codes"> ISO-2 country code</a>', max_length=2),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='local_code',
            field=models.TextField(blank=True, help_text='country specific code such as CLABE, CNAP, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone number', max_length=128, null=True, region=None),
        ),
    ]
