# Generated by Django 4.2.11 on 2024-05-24 02:12

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('broker', 'add_corpay_fees_20240513'),
        ('settlement', '0006_remove_beneficiary_iban_beneficiary_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonexBeneficiary',
            fields=[
                ('beneficiary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='settlement.beneficiary')),
                ('intermediary_bank_name', models.TextField(blank=True, help_text='Intermediary bank name', null=True)),
                ('intermediary_bank_address_line_1', models.TextField(blank=True, help_text='Intermediary bank address line 1', null=True)),
                ('intermediary_bank_address_line_2', models.TextField(blank=True, help_text='Intermediary bank address line 2', null=True)),
                ('intermediary_bank_city', models.TextField(blank=True, help_text='Intermediary bank city', null=True)),
                ('intermediary_bank_country', models.CharField(blank=True, help_text='Intermediary bank country', max_length=2, null=True)),
                ('intermediary_bank_postal_code', models.TextField(blank=True, help_text='Intermediary bank postal code', null=True)),
                ('intermediary_bank_swift_code', models.TextField(blank=True, help_text='Intermediary bank SWIFT code', null=True)),
                ('further_credit_account_number', models.TextField(blank=True, help_text='Further credit account number', null=True)),
                ('further_credit_name', models.TextField(blank=True, help_text='Further credit name', null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('settlement.beneficiary',),
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='beneficiary_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='corpaybeneficiary',
            name='bank_address_1',
        ),
        migrations.RemoveField(
            model_name='corpaybeneficiary',
            name='bank_address_2',
        ),
        migrations.RemoveField(
            model_name='corpaybeneficiary',
            name='bank_city',
        ),
        migrations.RemoveField(
            model_name='corpaybeneficiary',
            name='bank_country',
        ),
        migrations.RemoveField(
            model_name='corpaybeneficiary',
            name='bank_postal',
        ),
        migrations.RemoveField(
            model_name='niumbeneficiary',
            name='alias',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='alias',
            field=models.TextField(blank=True, help_text='Alias'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='bank_address_1',
            field=models.TextField(default='default_bank_address', help_text='Bank address line 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='bank_address_2',
            field=models.TextField(blank=True, help_text='Bank address line 2', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='bank_city',
            field=models.TextField(default='default_bank_city', help_text='Bank city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='bank_country',
            field=django_countries.fields.CountryField(default='US', help_text='Bank country', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='bank_postal',
            field=models.TextField(default='default_bank_postal', help_text='Bank postal code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='identification_type',
            field=models.CharField(blank=True, choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('driving_license', 'Driving License'), ('others', 'Others')], help_text='Type of identification document', max_length=50),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='identification_value',
            field=models.CharField(blank=True, help_text='Identification document number', max_length=50),
        ),
        migrations.AddField(
            model_name='niumbeneficiary',
            name='proxy_type',
            field=models.CharField(blank=True, choices=[('MOBILE', 'Mobile'), ('UEN', 'UEN'), ('NRIC', 'NRIC'), ('VPA', 'VPA'), ('ID', 'ID'), ('EMAIL', 'Email'), ('RANDOM_KEY', 'Random Key'), ('ABN', 'ABN'), ('ORGANISATION_ID', 'Organisation ID'), ('PASSPORT', 'Passport'), ('CORPORATE_REGISTRATION_NUMBER', 'Corporate Registration Number'), ('ARMY_ID', 'Army ID')], help_text='Proxy type', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='niumbeneficiary',
            name='proxy_value',
            field=models.CharField(blank=True, help_text='Proxy value', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='niumbeneficiary',
            name='remitter_beneficiary_relationship',
            field=models.CharField(blank=True, help_text='Relationship between remitter and beneficiary', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='account_number',
            field=models.TextField(help_text='Bank account number, IBAN, etc.'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='address_1',
            field=models.TextField(blank=True, help_text='Ex: 123 Main St.', null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='local_code',
            field=models.TextField(blank=True, help_text='Country specific code such as CLABE, CNAP, etc.', null=True),
        ),
        migrations.CreateModel(
            name='BeneficiaryFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_field', models.CharField(help_text='The field name in the beneficiary model', max_length=100)),
                ('broker_field', models.CharField(help_text="The corresponding field name in the broker's API", max_length=100)),
                ('broker', models.ForeignKey(help_text='The broker associated with the field mapping', on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_field_mappings', to='broker.broker')),
            ],
            options={
                'unique_together': {('broker', 'beneficiary_field')},
            },
        ),
    ]
