# Generated by Django 4.2.11 on 2024-05-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', 'add_corpay_fees_20240513'),
        ('settlement', '0008_beneficiary_additional_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='beneficiaryfieldmapping',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='broker',
        ),
        migrations.AddField(
            model_name='beneficiaryfieldmapping',
            name='brokers',
            field=models.ManyToManyField(help_text='The brokers associated with the field mapping', to='broker.broker'),
        ),
        migrations.RemoveField(
            model_name='beneficiaryfieldmapping',
            name='broker',
        ),
    ]
