# Generated by Django 4.2.11 on 2024-05-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0010_auto_20240524_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='external_id',
            field=models.TextField(blank=True),
        ),
    ]
