# Generated by Django 4.2.11 on 2024-05-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0011_beneficiary_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='bank_branch_name',
            field=models.TextField(blank=True, help_text='Bank Branch Name'),
        ),
    ]
