# Generated by Django 4.2.11 on 2024-05-31 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0012_beneficiary_bank_branch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpaybeneficiary',
            name='bank_region',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='bank_region',
            field=models.TextField(blank=True, help_text='State, Province, etc.'),
        ),
        migrations.AddField(
            model_name='corpaybeneficiary',
            name='iban_enabled',
            field=models.BooleanField(default=False, help_text='IBAN enable'),
        ),
    ]
