# Generated by Django 4.2.11 on 2024-05-31 21:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0013_remove_corpaybeneficiary_bank_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpaybeneficiary',
            name='purpose_of_payment',
        ),
        migrations.AddField(
            model_name='corpaybeneficiary',
            name='iban_digits',
            field=models.TextField(blank=True, help_text='IBAN digits', null=True),
        ),
        migrations.AddField(
            model_name='corpaybeneficiary',
            name='settlement_methods',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('W', 'Wire'), ('E', 'EFT')], help_text='Payment methods', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='bank_country',
            field=models.CharField(help_text='The country in which the bank account is domiciled. This field accepts the <a href="https://docs.pangea.io/reference/currency-and-country-codes"> ISO-2 country code</a>', max_length=2),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='classification',
            field=models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('aerospace_defense', 'Aerospace and defense'), ('agriculture_agrifood', 'Agriculture and agric-food'), ('apparel_clothing', 'Apparel / Clothing'), ('automotive_trucking', 'Automotive / Trucking'), ('books_magazines', 'Books / Magazines'), ('broadcasting', 'Broadcasting'), ('building_products', 'Building products'), ('chemicals', 'Chemicals'), ('dairy', 'Dairy'), ('e_business', 'E-business'), ('environment', 'Environment'), ('explosives', 'Explosives'), ('fisheries_oceans', 'Fisheries and oceans'), ('food_beverage_distribution', 'Food / Beverage distribution'), ('footwear', 'Footwear'), ('forest_industries', 'Forest industries'), ('furniture', 'Furniture'), ('giftware_crafts', 'Giftware and crafts'), ('horticulture', 'Horticulture'), ('hydroelectric_energy', 'Hydroelectric energy'), ('ict', 'Information and communication technologies'), ('intelligent_systems', 'Intelligent systems'), ('livestock', 'Livestock'), ('medical_devices', 'Medical devices'), ('medical_treatment', 'Medical treatment'), ('minerals_metals_mining', 'Minerals, metals and mining'), ('oil_gas', 'Oil and gas'), ('pharmaceuticals_biopharmaceuticals', 'Pharmaceuticals and biopharmaceuticals'), ('plastics', 'Plastics'), ('poultry_eggs', 'Poultry and eggs'), ('printing_publishing', 'Printing / Publishing'), ('product_design_development', 'Product design and development'), ('railway', 'Railway'), ('retail', 'Retail'), ('shipping_industrial_marine', 'Shipping and industrial marine'), ('soil', 'Soil'), ('sound_recording', 'Sound recording'), ('sporting_goods', 'Sporting goods'), ('telecommunications_equipment', 'Telecommunications equipment'), ('television', 'Television'), ('textiles', 'Textiles'), ('tourism', 'Tourism'), ('water_supply', 'Water supply'), ('wholesale', 'Wholesale')], help_text='Classification of the beneficiary: individual or corporate'),
        ),
        migrations.AlterField(
            model_name='corpaybeneficiary',
            name='local_account_number',
            field=models.TextField(blank=True, help_text='Local account number', null=True),
        ),
        migrations.AlterField(
            model_name='corpaybeneficiary',
            name='local_routing_code',
            field=models.TextField(blank=True, help_text='Local routing code', null=True),
        ),
        migrations.AlterField(
            model_name='corpaybeneficiary',
            name='routing_code',
            field=models.TextField(blank=True, help_text='Routing code', null=True),
        ),
        migrations.AlterField(
            model_name='corpaybeneficiary',
            name='send_pay_tracker',
            field=models.BooleanField(blank=True, help_text='Send pay tracker', null=True),
        ),
    ]
