# Generated by Django 4.2.11 on 2024-06-10 23:14

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0014_remove_corpaybeneficiary_purpose_of_payment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CorpayBeneficiary',
        ),
        migrations.DeleteModel(
            name='MonexBeneficiary',
        ),
        migrations.DeleteModel(
            name='NiumBeneficiary',
        ),
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'get_latest_by': 'modified'},
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='account_number',
            new_name='bank_account_number',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='address_1',
            new_name='beneficiary_address_1',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='address_2',
            new_name='beneficiary_address_2',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='city',
            new_name='beneficiary_city',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='email',
            new_name='beneficiary_email',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='name',
            new_name='beneficiary_name',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='phone',
            new_name='beneficiary_phone',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='postal',
            new_name='beneficiary_postal',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='region',
            new_name='beneficiary_region',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='country',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='local_code',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='swift_bic_code',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='bank_account_number_type',
            field=models.CharField(choices=[('iban', 'IBAN'), ('clabe', 'CLABE'), ('account_number', 'Account Number')], default='iban', help_text='Bank account number type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='bank_account_type',
            field=models.CharField(blank=True, choices=[('current', 'Current'), ('saving', 'Saving'), ('maestra', 'Maestra'), ('checking', 'Checking')], help_text='Bank account type', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='bank_code',
            field=models.TextField(blank=True, help_text='Bank code', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='bank_instruction',
            field=models.TextField(blank=True, help_text='Wiring instruction', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='bank_routing_code_1_type',
            field=models.CharField(blank=True, choices=[('swift', 'SWIFT'), ('ifsc', 'IFSC'), ('sort_code', 'SORT Code'), ('ach_code', 'ACH Code'), ('branch_code', 'Branch Code'), ('bsb_code', 'BSB Code'), ('bank_code', 'Bank Code'), ('aba_code', 'ABA Code'), ('transit_code', 'Transit Code'), ('generic', 'Generic')], help_text='Bank Routing Code 1 Type', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='bank_routing_code_1_value',
            field=models.TextField(blank=True, help_text='Bank routing code 1', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='bank_routing_code_2_type',
            field=models.CharField(blank=True, choices=[('swift', 'SWIFT'), ('ifsc', 'IFSC'), ('sort_code', 'SORT Code'), ('ach_code', 'ACH Code'), ('branch_code', 'Branch Code'), ('bsb_code', 'BSB Code'), ('bank_code', 'Bank Code'), ('aba_code', 'ABA Code'), ('transit_code', 'Transit Code'), ('generic', 'Generic')], help_text='Bank Routing Code 2 Type', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='bank_routing_code_2_value',
            field=models.TextField(blank=True, help_text='Bank routing code 2', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='beneficiary_account_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate')], default='checking', help_text='Beneficiary account type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='beneficiary_alias',
            field=models.TextField(blank=True, help_text='Beneficiary alias'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='beneficiary_country',
            field=models.CharField(default='US', help_text='The beneficiary\'s country. This field accepts the <a href="https://docs.pangea.io/reference/currency-and-country-codes"> ISO-2 country code</a>', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='client_legal_entity',
            field=models.CharField(default='US', help_text='This field accepts the <a href="https://docs.pangea.io/reference/currency-and-country-codes"> ISO-2 country code</a>', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='further_account_number',
            field=models.TextField(blank=True, help_text='Further account number', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='further_name',
            field=models.TextField(blank=True, help_text='Further name', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='inter_bank_account_number',
            field=models.TextField(blank=True, help_text='Intermediary bank account number', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='inter_bank_account_number_type',
            field=models.CharField(blank=True, choices=[('iban', 'IBAN'), ('clabe', 'CLABE'), ('account_number', 'Account Number')], help_text='Intermediary bank account number type', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='inter_bank_account_type',
            field=models.CharField(blank=True, choices=[('current', 'Current'), ('saving', 'Saving'), ('maestra', 'Maestra'), ('checking', 'Checking')], help_text='Bank account type', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='inter_bank_address_1',
            field=models.TextField(blank=True, help_text='Intermediary Bank address line 1', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='inter_bank_address_2',
            field=models.TextField(blank=True, help_text='Intermediary Bank address line 2', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='inter_bank_branch_name',
            field=models.TextField(blank=True, help_text='Intermediary Bank Branch Name', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='inter_bank_city',
            field=models.TextField(blank=True, help_text='Intermediary Bank city', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='inter_bank_code',
            field=models.TextField(blank=True, help_text='Intermediary bank code', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='inter_bank_country',
            field=models.TextField(blank=True, help_text='Intermediary Bank country', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='inter_bank_instruction',
            field=models.TextField(blank=True, help_text='Intermediary Bank instruction', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='inter_bank_name',
            field=models.TextField(blank=True, help_text='Intermediary Bank name', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='inter_bank_postal',
            field=models.TextField(blank=True, help_text='Intermediary Bank postal code', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='inter_bank_region',
            field=models.TextField(blank=True, help_text='Intermediary Bank region', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='inter_bank_routing_code_1_type',
            field=models.CharField(blank=True, choices=[('swift', 'SWIFT'), ('ifsc', 'IFSC'), ('sort_code', 'SORT Code'), ('ach_code', 'ACH Code'), ('branch_code', 'Branch Code'), ('bsb_code', 'BSB Code'), ('bank_code', 'Bank Code'), ('aba_code', 'ABA Code'), ('transit_code', 'Transit Code'), ('generic', 'Generic')], help_text='Intermediary bank Routing Code 1 Type', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='inter_bank_routing_code_1_value',
            field=models.TextField(blank=True, help_text='Intermediary bank Routing Code 1', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='inter_bank_routing_code_2_type',
            field=models.CharField(blank=True, choices=[('swift', 'SWIFT'), ('ifsc', 'IFSC'), ('sort_code', 'SORT Code'), ('ach_code', 'ACH Code'), ('branch_code', 'Branch Code'), ('bsb_code', 'BSB Code'), ('bank_code', 'Bank Code'), ('aba_code', 'ABA Code'), ('transit_code', 'Transit Code'), ('generic', 'Generic')], help_text='Intermediary bank Routing Code 2 Type', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='inter_bank_routing_code_2_value',
            field=models.TextField(blank=True, help_text='Intermediary bank routing code 2', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='payment_methods',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('wire', 'Wire'), ('eft', 'EFT'), ('local', 'Local'), ('swift', 'Swift'), ('wallet', 'Wallet'), ('proxy', 'Proxy')], help_text='Payment methods', max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='preferred_method',
            field=models.CharField(blank=True, choices=[('wire', 'Wire'), ('eft', 'EFT'), ('local', 'Local'), ('swift', 'Swift'), ('wallet', 'Wallet'), ('proxy', 'Proxy')], help_text='Preferred payment method', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='proxy_type',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('uen', 'UEN'), ('nric', 'NRIC'), ('vpa', 'VPA'), ('id', 'ID'), ('email', 'Email'), ('random_key', 'Random Key'), ('abn', 'ABN'), ('organization_id', 'Organisation ID'), ('passport', 'Passport'), ('corporate_registration_number', 'Corporate Registration Number'), ('army_id', 'Army ID')], help_text='The proxy type sent in the payment request', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='proxy_value',
            field=models.TextField(blank=True, help_text='The proxy value such as VPA, UEN, or mobile number etc.', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='settlement_methods',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('wire', 'Wire'), ('eft', 'EFT'), ('local', 'Local'), ('swift', 'Swift'), ('wallet', 'Wallet'), ('proxy', 'Proxy')], help_text='Payment methods', max_length=33, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='bank_branch_name',
            field=models.TextField(blank=True, help_text='Bank Branch Name', null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='bank_country',
            field=models.CharField(help_text='This field accepts the <a href="https://docs.pangea.io/reference/currency-and-country-codes"> ISO-2 country code</a>', max_length=2),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='destination_country',
            field=models.CharField(help_text='This field accepts the <a href="https://docs.pangea.io/reference/currency-and-country-codes"> ISO-2 country code</a>', max_length=2),
        ),
    ]
