# Generated by Django 4.2.11 on 2024-06-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0015_remove_monexbeneficiary_beneficiary_ptr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='bank_routing_code_1_type',
            new_name='bank_routing_code_type_1',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='bank_routing_code_2_type',
            new_name='bank_routing_code_type_2',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='bank_routing_code_1_value',
            new_name='bank_routing_code_value_1',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='bank_routing_code_2_value',
            new_name='bank_routing_code_value_2',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='inter_bank_routing_code_1_type',
            new_name='inter_bank_routing_code_type_1',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='inter_bank_routing_code_2_type',
            new_name='inter_bank_routing_code_type_2',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='inter_bank_routing_code_1_value',
            new_name='inter_bank_routing_code_value_1',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='inter_bank_routing_code_2_value',
            new_name='inter_bank_routing_code_value_2',
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='classification',
            field=models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('aerospace_defense', 'Aerospace and defense'), ('agriculture_agrifood', 'Agriculture and agric-food'), ('apparel_clothing', 'Apparel / Clothing'), ('automotive_trucking', 'Automotive / Trucking'), ('books_magazines', 'Books / Magazines'), ('broadcasting', 'Broadcasting'), ('building_products', 'Building products'), ('chemicals', 'Chemicals'), ('dairy', 'Dairy'), ('e_business', 'E-business'), ('environment', 'Environment'), ('explosives', 'Explosives'), ('fisheries_oceans', 'Fisheries and oceans'), ('food_beverage_distribution', 'Food / Beverage distribution'), ('footwear', 'Footwear'), ('forest_industries', 'Forest industries'), ('furniture', 'Furniture'), ('giftware_crafts', 'Giftware and crafts'), ('horticulture', 'Horticulture'), ('hydroelectric_energy', 'Hydroelectric energy'), ('ict', 'Information and communication technologies'), ('intelligent_systems', 'Intelligent systems'), ('livestock', 'Livestock'), ('medical_devices', 'Medical devices'), ('medical_treatment', 'Medical treatment'), ('minerals_metals_mining', 'Minerals, metals and mining'), ('oil_gas', 'Oil and gas'), ('pharmaceuticals_biopharmaceuticals', 'Pharmaceuticals and biopharmaceuticals'), ('plastics', 'Plastics'), ('poultry_eggs', 'Poultry and eggs'), ('printing_publishing', 'Printing / Publishing'), ('product_design_development', 'Product design and development'), ('railway', 'Railway'), ('retail', 'Retail'), ('shipping_industrial_marine', 'Shipping and industrial marine'), ('soil', 'Soil'), ('sound_recording', 'Sound recording'), ('sporting_goods', 'Sporting goods'), ('telecommunications_equipment', 'Telecommunications equipment'), ('television', 'Television'), ('textiles', 'Textiles'), ('tourism', 'Tourism'), ('water_supply', 'Water supply'), ('wholesale', 'Wholesale')], help_text='Classification of the beneficiary'),
        ),
    ]
