# Generated by Django 4.2.11 on 2024-06-12 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0018_auto_20240611_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'verbose_name': 'Beneficiary', 'verbose_name_plural': 'Beneficiaries'},
        ),
        migrations.CreateModel(
            name='BeneficiaryValueMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_value', models.CharField(help_text='The internal value', max_length=100)),
                ('broker_value', models.CharField(help_text='The broker-specific value', max_length=100)),
                ('field_mapping', models.ForeignKey(help_text='The field mapping associated with this value mapping', on_delete=django.db.models.deletion.CASCADE, to='settlement.beneficiaryfieldmapping')),
            ],
            options={
                'verbose_name': 'Beneficiary Value Mapping',
                'verbose_name_plural': 'Beneficiary Value Mappings',
                'unique_together': {('field_mapping', 'internal_value', 'broker_value')},
            },
        ),
    ]
