# Generated by Django 4.2.11 on 2024-06-12 01:08

from django.db import migrations

from main.apps.settlement.services.beneficiary import BeneficiaryValueMappingService


def populate_beneficiary_value_mapping(apps, schema_editor):
    BeneficiaryValueMappingService.create_or_update_value_mappings()

class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0019_alter_beneficiary_options_beneficiaryvaluemapping'),
    ]

    operations = [
        migrations.RunPython(populate_beneficiary_value_mapping)
    ]
