# Generated by Django 4.2.11 on 2024-06-12 18:21

from django.db import migrations, models
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0020_auto_20240612_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='regulatory',
            field=models.JSONField(blank=True, help_text='The fields and corresponding values needed to satisfy regulatory requirements for the destination country.', null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone number with country code, eg. +1-415-333-4444', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='payment_methods',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('local', 'Local'), ('swift', 'Swift'), ('wallet', 'Wallet'), ('card', 'Card'), ('proxy', 'Proxy')], help_text='Payment methods', max_length=29, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='preferred_method',
            field=models.CharField(blank=True, choices=[('local', 'Local'), ('swift', 'Swift'), ('wallet', 'Wallet'), ('card', 'Card'), ('proxy', 'Proxy')], help_text='Preferred payment method', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='settlement_methods',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('local', 'Local'), ('swift', 'Swift'), ('wallet', 'Wallet'), ('card', 'Card'), ('proxy', 'Proxy')], help_text='Settlement methods', max_length=29, null=True),
        ),
    ]
