# Generated by Django 4.2.11 on 2024-06-12 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_alter_brokercompany_company'),
        ('settlement', '0021_beneficiary_regulatory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryBroker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_beneficiary_id', models.CharField(help_text='The broker-specific beneficiary ID', max_length=255)),
                ('beneficiary', models.ForeignKey(help_text='The beneficiary associated with this broker', on_delete=django.db.models.deletion.CASCADE, to='settlement.beneficiary')),
                ('broker', models.ForeignKey(help_text='The broker associated with this beneficiary', on_delete=django.db.models.deletion.CASCADE, to='broker.broker')),
            ],
            options={
                'verbose_name': 'Beneficiary Broker',
                'verbose_name_plural': 'Beneficiary Brokers',
                'unique_together': {('beneficiary', 'broker')},
            },
        ),
    ]
