# Generated by Django 4.2.11 on 2024-07-02 19:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0024_wallet_bank_name_wallet_broker_account_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_balance', models.DecimalField(decimal_places=2, help_text='The total balance in the account', max_digits=18)),
                ('balance_held', models.DecimalField(decimal_places=2, help_text='The amount of balance that is held or reserved', max_digits=18)),
                ('available_balance', models.DecimalField(decimal_places=2, help_text='The balance that is available for use', max_digits=18)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='settlement.wallet')),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
    ]
