# Generated by Django 4.2.11 on 2024-07-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0025_walletbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text="The last time this wallet was synchronized with the broker's data", null=True),
        ),
    ]
