# Generated by Django 4.2.11 on 2024-07-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0028_wallet_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='bank_routing_code_type_1',
            field=models.CharField(blank=True, choices=[('swift', 'SWIFT'), ('ifsc', 'IFSC'), ('sort_code', 'SORT Code'), ('ach_code', 'ACH Code'), ('branch_code', 'Branch Code'), ('bsb_code', 'BSB Code'), ('bank_code', 'Bank Code'), ('aba_code', 'ABA Code'), ('transit_code', 'Transit Code'), ('generic', 'Generic'), ('wallet', 'Wallet'), ('location_id', 'Location ID')], help_text='Bank Routing Code 1 Type', null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='bank_routing_code_type_2',
            field=models.CharField(blank=True, choices=[('swift', 'SWIFT'), ('ifsc', 'IFSC'), ('sort_code', 'SORT Code'), ('ach_code', 'ACH Code'), ('branch_code', 'Branch Code'), ('bsb_code', 'BSB Code'), ('bank_code', 'Bank Code'), ('aba_code', 'ABA Code'), ('transit_code', 'Transit Code'), ('generic', 'Generic'), ('wallet', 'Wallet'), ('location_id', 'Location ID')], help_text='Bank Routing Code 2 Type', null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='identification_type',
            field=models.CharField(blank=True, choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('driving_license', 'Driving License'), ('others', 'Others'), ('cpf', 'CPF'), ('cnpj', 'CNPJ')], help_text='Type of identification document', max_length=50),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='inter_bank_routing_code_type_1',
            field=models.CharField(blank=True, choices=[('swift', 'SWIFT'), ('ifsc', 'IFSC'), ('sort_code', 'SORT Code'), ('ach_code', 'ACH Code'), ('branch_code', 'Branch Code'), ('bsb_code', 'BSB Code'), ('bank_code', 'Bank Code'), ('aba_code', 'ABA Code'), ('transit_code', 'Transit Code'), ('generic', 'Generic'), ('wallet', 'Wallet'), ('location_id', 'Location ID')], help_text='Intermediary bank Routing Code 1 Type', null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='inter_bank_routing_code_type_2',
            field=models.CharField(blank=True, choices=[('swift', 'SWIFT'), ('ifsc', 'IFSC'), ('sort_code', 'SORT Code'), ('ach_code', 'ACH Code'), ('branch_code', 'Branch Code'), ('bsb_code', 'BSB Code'), ('bank_code', 'Bank Code'), ('aba_code', 'ABA Code'), ('transit_code', 'Transit Code'), ('generic', 'Generic'), ('wallet', 'Wallet'), ('location_id', 'Location ID')], help_text='Intermediary bank Routing Code 2 Type', null=True),
        ),
    ]
