# Generated by Django 4.2.14 on 2024-08-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlement", "0030_alter_beneficiary_bank_routing_code_type_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiary",
            name="classification",
            field=models.CharField(
                choices=[
                    ("individual", "Individual"),
                    ("business", "Business"),
                    ("aerospace_defense", "Aerospace and defense"),
                    ("agriculture_agrifood", "Agriculture and agric-food"),
                    ("apparel_clothing", "Apparel / Clothing"),
                    ("automotive_trucking", "Automotive / Trucking"),
                    ("books_magazines", "Books / Magazines"),
                    ("broadcasting", "Broadcasting"),
                    ("building_products", "Building products"),
                    ("chemicals", "Chemicals"),
                    ("dairy", "Dairy"),
                    ("e_business", "E-business"),
                    ("educational_institute", "Educational Institutes"),
                    ("environment", "Environment"),
                    ("explosives", "Explosives"),
                    ("fisheries_oceans", "Fisheries and oceans"),
                    ("food_beverage_distribution", "Food / Beverage distribution"),
                    ("footwear", "Footwear"),
                    ("forest_industries", "Forest industries"),
                    ("furniture", "Furniture"),
                    ("giftware_crafts", "Giftware and crafts"),
                    ("horticulture", "Horticulture"),
                    ("hydroelectric_energy", "Hydroelectric energy"),
                    ("ict", "Information and communication technologies"),
                    ("intelligent_systems", "Intelligent systems"),
                    ("livestock", "Livestock"),
                    ("medical_devices", "Medical devices"),
                    ("medical_treatment", "Medical treatment"),
                    ("minerals_metals_mining", "Minerals, metals and mining"),
                    ("oil_gas", "Oil and gas"),
                    (
                        "pharmaceuticals_biopharmaceuticals",
                        "Pharmaceuticals and biopharmaceuticals",
                    ),
                    ("plastics", "Plastics"),
                    ("poultry_eggs", "Poultry and eggs"),
                    ("printing_publishing", "Printing / Publishing"),
                    ("product_design_development", "Product design and development"),
                    ("railway", "Railway"),
                    ("retail", "Retail"),
                    ("shipping_industrial_marine", "Shipping and industrial marine"),
                    ("soil", "Soil"),
                    ("sound_recording", "Sound recording"),
                    ("sporting_goods", "Sporting goods"),
                    ("telecommunications_equipment", "Telecommunications equipment"),
                    ("television", "Television"),
                    ("textiles", "Textiles"),
                    ("tourism", "Tourism"),
                    ("trademakrs_law", "Trademarks / Law"),
                    ("water_supply", "Water supply"),
                    ("wholesale", "Wholesale"),
                ],
                help_text="Classification of the beneficiary",
            ),
        )
    ]
