# Generated by Django 4.2.14 on 2024-08-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlement", "0031_alter_beneficiary_classification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiary",
            name="beneficiary_alias",
            field=models.TextField(
                blank=True, help_text="Beneficiary alias", null=True
            ),
        ),
    ]
