# Generated by Django 4.2.14 on 2024-08-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0034_beneficiaryfieldconfig_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiarybroker',
            name='deleted',
            field=models.BooleanField(default=False, help_text="The brokers's beneficiary deleted status"),
        ),
        migrations.AddField(
            model_name='beneficiarybroker',
            name='enabled',
            field=models.BooleanField(default=True, help_text='The beneficiary enable status'),
        ),
    ]
