# Generated by Django 4.2.14 on 2024-08-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0035_beneficiarybroker_deleted_beneficiarybroker_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='default_purpose',
            field=models.IntegerField(choices=[(1, 'Other'), (2, 'Payment for Goods Purchased'), (3, 'Payment for Goods Purchased - Equipment'), (4, 'Payment for Goods Purchased - Finished Goods'), (5, 'Payment for Goods Purchased - Manufacturing Materials'), (6, 'Payment for International Payroll'), (7, 'Payment for Services Purchased'), (8, 'Payment to fund Overseas Operations'), (9, 'Repatriate Funds Abroad'), (10, 'Repatriate Funds to US')], default=1, help_text='Beneficiary Purpose'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='default_purpose_description',
            field=models.TextField(help_text='Please be specific, eg. “This company is a supplier of leather goods. Each month we pay this company for wallets and belts”', null=True),
        ),
    ]
