# Generated by Django 4.2.14 on 2024-08-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlement", "0036_beneficiary_default_purpose_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="account_type",
            field=models.CharField(
                blank=True,
                choices=[("checking", "Checking"), ("saving", "Saving")],
                help_text="The type of the account",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="beneficiary",
            name="default_purpose",
            field=models.IntegerField(
                choices=[
                    (1, "Other"),
                    (2, "Payment for Goods Purchased"),
                    (3, "Payment for Goods Purchased - Equipment"),
                    (4, "Payment for Goods Purchased - Finished Goods"),
                    (5, "Payment for Goods Purchased - Manufacturing Materials"),
                    (6, "Payment for International Payroll"),
                    (7, "Payment for Services Purchased"),
                    (8, "Payment to fund Overseas Operations"),
                    (9, "Repatriate Funds Abroad"),
                    (10, "Repatriate Funds to US"),
                ],
                default=1,
                help_text="Beneficiary default payment purpose",
            ),
        ),
    ]
