# Generated by Django 4.2.14 on 2024-08-16 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0037_wallet_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('synced', 'Synced'), ('pending_update', 'Pending Update'), ('pending_delete', 'Pending Delete'), ('deleted', 'Deleted'), ('partially_synced', 'Partially Synced')], default='draft', help_text='The status of the beneficiary', max_length=60),
        ),
        migrations.CreateModel(
            name='BeneficiaryBrokerSyncResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sync', models.DateTimeField(help_text='Last beneficiary broker sync', null=True)),
                ('sync_errors', models.TextField(help_text='Any Sync error from the last attempt', null=True)),
                ('beneficiary_broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settlement.beneficiarybroker')),
            ],
        ),
    ]
