# Generated by Django 4.2.15 on 2024-08-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0039_alter_beneficiary_bank_routing_code_type_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('synced', 'Synced'), ('pending_update', 'Pending Update'), ('pending_delete', 'Pending Delete'), ('deleted', 'Deleted'), ('partially_synced', 'Partially Synced'), ('partially_deleted', 'Partially Deleted')], default='draft', help_text='The status of the beneficiary', max_length=60),
        ),
    ]
