# Generated by Django 4.2.15 on 2024-08-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0040_alter_beneficiary_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(help_text='The account number associated with the wallet', max_length=100, null=True),
        ),
    ]
