# Generated by Django 4.2.15 on 2024-09-06 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0015_alter_configurationtemplate_instrument_type'),
        ('settlement', '0043_alter_beneficiary_bank_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiarybrokersyncresult',
            name='beneficiary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settlement.beneficiary'),
        ),
        migrations.AddField(
            model_name='beneficiarybrokersyncresult',
            name='broker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='broker.broker'),
        ),
        migrations.AlterField(
            model_name='beneficiarybrokersyncresult',
            name='beneficiary_broker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settlement.beneficiarybroker'),
        ),
    ]
