# Generated by Django 4.2.15 on 2024-09-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0043_alter_beneficiary_bank_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='bank_routing_code_type_3',
            field=models.CharField(blank=True, choices=[('swift', 'SWIFT'), ('ifsc', 'IFSC'), ('sort_code', 'SORT Code'), ('ach_code', 'ACH Code'), ('branch_code', 'Branch Code'), ('bsb_code', 'BSB Code'), ('bank_code', 'Bank Code'), ('aba_code', 'ABA Code'), ('transit_code', 'Transit Code'), ('generic', 'Generic'), ('wallet', 'Wallet'), ('location_id', 'Location ID'), ('branch_name', 'Branch Name'), ('cnaps', 'CNAPS'), ('fedwire', 'Fedwire'), ('interac', 'Interac'), ('check', 'Check')], help_text='Bank Routing Code 3 Type', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='bank_routing_code_value_3',
            field=models.TextField(blank=True, help_text='Bank routing code 3', null=True),
        ),
    ]
