# Generated by Django 4.2.15 on 2024-09-06 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0045_separate_beneficiary_broker_relation_on_beneficiary_sync_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiarybrokersyncresult',
            name='beneficiary_broker',
        ),
    ]
