# Generated by Django 4.2.15 on 2024-09-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0045_beneficiary_inter_bank_routing_code_type_3_and_more'),
        ('settlement', '0046_remove_beneficiarybrokersyncresult_beneficiary_broker'),
    ]

    operations = [
    ]
