# Generated by Django 4.2.15 on 2024-09-14 00:40

from django.db import migrations


def create_periodic_task(apps, schema_editor):
    IntervalSchedule = apps.get_model('django_celery_beat', 'IntervalSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    schedule, _ = IntervalSchedule.objects.get_or_create(
        every=1,
        period='days',
    )

    PeriodicTask.objects.create(
        name='Sync Wallets from Brokers',
        task='main.apps.settlement.tasks.sync_wallet_from_brokers',
        interval=schedule,
        args='[]',
        kwargs='{}',
    )


def delete_periodic_task(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    PeriodicTask.objects.filter(
        name='Sync Wallets from Brokers'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0001_initial'),
        ('settlement', '0047_merge_20240909_1731'),
    ]

    operations = [
        migrations.RunPython(create_periodic_task, delete_periodic_task),
    ]
