# Generated by Django 4.2.15 on 2024-09-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0048_auto_20240914_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='default',
            field=models.BooleanField(default=False, help_text='Set wallet as default funding account'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='nickname',
            field=models.CharField(help_text='Wallet nickname', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('closed', 'Closed'), ('pending', 'Pending')], default='active', help_text='The status of the wallet', max_length=20),
        ),
    ]
