# Generated by Django 4.2.15 on 2024-10-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0049_wallet_default_wallet_nickname_alter_wallet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='default_purpose',
            field=models.IntegerField(choices=[(1, 'Intercompany Payment'), (2, 'Purchase/Sale of Goods'), (3, 'Purchase/Sale of Services'), (4, 'Personnel Payment'), (5, 'Financial Transaction'), (6, 'Other')], default=6, help_text='Beneficiary default payment purpose'),
        ),
    ]
