# Generated by Django 4.2.7 on 2024-02-16 11:41

from django.db import migrations


def populate_pangea_schedule_intervals(apps, schema_editor):
    from django_celery_beat.models import IntervalSchedule
    # IntervalSchedule = apps.get_model('django_celery_beat', 'IntervalSchedule')

    schedule_01m, created = IntervalSchedule.objects.get_or_create(
        every=1,
        period=IntervalSchedule.MINUTES,
    )
    schedule_05m, created = IntervalSchedule.objects.get_or_create(
        every=5,
        period=IntervalSchedule.MINUTES,
    )
    schedule_10m, created = IntervalSchedule.objects.get_or_create(
        every=10,
        period=IntervalSchedule.MINUTES,
    )
    schedule_15m, created = IntervalSchedule.objects.get_or_create(
        every=15,
        period=IntervalSchedule.MINUTES,
    )
    schedule_30m, created = IntervalSchedule.objects.get_or_create(
        every=30,
        period=IntervalSchedule.MINUTES,
    )
    schedule_01h, created = IntervalSchedule.objects.get_or_create(
        every=1,
        period=IntervalSchedule.HOURS,
    )


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
        ('django_celery_beat', '0001_initial')
    ]

    operations = [
        migrations.RunPython(populate_pangea_schedule_intervals)
    ]
