# Generated by Django 4.2.7 on 2024-02-14 13:27

from django.db import migrations

def populate_config(apps, schema_editor):
    Config = apps.get_model('core', 'Config')
    config, created = Config.objects.get_or_create(
        path='dataprovider/services/importer/provider_handler/ice/home_triangulation_pairs',
        defaults={'value': [["USD", "EUR"]]}
    )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_config),
    ]
