# Generated by Django 4.2.7 on 2024-02-22 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_pangea_schedule_intervals'),
        ('core', '0003_fx_spot_pair_provider'),
    ]

    operations = [
    ]
