# Generated by Django 4.2.10 on 2024-02-28 06:55

from django.db import migrations


def delete_config(apps, schema_editor):
    Config = apps.get_model('core', 'Config')
    try:
        obj = Config.objects.get(path='system/fxpair/supported_home_currencies')
        obj.delete()
    except:
        pass

    try:
        obj = Config.objects.get(path='dataprovider/services/importer/provider_handler/ice/home_triangulation_pairs')
        obj.delete()
    except:
        pass


def populate_config(apps, schema_editor):
    Config = apps.get_model('core', 'Config')

    obj, created = Config.objects.update_or_create(
        path='system/fxpair/triangulation_currencies',
        defaults={'value': ["EUR", ]}
    )

    obj, created = Config.objects.update_or_create(
        path='system/fxpair/home_currencies',
        defaults={'value': ["USD", ]}
    )

    obj, created = Config.objects.update_or_create(
        path='system/fxpair/id_provider/mode',
        defaults={'value': "quote"}
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_merge_20240222_1920"),
    ]

    operations = [
        migrations.RunPython(delete_config),
        migrations.RunPython(populate_config),

    ]
