# Generated by Django 4.2.10 on 2024-02-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20240222_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='path',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
