# Generated by Django 4.2.10 on 2024-02-28 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_config_path'),
        ('core', '0005_auto_20240228_0655'),
    ]

    operations = [
    ]
