# Generated by Django 4.2.11 on 2024-04-23 15:43

from django.db import migrations


def setup_eod_workflow(apps, schema_editor):
    from django_celery_beat.models import IntervalSchedule
    from django_celery_beat.models import PeriodicTask
    import json

    schedule_01d, created = IntervalSchedule.objects.update_or_create(
        every=1,
        period=IntervalSchedule.DAYS,
    )

    task, created = PeriodicTask.objects.get_or_create(
        name="EOD master workflow",
        defaults={
            'interval': schedule_01d,
            'task': 'main.apps.core.tasks.eod.eod_master_workflow',
            'args': json.dumps([]),
            'kwargs': json.dumps({}),
            'enabled': False,
        }
    )


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_add_eod_benchmark_hour_config'),
    ]

    operations = [
        migrations.RunPython(setup_eod_workflow),
    ]
