# Generated by Django 4.2.11 on 2024-04-15 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0007_add_eod_benchmark_hour_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorOauth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vendor",
                    models.CharField(choices=[("GOOGLE", "Google")], default="GOOGLE"),
                ),
                ("service", models.CharField(max_length=100)),
                ("access_token", models.CharField(max_length=250)),
                ("refresh_token", models.CharField(max_length=250)),
                ("client_id", models.CharField(max_length=80)),
                ("client_secret", models.CharField(max_length=40)),
                ("scopes", models.JSONField()),
                ("token_expiry", models.DateTimeField()),
                ("token_uri", models.CharField(max_length=2048)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
