# Generated by Django 4.2.11 on 2024-04-25 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20240423_1643'),
        ('core', '0008_vendorserviceoauth'),
    ]

    operations = [
    ]
