# Generated by Django 4.2.11 on 2024-05-23 19:24

from django.db import migrations


def populate_config(apps, schema_editor):
    Config = apps.get_model('core', 'Config')

    obj, created = Config.objects.update_or_create(
        path='system/notification/internal_recipients',
        defaults={'value': ""}
    )


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0009_merge_0008_auto_20240423_1643_0008_vendorserviceoauth'),
    ]

    operations = [
        migrations.RunPython(populate_config)
    ]
