# Generated by Django 3.2.8 on 2023-08-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='use_in_average',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
