# Generated by Django 3.2.8 on 2023-09-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_alter_country_use_in_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='strictness_of_capital_controls',
            field=models.CharField(choices=[('strict_gate', 'Strict Gate'), ('soft_gate', 'Soft Gate'), ('persuasive', 'Persuasive'), ('open', 'Open')], default='open', max_length=12, verbose_name='Strictness of Capital Controls'),
        ),
        migrations.AlterField(
            model_name='country',
            name='use_in_average',
            field=models.BooleanField(default=False),
        ),
    ]
