from django.db import migrations


def add_templates(apps, schema_editor):
    EmailTemplate = apps.get_model('post_office', 'EmailTemplate')
    EmailTemplate.objects.create(**{
        "name": "wallet_transfer_completed",
        "description": "wallet_transfer_completed",
        "subject": "FX Wallet Transfer Receipt",
        "content": "FX TRANSFER COMPLETE\r\n\r\n\r\nThis is confirmation for the following FX Wallet transfer:\r\n\r\n\r\nTransfer from: {{ account_from }}\r\nTransfer to: {{ account_to }}\r\nAmount: {{ currency_to.mnemonic }} {{ currency_to.symbol }}{{ amount_to|floatformat:\"2g\" }}\r\nSettlement Amount: {{ currency_from.mnemonic }} {{ currency_from.symbol }}{{ amount_from|floatformat:\"2g\" }}\r\nRate: {{ rate }}\r\nDelivery Date: {{ date }}\r\nFee: {{ fee }}",
        "html_content": "{% extends \"core/email/layout/base.html\" %}\r\n{% load static %}\r\n{% block content %}\r\n  <p class=\"center\"><img src=\"{% static 'media/email/status/success.png' %}\"/></p>\r\n  <h2 class=\"pangea-title center\">FX TRANSFER COMPLETE</h2>\r\n  <p class=\"padded center\">The following forward will settle in 72 hours.</p>\r\n  <p class=\"padded center\">Please ensure the target account is correct.</p>\r\n  <table class=\"full-width table striped\">\r\n    <tr>\r\n      <td>Transfer from:</td>\r\n      <td class=\"content-right\">{{ account_from }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Transfer to:</td>\r\n      <td class=\"content-right\">{{ account_to }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Amount:</td>\r\n      <td class=\"content-right\">{{ currency_to.mnemonic }} {{ currency_to.symbol }} {{ amount_to|floatformat:\"2g\" }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Settlement Amount:</td>\r\n      <td class=\"content-right\">{{ currency_from.mnemonic }} {{ currency_from.symbol }} {{ amount_from|floatformat:\"2g\" }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Rate:</td>\r\n      <td class=\"content-right\">{{ rate }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Delivery Date:</td>\r\n      <td class=\"content-right\">{{ date }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Fee:</td>\r\n      <td class=\"content-right\">{{ fee }}</td>\r\n    </tr>\r\n  </table>  \r\n{% endblock %}",
    })
    EmailTemplate.objects.create(**{
        "name": "wallet_transfer_waiting",
        "description": "wallet_transfer_waiting",
        "subject": "FX Wallet Transfer Needs Approval",
        "content": "APPROVAL NEEDED\r\n\r\n\r\nThe following FX Wallet transfer was submitted for approval.\r\n\r\n\r\nTransfer from: {{ account_from }}\r\nTransfer to: {{ account_to }}\r\nAmount: {{ currency_to.mnemonic }} {{ currency_to.symbol }}{{ amount_to|floatformat:\"2g\" }}\r\nSettlement Amount: Calculated at review\r\nRate: Calculated at review\r\nDelivery Date: {{ date }}\r\nFee: {{ fee }}",
        "html_content": "{% extends \"core/email/layout/base.html\" %}\r\n{% load static %}\r\n{% block content %}\r\n  <p class=\"center\"><img src=\"{% static 'media/email/status/checking.png' %}\"/></p>\r\n  <h2 class=\"pangea-title center\">APPROVAL NEEDED</h2>\r\n  <p class=\"padded center\">The following FX Wallet transfer was submitted for approval.</p>\r\n  <table class=\"full-width table striped\">\r\n    <tr>\r\n      <td>Transfer from:</td>\r\n      <td class=\"content-right\">{{ account_from }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Transfer to:</td>\r\n      <td class=\"content-right\">{{ account_to }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Amount:</td>\r\n      <td class=\"content-right\">{{ currency_from.mnemonic }} {{ currency_from.symbol }} {{ amount_from|floatformat:\"2g\" }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Settlement Amount:</td>\r\n      <td class=\"content-right\">Calculated at review</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Rate:</td>\r\n      <td class=\"content-right\">Calculated at review</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Delivery Date:</td>\r\n      <td class=\"content-right\">{{ date }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Fee:</td>\r\n      <td class=\"content-right\">{{ fee }}</td>\r\n    </tr>\r\n  </table>\r\n  <p class=\"center\">\r\n    <a class=\"btn bold pangea-dark-button\" href=\"{{ url }}\"\r\n       style=\"display: inline-block !important; padding: 9px; width: auto;\">\r\n      REVIEW TRANSFER &rarr;</a>\r\n  </p>\r\n{% endblock %}",
    })
    EmailTemplate.objects.create(**{
        "name": "payment_initiated",
        "description": "payment_initiated",
        "subject": "Payment Initiated",
        "content": "PAYMENT INITIATED\r\n\r\n\r\nYou have initiated the following payment:\r\n\r\n\r\nTransfer from: {{ account_from }}\r\nTransfer to: {{ account_to }}\r\nPayment Amount: {{ currency_from.mnemonic }} {{ currency_from.symbol }}{{ amount_from|floatformat:\"2g\" }}\r\nMethod: {{ method }}\r\nEstimated Delivery Date: {{ date }}\r\nPurpose of Payment: {{ purpose }}\r\nPayment Reference: {{ reference }}\r\nFee: {{ fee }}",
        "html_content": "{% extends \"core/email/layout/base.html\" %}\r\n{% load static %}\r\n{% block content %}\r\n  <p class=\"center\"><img src=\"{% static 'media/email/status/pending.png' %}\"/></p>\r\n  <h2 class=\"pangea-title center\">PAYMENT INITIATED</h2>\r\n  <p class=\"padded center\">You have initiated the following payment:</p>\r\n  <table class=\"full-width table striped\">\r\n    <tr>\r\n      <td>Transfer from:</td>\r\n      <td class=\"content-right\">{{ account_from }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Transfer to:</td>\r\n      <td class=\"content-right\">{{ account_to }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Payment Amount:</td>\r\n      <td class=\"content-right\">{{ currency_from.mnemonic }} {{ currency_from.symbol }} {{ amount_from|floatformat:\"2g\" }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Method:</td>\r\n      <td class=\"content-right\">{{ method }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Estimated Delivery Date:</td>\r\n      <td class=\"content-right\">{{ date }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Purpose of Payment:</td>\r\n      <td class=\"content-right\">{{ purpose }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Payment Reference:</td>\r\n      <td class=\"content-right\">{{ reference }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Fee:</td>\r\n      <td class=\"content-right\">{{ fee }}</td>\r\n    </tr>\r\n  </table>\r\n{% endblock %}",
    })
    EmailTemplate.objects.create(**{
        "name": "payment_waiting",
        "description": "payment_waiting",
        "subject": "Payment Needs Approval",
        "content": "APPROVAL NEEDED\r\n\r\n\r\nThe following payment needs approval:\r\n\r\n\r\nTransfer from: {{ account_from }}\r\nTransfer to: {{ account_to }}\r\nPayment Amount: {{ currency_from.mnemonic }} {{ currency_from.symbol }}{{ amount_from|floatformat:\"2g\" }}\r\nMethod: {{ method }}\r\nEstimated Delivery Date: {{ date }}\r\nPurpose of Payment: {{ purpose }}\r\nPayment Reference: {{ reference }}\r\nFee: {{ fee }}\r\nReview Payment: {{ url }}",
        "html_content": "{% extends \"core/email/layout/base.html\" %}\r\n{% load static %}\r\n{% block content %}\r\n  <p class=\"center\"><img src=\"{% static 'media/email/status/checking.png' %}\"/></p>\r\n  <h2 class=\"pangea-title center\">APPROVAL NEEDED</h2>\r\n  <p class=\"padded center\">The following payment needs approval:</p>\r\n  <table class=\"full-width table striped\">\r\n    <tr>\r\n      <td>Transfer from:</td>\r\n      <td class=\"content-right\">{{ account_from }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Transfer to:</td>\r\n      <td class=\"content-right\">{{ account_to }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Payment Amount:</td>\r\n      <td class=\"content-right\">{{ currency_from.mnemonic }} {{ currency_from.symbol }} {{ amount_from|floatformat:\"2g\" }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Method:</td>\r\n      <td class=\"content-right\">{{ method }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Estimated Delivery Date:</td>\r\n      <td class=\"content-right\">{{ date }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Purpose of Payment:</td>\r\n      <td class=\"content-right\">{{ purpose }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Payment Reference:</td>\r\n      <td class=\"content-right\">{{ reference }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Fee:</td>\r\n      <td class=\"content-right\">{{ fee }}</td>\r\n    </tr>\r\n  </table>\r\n  <p class=\"center\">\r\n    <a class=\"btn bold pangea-dark-button\" href=\"{{ url }}\"\r\n       style=\"display: inline-block !important; padding: 9px; width: auto;\">\r\n      REVIEW PAYMENT &rarr;</a>\r\n  </p>\r\n{% endblock %}",
    })
    EmailTemplate.objects.create(**{
        "name": "payment_completed",
        "description": "payment_completed",
        "subject": "Payment Complete",
        "content": "PAYMENT COMPLETE\r\n\r\n\r\nThe following payment has been completed:\r\n\r\n\r\nTransfer from: {{ account_from }}\r\nTransfer to: {{ account_to }}\r\nPayment Amount: {{ currency_from.mnemonic }} {{ currency_from.symbol }}{{ amount_from|floatformat:\"2g\" }}\r\nMethod: {{ method }}\r\nDelivery Date: {{ date }}\r\nPurpose of Payment: {{ purpose }}\r\nPayment Reference: {{ reference }}\r\nFee: {{ fee }}",
        "html_content": "{% extends \"core/email/layout/base.html\" %}\r\n{% load static %}\r\n{% block content %}\r\n  <p class=\"center\"><img src=\"{% static 'media/email/status/success.png' %}\"/></p>\r\n  <h2 class=\"pangea-title center\">PAYMENT COMPLETE</h2>\r\n  <p class=\"padded center\">The following payment has been completed:</p>\r\n  <table class=\"full-width table striped\">\r\n    <tr>\r\n      <td>Transfer from:</td>\r\n      <td class=\"content-right\">{{ account_from }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Transfer to:</td>\r\n      <td class=\"content-right\">{{ account_to }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Payment Amount:</td>\r\n      <td class=\"content-right\">{{ currency_from.mnemonic }} {{ currency_from.symbol }} {{ amount_from|floatformat:\"2g\" }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Method:</td>\r\n      <td class=\"content-right\">{{ method }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Delivery Date:</td>\r\n      <td class=\"content-right\">{{ date }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Purpose of Payment:</td>\r\n      <td class=\"content-right\">{{ purpose }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Payment Reference:</td>\r\n      <td class=\"content-right\">{{ reference }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Fee:</td>\r\n      <td class=\"content-right\">{{ fee }}</td>\r\n    </tr>\r\n  </table>\r\n{% endblock %}",
    })
    EmailTemplate.objects.create(**{
        "name": "deposit_waiting",
        "description": "deposit_waiting",
        "subject": "Deposit Needs Approval",
        "content": "APPROVAL NEEDED\r\n\r\n\r\nThe following deposit needs approval:\r\n\r\n\r\nTransfer from: {{ account_from }}\r\nTransfer to: {{ account_to }}\r\nPayment Amount: {{ currency_to.mnemonic }} {{ currency_to.symbol }}{{ amount_to|floatformat:\"2g\" }}\r\nMethod: {{ method }}\r\nEstimated Delivery Date: {{ date }}\r\nPayment Reference: {{ reference }}\r\nFee: {{ fee }}\r\nReview Payment: {{ url }}",
        "html_content": "{% extends \"core/email/layout/base.html\" %}\r\n{% load static %}\r\n{% block content %}\r\n  <p class=\"center\"><img src=\"{% static 'media/email/status/checking.png' %}\"/></p>\r\n  <h2 class=\"pangea-title center\">APPROVAL NEEDED</h2>\r\n  <p class=\"padded center\">The following deposit needs approval:</p>\r\n  <table class=\"full-width table striped\">\r\n    <tr>\r\n      <td>Transfer from:</td>\r\n      <td class=\"content-right\">{{ account_from }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Transfer to:</td>\r\n      <td class=\"content-right\">{{ account_to }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Payment Amount:</td>\r\n      <td class=\"content-right\">{{ currency_to.mnemonic }} {{ currency_to.symbol }} {{ amount_to|floatformat:\"2g\" }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Method:</td>\r\n      <td class=\"content-right\">{{ method }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Estimated Delivery Date:</td>\r\n      <td class=\"content-right\">{{ date }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Payment Reference:</td>\r\n      <td class=\"content-right\">{{ reference }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Fee:</td>\r\n      <td class=\"content-right\">{{ fee }}</td>\r\n    </tr>\r\n  </table>\r\n  <p class=\"center\">\r\n    <a class=\"btn bold pangea-dark-button\" href=\"{{ url }}\"\r\n       style=\"display: inline-block !important; padding: 9px; width: auto;\">\r\n      REVIEW DEPOSIT &rarr;</a>\r\n  </p>\r\n{% endblock %}",
    })
    EmailTemplate.objects.create(**{
        "name": "deposit_initiated",
        "description": "deposit_initiated",
        "subject": "Deposit Initiated",
        "content": "DEPOSIT INITIATED\r\n\r\n\r\nYou have initiated the following deposit:\r\n\r\n\r\nTransfer from: {{ account_from }}\r\nTransfer to: {{ account_to }}\r\nPayment Amount: {{ currency_to.mnemonic }} {{ currency_to.symbol }}{{ amount_to|floatformat:\"2g\" }}\r\nMethod: {{ method }}\r\nEstimated Delivery Date: {{ date }}\r\nPurpose of Payment: {{ purpose }}\r\nPayment Reference: {{ reference }}\r\nFee: {{ fee }}",
        "html_content": "{% extends \"core/email/layout/base.html\" %}\r\n{% load static %}\r\n{% block content %}\r\n  <p class=\"center\"><img src=\"{% static 'media/email/status/pending.png' %}\"/></p>\r\n  <h2 class=\"pangea-title center\">DEPOSIT INITIATED</h2>\r\n  <p class=\"padded center\">You have initiated the following deposit:</p>\r\n  <table class=\"full-width table striped\">\r\n    <tr>\r\n      <td>Transfer from:</td>\r\n      <td class=\"content-right\">{{ account_from }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Transfer to:</td>\r\n      <td class=\"content-right\">{{ account_to }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Payment Amount:</td>\r\n      <td class=\"content-right\">{{ currency_to.mnemonic }} {{ currency_to.symbol }} {{ amount_to|floatformat:\"2g\" }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Method:</td>\r\n      <td class=\"content-right\">{{ method }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Estimated Delivery Date:</td>\r\n      <td class=\"content-right\">{{ date }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Purpose of Payment:</td>\r\n      <td class=\"content-right\">{{ purpose }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Payment Reference:</td>\r\n      <td class=\"content-right\">{{ reference }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Fee:</td>\r\n      <td class=\"content-right\">{{ fee }}</td>\r\n    </tr>\r\n  </table>\r\n{% endblock %}",
    })
    EmailTemplate.objects.create(**{
        "name": "deposit_received",
        "description": "deposit_received",
        "subject": "Deposit Received",
        "content": "DEPOSIT RECEIVED\r\n\r\n\r\nThe following deposit has been received:\r\n\r\n\r\nTransfer from: {{ account_from }}\r\nTransfer to: {{ account_to }}\r\nPayment Amount: {{ currency_to.mnemonic }} {{ currency_to.symbol }}{{ amount_to|floatformat:\"2g\" }}\r\nMethod: {{ method }}\r\nDate: {{ date }}\r\nPayment Reference: {{ reference }}\r\nFee: {{ fee }}",
        "html_content": "{% extends \"core/email/layout/base.html\" %}\r\n{% load static %}\r\n{% block content %}\r\n  <p class=\"center\"><img src=\"{% static 'media/email/status/success.png' %}\"/></p>\r\n  <h2 class=\"pangea-title center\">DEPOSIT RECEIVED</h2>\r\n  <p class=\"padded center\">The following deposit has been received:</p>\r\n  <table class=\"full-width table striped\">\r\n    <tr>\r\n      <td>Transfer from:</td>\r\n      <td class=\"content-right\">{{ account_from }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Transfer to:</td>\r\n      <td class=\"content-right\">{{ account_to }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Payment Amount:</td>\r\n      <td class=\"content-right\">{{ currency_to.mnemonic }} {{ currency_to.symbol }} {{ amount_to|floatformat:\"2g\" }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Method:</td>\r\n      <td class=\"content-right\">{{ method }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Date:</td>\r\n      <td class=\"content-right\">{{ date }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Payment Reference:</td>\r\n      <td class=\"content-right\">{{ reference }}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Fee:</td>\r\n      <td class=\"content-right\">{{ fee }}</td>\r\n    </tr>\r\n  </table>\r\n{% endblock %}",
    })


class Migration(migrations.Migration):
    dependencies = [
        ('notification', '0002_add_templates'),
    ]

    operations = [
        migrations.RunPython(add_templates)
    ]
