# Generated by Django 4.2.7 on 2024-02-13 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reports", "0001_volatility_movement_threshold"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("avg_buy", models.FloatField(null=True)),
                ("avg_sell", models.FloatField(null=True)),
                ("avg_buy_saved", models.FloatField(null=True)),
                ("avg_sell_gained", models.FloatField(null=True)),
                ("avg_saved", models.FloatField(null=True)),
                ("min_buy_saved", models.FloatField(null=True)),
                ("min_sell_gained", models.FloatField(null=True)),
                ("avg_execution_spread", models.FloatField(null=True)),
                ("avg_start_spread", models.FloatField(null=True)),
                ("spread_benefit", models.FloatField(null=True)),
                ("max_execution_spread", models.FloatField(null=True)),
                ("avg_wait", models.FloatField(null=True)),
                ("min_wait", models.FloatField(null=True)),
                ("max_wait", models.FloatField(null=True)),
                (
                    "ai_model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="metric_aimodel",
                        to="ai.aimodel",
                    ),
                ),
            ],
        ),
    ]
