# Generated by Django 4.2.10 on 2024-02-24 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='ai_model',
        ),
    ]
