# Generated by Django 4.2.10 on 2024-02-24 00:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_metric_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='ai_model',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
