# Generated by Django 4.2.11 on 2024-04-17 20:11

from django.db import migrations


def setup_jobs_to_generate_activity_reports(apps, schema_editor):
    from django_celery_beat.models import IntervalSchedule
    from django_celery_beat.models import PeriodicTask
    import json

    schedule_01d, created = IntervalSchedule.objects.update_or_create(
        every=1,
        period=IntervalSchedule.DAYS,
    )

    task_for_daily_activity, created = PeriodicTask.objects.get_or_create(
        name="Daily - Platform Activity Report (EXCEL)",
        defaults={
            'interval': schedule_01d,
            'task': 'main.apps.reports.tasks.platform_activity_report.task_to_generate_platform_activity_report',
            'args': json.dumps(['daily', 'XLSX']),
            'kwargs': json.dumps({}),
            'enabled': False,
        }
    )

    task_for_weekly_activity, created = PeriodicTask.objects.get_or_create(
        name="Weekly - Platform Activity Report (EXCEL)",
        defaults={
            'interval': schedule_01d,
            'task': 'main.apps.reports.tasks.platform_activity_report.task_to_generate_platform_activity_report',
            'args': json.dumps(['weekly', 'XLSX']),
            'kwargs': json.dumps({}),
            'enabled': False,
        }
    )

    task_for_monthly_activity, created = PeriodicTask.objects.get_or_create(
        name="Monthly - Platform Activity Report (EXCEL)",
        defaults={
            'interval': schedule_01d,
            'task': 'main.apps.reports.tasks.platform_activity_report.task_to_generate_platform_activity_report',
            'args': json.dumps(['monthly', 'XLSX']),
            'kwargs': json.dumps({}),
            'enabled': False,
        }
    )


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0004_metric_ai_model'),
    ]

    operations = [
        migrations.RunPython(setup_jobs_to_generate_activity_reports),
    ]
