# Generated by Django 4.2.15 on 2024-10-11 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20240523_1924'),
        ('auditlog', '0015_alter_logentry_changes'),
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        ('reports', '0005_auto_20240417_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.config',),
        ),
        migrations.CreateModel(
            name='GroupResult',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_results.groupresult',),
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Log Entries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auditlog.logentry',),
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_results.taskresult',),
        ),
        migrations.CreateModel(
            name='VendorOauth',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.vendoroauth',),
        ),
    ]
