apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
    name: gcp-store-for-pangea-development
spec:
    provider:
        gcpsm:
            projectID: pangea-development
            auth:
                workloadIdentity:
                    clusterLocation: us-central1
                    clusterName: pangea-development-autopilot-cluster
                    clusterProjectID: pangea-development
                    serviceAccountRef:
                        name: external-secrets
                        namespace: pangea-development
